### ISSUE TITLE
Firefox not updating posts (2 problems here)

### ISSUE THREAD

**Issue by ryanmavilia** [HubPress/hubpress.io#100]
First, hooray :100: issues opened and more than half have been closed so :+1: @anthonny !

I made a post in Firefox, it was published and appeared on my site. But the posts tab still showed it as unpublished and no matter how much I pressed the published button this would not change (however the post stayed up).

![new cap](https://cloud.githubusercontent.com/assets/1221512/6238994/7d400eb0-b6cd-11e4-96f0-f627e02e2534.PNG)

So I switched to chrome and I unpublished the post then deleted from my GitHub (because I only needed the post for testing anyways). After deleting it I got on with Firefox and the post was still there (looked the exact same as the image above) even though it was clearly deleted on Chrome. 

So I deleted my Firefox DB and that cured the problem however obviously we don't want people on Firefox to have to do this every time.

**Comment by anthonny** [comment]
Yeah 100 issues :beers: !
As i writed in the README, Firefox is not well supported by i don't use transaction when i write in indexedDb.
It's in my Todolist

**Comment by ryanmavilia** [comment]
Ok glad to hear it!
