### ISSUE TITLE
Add a default title when creating a new post

### ISSUE THREAD

**Issue by naveensrinivasan** [HubPress/hubpress.io#103]
When creating a new post if the title is missing it causes an error https://github.com/HubPress/hubpress.io/issues/39 while saving.  To avoid this a new post could have a default title something like this

` = Change the Title  `

**Comment by jaredmorgs** [comment]
That's a really great suggestion!

I think we could go further with this and add some basic AsciiDoc syntax as
a starting point that folks could either delete or re-purpose.

Maybe some of the following:

* numbered list,
* ordered list,
* image block,
* code block,
* video embed.

And some section headings that show the user how to nest things correctly.

**Comment by anthonny** [comment]
Yes it's a great suggestion, maybe we can add an option in the settings : 
- [x] add sample content in new post

And for all posts add a placeholder to indicate that a title is required, and disable buttons if no title

**Comment by jaredmorgs** [comment]
Good idea. That way you can turn it off when you are accustomed to the syntax.

If you can detect there is no title, how about you put an error message on save that there is no title and show basic syntax how to add it in the error message.

**Comment by jaredmorgs** [comment]
Hey @anthonny 

Could I create a basic AsciiDoc template and create a PR for it. Which part of the tree would I commit this to?

**Comment by anthonny** [comment]
@jaredmorgs sure you can! You can commit on the development branch

**Comment by jaredmorgs** [comment]
Which part of the development tree should I commit into? Is there a
specific directory you would pull this info from?

On Tue, Feb 24, 2015, 19:32 Anthonny Quérouil <notifications@github.com>
wrote:

@jaredmorgs <https://github.com/jaredmorgs> sure you can! You can commit on
the development branch

**Comment by anthonny** [comment]
You can create a sample file in the docs directory

**Comment by jaredmorgs** [comment]
Done, and ready to implement when you are ready.

**Comment by eeherring** [comment]
You should also mention to add two spaces away from the title otherwise the first line or lines are cut off. I looked at the ASCDoc doesn't mention it

**Comment by jaredmorgs** [comment]
I'll make that change right now. Good pick up!
