### ISSUE TITLE
Petit problème

### ISSUE THREAD

**Issue by vojjor** [HubPress/hubpress.io#104]
Bonsoir!

Je me permet de poster se message en français sachant que les développeurs parlent français et que je suis une quiche en anglais.

Donc, j'ai suivis le tutoriel, aucun problème sauf pour poster sur mon blog, je créer un nouveau Post, j'ajoute un "= My title" (ceci est obligatoire d'après ce que j'ai compris?), je valide mon post, mais j'ai un message d'erreur qui s'affiche.

Publishing
An error has occurred, see your console for more informations.

Ceci est dut à quoi?

**Comment by anthonny** [comment]
Salut @vojjor et bienvenue !

Si tu veux utiliser l'url `vojjor.github.io`, il faut que tu renommes ton repository avec le même nom `vojjor.github.io`.

Si tu veux utiliser l'adresse `vojjor.github.io/blog`, il faut bien renommer ton repository en `blog` (comme tu l'as fait) mais tu dois travailler sur la branche `gh-pages` (ce aue tu as fait également).
Mais dans les settings de ton repository, tu dois définir la branche `gh-pages` comme étant la branche **par défaut**.

**Comment by jaredmorgs** [comment]
I don't speak French, but I gather this is about issues with @vojjor already using the username.github.com domain and therefore not changing the branch to gh-pages and configuring that config.json on the gh-pages branch (made the same mistake myself).

**Comment by vojjor** [comment]
@anthonny Voilà mon erreur, je n'avais pas mis la branch gh-pages par défaut. Merci ! Sinon super boulot, bonne continuation.

@jaredmorgs Thank you, my problem is resolved.

**Comment by jaredmorgs** [comment]
Merci @vojjor
