### ISSUE TITLE
"Share this post" shared URL broken

### ISSUE THREAD

**Issue by adericbourg** [HubPress/hubpress.io#105]
At the bottom of a post, the link to that post submitted to the sharer is broken (always links to `<my_correct_root_url>/blogundefined`).

Tested on Casper theme.

**Comment by jaredmorgs** [comment]
I found this as well. 

Confirmed bug.

**Comment by anthonny** [comment]
@adericbourg @jaredmorgs  can you merge from upstream and retry ?

**Comment by adericbourg** [comment]
Still broken here. 

You can check there: http://www.dericbourg.net/blog/2015/02/16/Quest-ce-qui-me-motive-en-tant-que-developpeur.html

My repo: https://github.com/adericbourg/blog

**Comment by anthonny** [comment]
It's your browser cache, i added a note on the diff of your commit

**Comment by adericbourg** [comment]
Agreed! Sorry for that...

**Comment by anthonny** [comment]
No problem ;)
