### ISSUE TITLE
Add "delete post" feature

### ISSUE THREAD

**Issue by adericbourg** [HubPress/hubpress.io#106]
I did not found how to delete a post in the admin interface. Il could be useful to delete a draft for instance.

**Comment by jaredmorgs** [comment]
Yes, you can only "take down the post" using the arrow button in the lower
right of the screen. But that doesn't completely remove it from your admin
console.

To workaround the issue, you can keep the post in your hubpress post list,
but name it something like "USE_ME - New Post" and write your next blog
post in this post. It repurposes the post which means you don't have all
these old posts in your list.

Alternatively, you can permanently delete a post by going into your github
repo and manually deleting the .adoc file, then go through the HubPress
admin interface and force the site to regenerate by altering a parameter in
the settings page.

Neither of these work-arounds are intuitive.

**Comment by adericbourg** [comment]
Thanks.

I just tried the second method but it does not seem to be working: the article is properly deleted on my repo but not in web interface (I changed "theme" setting).

I may have missed something, though.

**Comment by ryanmavilia** [comment]
What browser are you using?

**Comment by adericbourg** [comment]
Firefox 35.0.1

**Comment by ryanmavilia** [comment]
Ok so HubPress is currently having issues with FireFox I will get on my main pic and comment back with instructions of fixing the error.

**Comment by ryanmavilia** [comment]
1. Exit out of Firefox. (Make sure to do this)
2. Under your user profile (you need show hidden file enabled) go to AppData\Roaming\Mozilla\Firefox\Profiles
3. You will see two folders, one of them will contain a folder called storage.
4. Open the storage folder then open the persistent folder. You should see you site's domain in that folder. 
5. Click your domain's folder and delete it.
6. Log back into your HubPress and the post you deleted should be gone.

These steps work for me but they may not work for you so please report back with your findings.

**Comment by adericbourg** [comment]
That worked, thanks!

(but it's not very convenient :) )

**Comment by ryanmavilia** [comment]
Don't worry the delete function and Firefox bugs will be fixed in the future! :smile:

**Comment by metasean** [comment]
:+1:

**Comment by mubix** [comment]
Would love to see this feature!

**Comment by wols** [comment]
+1

**Comment by anthonny** [comment]
It will be in the next version ;)

<img width="342" alt="capture d ecran 2016-03-30 a 22 05 58" src="https://cloud.githubusercontent.com/assets/2006548/14155820/b07aebba-f6c3-11e5-9d3d-70ede50d4ecf.png">

**Comment by anthonny** [comment]
The feature is here, i close this issue.
Feel free to reopen if necessary

**Comment by mdramos** [comment]
Is there an undo?

**Comment by anthonny** [comment]
No there is no undo, but you can easily find your post with the github history

**Comment by mdramos** [comment]
yea thats what I resolved to doing, but a simple undo capability would be nice, or at least a warning message. Its pretty easy to accidentally click that delete button.
