### ISSUE TITLE
[uno theme] No post on home page

### ISSUE THREAD

**Issue by adericbourg** [HubPress/hubpress.io#107]
Using *uno* theme, no post are displayed on the home page. No message in console is displayed.

Using their URL, they are still available.

**Comment by jaredmorgs** [comment]
@adericbourg, what is the blog url?

Did you recently rebuild the site after applying the theme? Sometimes the posts can take a while to repopulate as the site index is rebuilt (based on my personal experience).

**Comment by guillaumevidal** [comment]
Are the posts displayed when you click the Blog button? That's how that theme works AFAIK, no post directly on the page.

**Comment by anthonny** [comment]
@adericbourg do you still have no post on home page?

**Comment by adericbourg** [comment]
Now I've got the *Blog* button. It works and it ok.
