### ISSUE TITLE
Lag when writing longer posts, or browser remains open

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#108]
Hey @anthonny

I've noticed a bit of lag as I continue writing a larger post. For example, when I press and hold the delete key, the way the text is deleted on screen is choppy. The same goes for typing: text input lags about a quarter second behind keystrokes.

I have a feeling this could be solved by changing the live preview update to around 2 seconds (maybe 3, if this wouldn't result in users thinking there was "delay" in rendering), rather than instantaneously as it seems to be now.

I'm making this judgement based on how you described the process by which HubPress renders and writes a local recovery copy of the blog to memory so content isn't lost if the browser crashes. I have a feeling this could be causing a performance regression as the cached file grows.

**Comment by ryanmavilia** [comment]
What's the approximate word range? I will try to emulate and report back.

**Comment by jaredmorgs** [comment]
When deleting if you have a long sentence, just hold backspace and observe
the behavior.

When typing, it can sometime be every four characters if you are a fast
typist. I've had it lag up to about 10 characters at one point.

**Comment by ryanmavilia** [comment]
So I used some lorem ipsum and held the backspace down with a resource monitor up. The red circle where CPU usage drops off is when I let go of the backspace. The line that is near the top behind that point was generated while holding the backspace down.
![graph capture](https://cloud.githubusercontent.com/assets/1221512/6262027/3d3dc972-b7c9-11e4-9025-f94041423d55.PNG)

**Comment by jaredmorgs** [comment]
Let me just clarify: that was the CPU of the PC?!

If it was the PC, then I feel there's a definite performance tuning need
with this aspect of HubPress.

Thanks for running the test. This would explain why things run even slower
on Android (even though I'm using a Shield Tablet (2GB RAM, K1 Processor)).

**Comment by anthonny** [comment]
@ryanmavilia @jaredmorgs Thank you for your tests!

I added an input in the settings form to set the delay before rendering HTML, default is 200ms.
Actually, it's only on the dev branch, i'll release soon

**Comment by jaredmorgs** [comment]
Perfect, that will solve the problem. I'll update the README on
/develelopment now so it reflects reality.

**Comment by anthonny** [comment]
It should be better now, could you merge and test again ? If it's ok, for you we can close the issue

**Comment by jaredmorgs** [comment]
This seems better for me now.
