### ISSUE TITLE
[Theme] <site>/tags/[tagname] broken on "Saga" theme

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#109]
Hi @anthonny 

I have found a issue with the tag cloud on this theme. I'm not sure it is the same as other themes or not. 

If you access http://jaredmorgs.github.io and click on any of the tags I've used, you get a 404

**Comment by ryanmavilia** [comment]
Casper tags don't work either: unoriginality.me

**Comment by jaredmorgs** [comment]
Ahh, right. That would suggest @anthonny might have to do some tweaks for
compatibility down the track. Roadmap item, mate?

**Comment by guillaumevidal** [comment]
Tags are not implemented for now, see [issue 38](https://github.com/HubPress/hubpress.io/issues/38).

**Comment by anthonny** [comment]
Tags are implemented now, could you merge from upstream and test again?

**Comment by jasonswearingen** [comment]
works for me (using Saga, pulled 0.2 from upstream).

I republished my site after pulling though (clicked edit on a post, and clicked update)
