### ISSUE TITLE
Dexie.min.js.map and opal.js.map not found

### ISSUE THREAD

**Issue by lebesnec** [HubPress/hubpress.io#112]
I have the following JS errors when I try to save a post :

GET http://lebesnec.github.io/hubpress.io/hubpress/scripts/Dexie.min.js.map 404 (Not Found)
GET http://lebesnec.github.io/__opal_source_maps__/opal.js.map 404 (Not Found)

My GitHub Page Domain is already in use, so I didn't use it. I have probably missed some configuration ?

**Comment by anthonny** [comment]
Hi @lebesnec !

Your configuration seems to be good :+1: 

Can you show me the content you try to save ? Remember that a post require a title (`= My Title`)

**Comment by lebesnec** [comment]
It works with the title (the post is saved and published),
but the JS errors are still here.
Actually I have theses errors as soon as I'm logged to http://lebesnec.github.io/hubpress.io/hubpress

**Comment by anthonny** [comment]
Cool!

These errors are here because js files are minified, the map file is used to make a link with the original source file.
Like as said in my previous comment, consider these 404 as a warning :smile: 
I'll add the map in a next version.

**Comment by lebesnec** [comment]
ok ! Thanks for the quick answer !

**Comment by anthonny** [comment]
You're welcome
