### ISSUE TITLE
Instillation problem: Page not found

### ISSUE THREAD

**Issue by eeherring** [HubPress/hubpress.io#114]
Hey I was trying to get the hubpress.io to install into my computer and I followed the steps you presented however I ended up getting a Page not found instead of the image you stated would pop up.

site: https://eeherring.github.io/

**Comment by anthonny** [comment]
Hi @eeherring!

In the settings of your repository, you must rename it to: 
eeherring.github.io

**Comment by eeherring** [comment]
@anthonny 

oh...well is my face red.
