### ISSUE TITLE
Wordpress Importer?

### ISSUE THREAD

**Issue by B-iggy** [HubPress/hubpress.io#116]
Hey anthonny,

thanks for your work! I just forked your rep :)
After long time using wordpress I finally want a secure, fast website -> static. A little bit CMS would be great also, so I give HubPress a try.

Is there a way to import my posts from wordpress to HubPress? Like jekyll Wordpress Importer?
Isn't a Issue at all, just a question.
Thank you.

**Comment by jaredmorgs** [comment]
I know there is no native HubPress importer for external blogs, but if you
could save your posts out as text files (stripped of all HTML formatting if
possible) you could then easily mark those up to AsciiDoc.

I did a search and there seems to be an approach documented on
http://wordpress.stackexchange.com/questions/53069/export-all-posts-as-individual-plain-txt-files
that should do exactly this.

If you are going to do this, I'd recommend doing the initial conversion on
a PC using something like Atom Editor (with the AsciiDoctor plug-in
installed). Then copy the text over into new blog post containers in
HubPress UI.

Don't forget to set the :published_at: parameter in each post so you don't
lose the blog post order that was present on your original site.

**Comment by jaredmorgs** [comment]
The other option is to save the HTML pages and use https://cloudconvert.com
to convert the files in a batch. I used this when converting my exported
Blogger posts to Markdown. Using the markdown option would at least get you
half way there to AsciiDoc.

**Comment by B-iggy** [comment]
Sounds very smart. Thank you, I give it a try / understand the way I have to do it.
Can be closed.
Good night.

**Comment by anthonny** [comment]
Thank you @jaredmorgs

**Comment by bodiam** [comment]
I'm actually working on a more robust version, in which you can just export the Wordpress files (as a big XML file), and convert them to AsciiDoc automatically, and reimport them to HubPress. Most of it is working now, I can share if there's still interest.

**Comment by danmbox** [comment]
@bodiam that would make sense -- is your tool open source?

**Comment by bodiam** [comment]
@danmbox It's opensource indeed: https://github.com/bodiam/hubpress-importer

**Comment by YannDanthu** [comment]
Hi @bodiam,

Is it possible to update your README.adoc to explain how to use hubris-importer ?

thanks

**Comment by bodiam** [comment]
Hi @YannDanthu ,

It's only a rough version, please take a look at https://github.com/bodiam/hubpress-importer/blob/master/src/main/java/nl/jworks/wordpress/importer/HtmlToAsciiDocConverter.java to see what it does.
