### ISSUE TITLE
Remote save error

### ISSUE THREAD

**Issue by alxndr** [HubPress/hubpress.io#117]
(as you asked for in #115)

When I try to edit a post and save it, I get this error: "Remote save / An error has occurred, see your console for more informations."

The Network tab shows a GET request to the post's URL, but a 401 response, with this content:
```
{
  documentation_url: "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
  message: "Must specify two-factor authentication OTP code."
}
```

**Comment by anthonny** [comment]
Hi @alxndr!
This bug should be fixed, could you merge from upstream and retry (a relog in Hubpress is required)?

**Comment by alxndr** [comment]
Worked for saving and then publishing one draft post!

When I tried to edit an already-published post however, it appears to have caused the same error about 2FA.

**Comment by anthonny** [comment]
@alxndr do you still have a problem with 2FA ? I can't reproduce :cry:

**Comment by alxndr** [comment]
I think this is working now, thank you!
