### ISSUE TITLE
Shouldn't allow `timeago`

### ISSUE THREAD

**Issue by hinaloe** [HubPress/hubpress.io#118]
Some of Ghost theme like **Saga** uses *XX ago* in DateTime-format (ex: `{{date published_at timeago='true'}}`)
But in HubPress, that won't update until regenerate article or page.

**Comment by anthonny** [comment]
Hi @hinaloe!
Thank you for having filled this issue, i confirm that there is a bug

**Comment by anthonny** [comment]
@hinaloe i think we can close this issue, right?

**Comment by hinaloe** [comment]
:+1:
