### ISSUE TITLE
attempted to use a custom domain

### ISSUE THREAD

**Issue by eeherring** [HubPress/hubpress.io#119]
So I have installed the github.io already so I wanted to test if it would allow me to use a custom domain as well. So I followed the instructions and I got a 404 error page; just asking to see if that is supposed to happen or not

**Comment by anthonny** [comment]
Hi @eeherring,

Did you make the following configuration on your provider? https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/

I'll add a link in the documentation.

**Comment by eeherring** [comment]
there we go, thanks
