### ISSUE TITLE
Synchronization notification typo

### ISSUE THREAD

**Issue by eeherring** [HubPress/hubpress.io#120]
When I sign onto the hubpress the there is a grammatical error in the notification of it letting me know my devices have Synced:

Synchronization
The synchronization is ended

It should read as: 

Synchronization
The synchronization has ended

or something like:
Synchronization Complete

It's a small thing but I wanted to point it out

**Comment by anthonny** [comment]
Thank you :+1: 
I close because there is already an issue for this bug #32

**Comment by jaredmorgs** [comment]
What files/paths on /development are these pop up messages stored?

I'll take a look quickly tomorrow and do a grammar pass if you like,
Anthonny.

**Comment by jaredmorgs** [comment]
Whoops, got it:  hubpress/scripts/app.js

Any others?

**Comment by anthonny** [comment]
@jaredmorgs, `hubpress/scripts/app.js` is the minified version.
You can change the source on the development branch : 
https://github.com/HubPress/hubpress.io/blob/development/src/hubpress/scripts/stores/AppStore.js#L39

Then i'll generate a new dist version

**Comment by jaredmorgs** [comment]
I've made the change:

* are the changes I've made going to fit inside the pop-up box constraints?
* is this message reused by other parts of the code, and if so will it be
relevant still?

If these two questions are no-issue, then you can go ahead and create a
stable. :D
