### ISSUE TITLE
Another grammar error found

### ISSUE THREAD

**Issue by eeherring** [HubPress/hubpress.io#121]
So I wanted to save a post while I try to figure out how to upload an image into the pic file which I couldn't seem to get to commit to just comment on. So when I go to hit save it says there is an error reading:

Remote save
An error has occurred, see your console for more informations

so yeah grammar error there too, should read information.

and yes I know I forgot to put in the title that's why it wouldn't save

**Comment by jaredmorgs** [comment]
Hey @anthonny, what part of the code does this error content occur in? I
need to copy edit it.

Is there a way to tell me all the places/modules where these error messages
are? I'll ping you on hangouts.

**Comment by anthonny** [comment]
Should be fix now, could you merge the upstream and close the issue if it's ok @eeherring ?

**Comment by anthonny** [comment]
Feel free to reopen if necessary.
