### ISSUE TITLE
notifications won't close at times

### ISSUE THREAD

**Issue by eeherring** [HubPress/hubpress.io#122]
Yeah sometimes the notifications won't close, by themselves or me clicking on them or the close button them. Have to refresh the page to make them removed.

Also the notification of you saving your settings pop-up twice every time once before the page refreshes, and again after it refreshes

**Comment by anthonny** [comment]
Hi @eeherring !
Thank you for having filled this issue.
For the notifications which do not close, there the #3 

I keep open for the multiple notifications, there is effectively a bug :+1:

**Comment by eeherring** [comment]
@anthonny 
No problem, I wanted to help out with this project the best that I can. So I figure the best place to start would be try to find bugs in the blog. I know I've brought up already found problems but I blame it only finding time to look at the blog is pretty late at night.
