### ISSUE TITLE
Readme on spanish 

### ISSUE THREAD

**Issue by jelitox** [HubPress/hubpress.io#124]
hi! 
I was translating into Spanish the readme file for some friends and I think it could serve to many more people!.
[here is the raw url!](https://raw.githubusercontent.com/jelitox/jelitox.github.io/master/README-es.adoc)

**Comment by anthonny** [comment]
Thank you so much!
If you want you can put this doc in the `docs` directory on the **development** branch and make a pull request. Then i'll merge it and you'll appear as contributors, wdyt?

**Comment by jelitox** [comment]
excellent!

2015-02-28 6:19 GMT-04:30 Anthonny Quérouil <notifications@github.com>:

> Thank you so much!
> If you want you can put this doc in the docs directory on the
> *development* branch and make a pull request. Then i'll merge it and
> you'll appear as contributors, wdyt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/124#issuecomment-76521161>
> .
>



-- 
Javier Enrique León
0416- 2546908
GNU/Linux user  # 327958
 Huella de clave = DAEB 6C39 6592 E3DC FAE4
639E 56C4 3D37 A045 ABBF
Running Linux!

[Mis Blogs... ]
http://jelitox.unplug.org.ve/
<http://jelitox.unplug.org.ve/>http://jelitox.plug.org.ve/
<http://jelitox.unplug.org.ve/>

[Grupo de Usuarios de Software Libre de Portuguesa]

www.plug.org.ve

**Comment by isidrorg** [comment]
Thanks @jelitox but.... you forgot the initial `¿` in the `Qué es HubPress?`` sentence ^^.

**Comment by jelitox** [comment]
ready, fix the initial ¿ and accents, 
@anthonny   i make the pull!.

**Comment by anthonny** [comment]
Thnak you again, i close the issue
