### ISSUE TITLE
No highlighting Source

### ISSUE THREAD

**Issue by viejOMs** [HubPress/hubpress.io#126]
In most themes highlighting code on a post doesn't seem to work. I even tried the recommended way by ASCIIdoctor to set it `:source-highlighter: prettify`. Where can I change the default values? I tried in the codemirror.css but nothing seems to happen (plus some values are not standard to what some highlighters seem to have use; .typ but not sure how it was name in codemirror.css)

**Comment by jaredmorgs** [comment]
Highlighting is not currently implemented. @Anthonny is aware of it. I
believe this has already been reported (by me😀).

**Comment by viejOMs** [comment]
my bad! (:stuck_out_tongue_winking_eye:) Perhaps I missed it when I was scrolling looking for a similar issue. Shall we close it?

**Comment by jaredmorgs** [comment]
I'm definitely looking forward to code highlighting as well. Being an open
source guy, I have a fair few posts with code samples in them. Feel free to
self-close the issue, and thanks for using HubPress!
