### ISSUE TITLE
The `token` attribute is deprecated

### ISSUE THREAD

**Issue by hinaloe** [HubPress/hubpress.io#128]
[The `token` attribute is deprecated](https://developer.github.com/v3/oauth_authorizations/#list-your-authorizations) (?)

https://github.com/HubPress/hubpress.io/blob/development/src/hubpress/scripts/services/AuthServices.js#L115

[Breaking changes to Authorizations API responses on April 20](https://developer.github.com/changes/2015-02-20-migration-period-removing-authorizations-token/)

sorry, I don't know detail...

**Comment by anthonny** [comment]
:+1: Thank you!
