### ISSUE TITLE
[Cross Device][UX] Refresh Issues with Settings When Connecting On Separate Devices

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#13]
This morning, I've been doing most of my config on my Laptop.

Just out of curiosity, I logged back into my tablet instance, and noticed a bug.

Steps to reproduce:

1. Log onto the PC and open settings
2. Change the summary or something obvious.
3. Save changes.
4. Log onto tablet and open settings
5. Observe results

Actual results

The settings you changed on the PC are not automatically synced when you first open the settings. You need to refresh the page to get the PC settings merged into the tablet settings.

Expected results

When you authenticate again and open settings, a refresh trigger is automatically called to get the latest info.

**Comment by dan-blanchard** [comment]
My settings don't even show up consistently in the same browser tab on the same machine.

**Comment by jaredmorgs** [comment]
I've noticed that the settings issue you've experienced @dan-blanchard also happens in the same tab on Chrome Android. I had to back out to the post menu then back into the settings screen. I captured this same bug in #9

**Comment by anthonny** [comment]
I close this issue, feel free to reopen if necessary
