### ISSUE TITLE
ReadMore link failed

### ISSUE THREAD

**Issue by malys** [HubPress/hubpress.io#135]
Thanks you for this project.
I have installed hubpress this week and after publishing a new post, I was detected that ReadMore link isn't generated correctly.

ex:
> https://malys.github.io2014807-redirection-de-port-sous-windows.adoc/
> see http://malys.github.io/

Bye

**Comment by anthonny** [comment]
Hi @malys !
I opened/closed a PR yesterday to tell you that the :published_at: should have the following format : 
`yyyy-mm-dd`

**Comment by anthonny** [comment]
It seems to be good now, right?

**Comment by malys** [comment]
yes 
Thank you I didn't seen your merge request.
Thank you for your job.
Bye
