### ISSUE TITLE
[enhancement] Soundcloud/other embeds

### ISSUE THREAD

**Issue by guillaumevidal** [HubPress/hubpress.io#136]
It would be nice to be able to embed Soundclound tracks/albums to hubpress posts.
I didn't find anything conclusive about using html in the posts, I think that's not supported.
So, feature request: because Youtube isn't everything :tm:

**Comment by anthonny** [comment]
Hi @guillaumevidal !

You can use [Block passthroughs](http://asciidoctor.org/docs/user-manual/#pass-bl)

![capture d ecran de 2015-03-17 11 26 27](https://cloud.githubusercontent.com/assets/2006548/6685279/9e107bee-cc98-11e4-8646-7f481f10abba.png)

https://raw.githubusercontent.com/demo-hubpress/demo-hubpress.github.io/master/_posts/2015-03-14-0140-alternative-title-new-post.adoc

https://demo-hubpress.github.io/2015/03/14/0140-alternative-title-new-post.html

**Comment by jaredmorgs** [comment]
http://asciidoctor.org/docs/user-manual/#audio should work if you
substitute the local file in the example for the URL of the Soundcloud
track. Right?

**Comment by anthonny** [comment]
@jaredmorgs i don't think that the audio display the beautiful player of soundcloud, but we can write a macro in the asciidoctor project.

**Comment by guillaumevidal** [comment]
Thanks, that's awesome! 
Thanks for checking out the track too :wink: 
Would the Audio tag actually work with, for instance, a soundcloud url, which doesn't give you the actual filename anywhere?

**Comment by jaredmorgs** [comment]
The only way to find out is to give it a go, Guillaume. ;)

**Comment by anthonny** [comment]
> Thanks, that's awesome! 

I'm so glad each time i'm reading this kind of comment :smiley:

**Comment by guillaumevidal** [comment]
@jaredmorgs : Results are in, it doesn't work !
Anyway, this is resolved, closing.

**Comment by guillaumevidal** [comment]
As it turns out, the passthrough doesn't seem to work with another iframe embed, this one from bandcamp:

https://guillaumevidal.github.io/2015/03/17/Jam-of-the-Day-2.html

https://raw.githubusercontent.com/guillaumevidal/guillaumevidal.github.io/master/_posts/2015-03-17-Jam-of-the-Day-2.adoc

It works in the preview but not in the post (at least I can't see it from latest chrome, ie, and android chrome).

**Comment by anthonny** [comment]
In the source of your iframe, remove the **http:** and keep **//bandcamp...**
Your blog is expose on https and your iframe refered a source in http (mix content)

![capture](https://cloud.githubusercontent.com/assets/2006548/6731498/8faf169c-ce45-11e4-9e39-95e915ffd64a.png)

It seems you work in **http** when you admin your hubpress (that's why it workss in the preview), you should use **https** too.

**Comment by guillaumevidal** [comment]
Haha, that was quick!
Thanks, I see. I must remember to check the console next time something doesn't look right...

**Comment by anthonny** [comment]
Feel free to reopen if necessary :smile:

**Comment by heyallan** [comment]
README states that embeds from YouTube and Vimeo are possible. Good.
Now it could be also helpful to add a note stating that other embeds are also possible. With a link to [Block passthroughs](http://asciidoctor.org/docs/user-manual/#pass-bl) maybe?

**Comment by jaredmorgs** [comment]
I've added this information to the /development branch of the README.adoc.

Thanks everyone for your efforts in working out how to do this.
