### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by daenney** [HubPress/hubpress.io#142]
I know it's been implemented with 0.2.0 but how do I actually use it? Does it automatically detect code blocks, can I specify a highlighter to be used (language) and which languages are actually supported?

**Comment by anthonny** [comment]
Hi @daenney!

Yes, code blocks are automatically detected, actually the highlighter is **highlight.js** and you can specify your language, for example ruby : 

```
[source,ruby]
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
```

You can find more informations in the asciidoctor documentation : 
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

**Comment by daenney** [comment]
Thanks!

**Comment by anthonny** [comment]
You're welcome
