### ISSUE TITLE
Support iPad

### ISSUE THREAD

**Issue by tomgue** [HubPress/hubpress.io#144]
Est-ce que le support des navigateur tablette est planifié ?

Dans l'état, après être loger aucune fonction ne fonctionne, éditer, enregistrer, ...

Une roadmap est dispo ?

**Comment by anthonny** [comment]
Bonjour @tomgue,

HubPress fonctionne sur tablette/mobile sous Android.
Actuellement HubPress ne peut pas fonctionner avec Safari car ce navigateur ne supporte pas IndexedDb http://caniuse.com/#search=indexeddb.
Une solution pourrait être d'utiliser un polyfill comme https://github.com/axemclion/IndexedDBShim

La prochaine milestone est là https://github.com/HubPress/hubpress.io/milestones/0.3.0

Je cherche encore la bonne organisation :smile:

**Comment by tomgue** [comment]
Merci @anthonny pour ta réponse je vais tester ce polyfill, décidément safari et toujours a la bourre !!!

En tous cas merci pour HubPress ;)

**Comment by anthonny** [comment]
De rien, n'hésites pas à venir déposer un feedback sur tes tests de polyfill quand tu auras un moment :+1:

**Comment by buzhug** [comment]
Bonjour. Néophyte en recherche d'un moyen de faire une application avec base de données sans souscrire un compte sur l'apple store,  j'ai testé le lien polyfill (en recopiant le script indiqué ainsi que les modifs à envisager) sur un iPad mini (iOS8) sans effet …
je l'ai testée directement sous Textastic, logiciel avec lequel je l'ai éditée, et aussi en l'ouvrant par Safari après l'avoir envoyée par mail … si vous avez réussi à faire un test qui fonctionne, d'avance merci pour vos scripts
