### ISSUE TITLE
Missing documentation link: Video reference in Updating HubPress

### ISSUE THREAD

**Issue by metasean** [HubPress/hubpress.io#149]
In the Updating HubPress README (https://github.com/HubPress/hubpress.io#updating-hubpress) it states, "To learn how to do this correctly (there’s a trick to it the first time you pull changes from upstream), you can watch the following video to learn the correct process." But there is no video embedded or video link.

p.s. I'm really psyched about HubPress!

**Comment by anthonny** [comment]
Github do not deal well with the macro `video`.
Here is the link https://www.youtube.com/watch?v=KCylB780zSM

**Comment by jaredmorgs** [comment]
Maybe we should use the jekyll-asciidoc-quickstart to turn the readme into
a proper Asciidoc User Guide for HubPress. We could get stuff like a TOC
and proper video embeds. WDYT @Anthonny?

**Comment by metasean** [comment]
@anthonny - Thank you for the link!

@jaredmorgs - I know you weren't asking me, but projects that eat their own dogfood always get an extra cool point from me.  Not to mention, the subsequent forks and updated forks will have one more working example for reference purposes. :+1:

**Comment by metasean** [comment]
Original issue fixed.  Left open for possible replacement with proper Asciidoc version.

**Comment by eurusd** [comment]
学习了

**Comment by jaredmorgs** [comment]
The one thing I don't want to do is mess up the workflow the other
community translators have with the existing README.

I think you can close this issue MetaSean, and I'll create another issue
specifically related to converting the README to a formalized User Guide.

**Comment by anthonny** [comment]
@jaredmorgs jekyll-asciidoc-quickstart could be a relevant choice

**Comment by jaredmorgs** [comment]
#153 created to track the User Guide discussion.

**Comment by eurusd** [comment]
标题 不支持中文？

**Comment by metasean** [comment]
@eurusd  - I think you want issue #43 

---

Since @jaredmorgs opened issue #153  :+1: , I'm closing this issue.

**Comment by anthonny** [comment]
Thank you @metasean :+1:

**Comment by metasean** [comment]
@anthonny - No, thank you for starting HubPress!  I just wish I had more time, knowledge, or money so that I could do more to help move it forward.
