### ISSUE TITLE
[Enhancement] [Editor] Pop-out AsciiDoc Cheat Sheet

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#15]
I was originally going to suggest putting in some snippet buttons into the UI, but what might be better would be to include a basic AsciiDoc CheatSheet directly in the app. Maybe pop it over the editor window so folks can look at the code view and copy paste the samples directly into their blog post.

Or even cooler would be to have a button beside each one that copied and pasted the code wherever the cursor was in the code view. :smile:

**Comment by metasean** [comment]
:+1:

**Comment by jaredmorgs** [comment]
This is fixed in 0.7.0. See https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/more_info_asciidoc.html
