### ISSUE TITLE
Clicking on the 'Support' link on the HubPress home page does not do what is expected

### ISSUE THREAD

**Issue by phayz** [HubPress/hubpress.io#151]
Clicking on the 'Support' link on the HubPress home page scrolls down to the 'Get App' section. There should instead be some text which explains the available support options.

**Comment by jaredmorgs** [comment]
Just confirming that this is on the http://hubpress.io main page?

**Comment by jaredmorgs** [comment]
I've submitted a basic fix for this in a PR. The Support section of the homepage is set to the footer. @anthonny seems to have a web support form coded, but I can understand why he didn't activate that email form. ;)

**Comment by phayz** [comment]
Jared,

The UX is a little odd when using the main menu of the HubPress site [1].
The "Get App" menu item is permanently highlighted, having a different
background than the other menu items. If I click on the "Support" menu
item, the view of the page scrolls down but at the top appears the section
with the text "Get App - Fork the hubpress.io repository and get started!".
In the footer section there is no mention of available methods to obtain
support. The addition of words along the lines of "If you need help with
HubPress, either raise a GitHub issue or tweet @hubpressio." would be
helpful.


[1] http://hubpress.io

**Comment by jaredmorgs** [comment]
Yeah that's basically what I've done. The absence of any text here is the
real issue. Hopefully @anthonny will merge the PR soon or do some
rethinking of the main site. I really like the one-page style of the
hubpress.io page.

**Comment by phayz** [comment]
Jared,

Thanks. I too like the one-page style of the Hubpress.io site. It seems to
be a new trend and definitely suits some sites, though not all.

**Comment by anthonny** [comment]
Fixed, @phayz thank you for having filled the issue :+1: 
@jaredmorgs thank you for the PR :smile: 

If it's ok for you @phayz, feel free to close the issue

**Comment by phayz** [comment]
Thanks, everybody for fixing this issue. The added text has resolved the problem IMHO.
