### ISSUE TITLE
What are the differences between `:hp-tags:` and `:keywords:`?

### ISSUE THREAD

**Issue by metasean** [HubPress/hubpress.io#152]
Obviously, `:hp-tags:` are interpreted as [metadata tags](https://en.wikipedia.org/wiki/Tag_%28metadata%29), but what was the thinking behind creating a hubpress-specific tag instead of using the existing AsciiDoc [`:keywords:`](http://asciidoctor.org/docs/user-manual/#keywords)?   Other than being displayed as blog tags, are there any other functional differences?

**Comment by jaredmorgs** [comment]
This is a very good question, @metasean and something I wondered about when first using HubPress. 

I would have thought that if an Asciidoc tag exists then it should be used in favour of a custom tag.  

Justifications for this include:

1. It makes the blog posts generated by HubPress truly portable if you should ever want to remove them from HubPress into another AsciiDoc blog platform.
2. It keeps things consistent with the Asciidoc suggested formatting (I hesitated using "standard" here because it isn't strictly a standard").

**Comment by anthonny** [comment]
ATM there is no functional differences.

I made some tests with awestruct before i create hubpress, it is partially for that i added this attributes (like `:awestruct-tags:` https://raw.githubusercontent.com/asciidoctor/asciidoctor.org/master/news/a-new-resource-for-asciidoc.adoc).

So i think that `tags` is more understandable than `keywords`, but i'm not sure that it is a sufficient argument.

There is this issue #145, if i add some extra-data, is-it still keywords? for example : 
`:hp-tags: title[タイトル]`

However, i agree with @jaredmorgs :keywords: is more "standard"

**Comment by jaredmorgs** [comment]
It's good to hear about the design decisions you chose when making HubPress
@anthonny . Keeping it open is the only way. ;)

Semantically, I also agree that "tags" is more recognizable in a blog
context. It's a tricky call...

**Comment by metasean** [comment]
I'm definitely agree that "tags" makes more sense, but "keywords" is already a standard.  I figured there was a progression that lead to hp-tags, and I think it's important to understand that progression.

That said, if :hp-tags: can support extra-data *that HubPress can easily tap into*, well that would just plain be awesome!  In particular, I love the way that [Gwern](http://www.gwern.net/index) adds a range of meta-data to his posts (e.g. [status & belief](http://www.gwern.net/About#belief-tags) [1]), and I'd like to do something similar but with my own tag categories [2].

However, for portability and standardization, I think it's probably more important (and lower hanging fruit) to have a configuration option to interpret `:keywords:` as tags, and default to that (i.e. new installations would display `:keywords:` as tags).

Alternatively, is it appropriate to suggest adding :tags: to AsciiDoc?  Are tags used outside of blogging, wikis, and related online documentation, i.e. is there an analog in the analog world?

--- 

[1] His are clearly done with predefined values, e.g. [notes, drafts, in progress, finished].
[2] Some of the ones I want will be predefined, but several will definitely be more open-ended and tag-like.

**Comment by jaredmorgs** [comment]
I'd say that changing any of the tag names at this point in the product's life would probably inconvenience long-standing users.

For example, I have a blog with 90 posts all using :hp-tags: so wouldn't really enjoy changing those and republishing.

The point about standardising is a good "lesson's learned" for future projects of this type.
