### ISSUE TITLE
如何删除文章？

### ISSUE THREAD

**Issue by ghost** [HubPress/hubpress.io#154]
请问 如何删除文章？发布的文章总是有错误。

**Comment by hanwencheng** [comment]
有错误的话直接编辑保存就可以了，如果想删除的话，在编辑文章的页面点击右下角的小箭头，把它下架就好。
要彻底删除相关文件，在本地的post文件夹里，删除之后commit到github就可以。

**Comment by eurusd** [comment]
谢谢

**Comment by anthonny** [comment]
I can't read this issue sorry :(
I close, feel free to reopen (in english please :smile: ) if necessary
