### ISSUE TITLE
文章不支持中文？

### ISSUE THREAD

**Issue by ghost** [HubPress/hubpress.io#155]
有解决办法吗？

**Comment by eurusd** [comment]
tags也不支持中文！！

**Comment by hanwencheng** [comment]
tags也不支持中文，英文的文档里都有说明，因为保存的文章是以标题名来作为文件名的，具体请添加 ':hp-alt-title' 加入英文标题，毕竟作者不是中国人，而且也在开发过程中。

**Comment by eurusd** [comment]
谢谢

**Comment by anthonny** [comment]
@hanwencheng thank you :+1:

**Comment by eurusd** [comment]
是的 
china

**Comment by anthonny** [comment]
I close, feel free to reopen if necessary
