### ISSUE TITLE
ios系统 任何浏览器 都不能登录后台

### ISSUE THREAD

**Issue by ghost** [HubPress/hubpress.io#158]
后台地址 http://fxdan.com/hubpress

**Comment by anthonny** [comment]
Hi @eurusd!
iOS is not supported yet because it does not support indexedDb http://caniuse.com/#search=indexeddb.

For the next tickets which you are going to create, could you use English please? I'll be easier for the community and me to understand you and help you :smile:

**Comment by eurusd** [comment]
谢谢

**Comment by eurusd** [comment]
我不会英语  ：（

**Comment by HiveSolution** [comment]
这里大多数人不会说中国话

**Comment by anthonny** [comment]
I close, feel free to reopen if necessary (in english please :smile: )
