### ISSUE TITLE
I think http://dev.hubpress.io/ is more cool than http://blog.hubpress.io/

### ISSUE THREAD

**Issue by tvvocold** [HubPress/hubpress.io#16]
RT

**Comment by sebie** [comment]
Isn't it just a different theme? 

To change themes, wouldn't you just change the default (`Casper`) in `hubpress/config.yml` to something from the `themes` folder?

**Comment by jaredmorgs** [comment]
@sebie is correct.

http://dev.hubpress.io/ is ichi
http://blog.hubpress.io/ is Casper
