### ISSUE TITLE
Too long paragraph, can't cut in CJK

### ISSUE THREAD

**Issue by hinaloe** [HubPress/hubpress.io#161]
as CJK language, there is no space between the words.
so Long sentence is regarded as one word, excerpt is very long.

Sample: http://hnle.tk/hubpress/

There is same issue on WordPress.
in Japanese, WordPress user can use [WP Multibyte Patch](https://wordpress.org/plugins/wp-multibyte-patch/), this is default included WordPress Japanese package.

One of this plugins function is `thing separated by a number of characters instead of the number of words the excerpt.`

Can you implement similar features?

**Comment by moshefeit** [comment]
Have you tried to manipulate it using [hard line break](http://asciidoctor.org/docs/asciidoc-writers-guide/#it-s-just-text-mate)?

**Comment by anthonny** [comment]
Hi @hinaloe,

I made a fix, could you have a look to http://demo-hubpress.github.io/ ? i have duplicated your blog post 坊っちゃん

If it's ok for you i'll add this fix in the next release

**Comment by hinaloe** [comment]
Thanks, That looks good!

**Comment by anthonny** [comment]
@hinaloe It seems to be good for you with the 0.3.0, right?

**Comment by hinaloe** [comment]
Right!
2015/04/19 7:19 "Anthonny Quérouil" <notifications@github.com>:
