### ISSUE TITLE
Subfolder?

### ISSUE THREAD

**Issue by greasan** [HubPress/hubpress.io#166]
I tried to place HubPress in a subfolder named "blog".

But HubPress loads themes using absolute urls?

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (theme.json, line 0)
http://greasan.github.io/themes/Casper/theme.json?dt=1427915138666

Background: I plan to develop a personal site in the same repo (root folder). Can HubPress run inside a subfolder?

**Comment by jaredmorgs** [comment]
Another approach is to set up you main site on http://greasan.github.io and
then create your HubPress instance in another repo and then code into your
main site a Blog tab that resolves to the hubpress repo.

**Comment by greasan** [comment]
Yeah, I can set it as "subfolder" by using gh-pages without custom domain. *facepalm*

But the – I think interesting – question remains: Is it possible to run HubPress in a subfolder of a repo?

**Comment by anthonny** [comment]
Hi @greasan!

Actually you can't run HubPress in a subfolder, at the moment the solution that @jaredmorgs has pointed is the only one

**Comment by greasan** [comment]
Thank you @anthonny.

I am happy with this solution.

Keep up the good work!

**Comment by greasan** [comment]
@anthonny The backend doesn't work with custom domain, right? Same as subfolder, I guess.
