### ISSUE TITLE
JS are missing 

### ISSUE THREAD

**Issue by r--w** [HubPress/hubpress.io#17]
While saving post:
![hubpress](https://cloud.githubusercontent.com/assets/1191700/6106417/800d04c6-b061-11e4-839e-a2587ef1ae4b.png)

**Comment by anthonny** [comment]
Hi @r--w,

Thank you for reporting this issue, i have knowledge of this point and i'll certainly remove the map files in the future version.

However, you should be able to save your post.

**Comment by r--w** [comment]
Can't save, please check:
![hubpress-2](https://cloud.githubusercontent.com/assets/1191700/6106747/800f189e-b064-11e4-9452-3ea3716a65a3.png)

**Comment by anthonny** [comment]
A title is required to save a post : 

```
= My title

Test
```

**Comment by r--w** [comment]
Ok, thanks ;)
