### ISSUE TITLE
Logo: broken image icon

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.io#171]
I have icon.png in my repo/images.  Have tried (a) icon.png,(b)  image::icon.png[] but do not see log after saving settings.  Ditto with file renamed log.pong.

**Comment by lametaweb** [comment]
Hi @jxxcarlson, you should use:
https://raw.githubusercontent.com/jxxcarlson/jxxcarlson.github.io/master/images/logo.png
Cheers.

**Comment by anthonny** [comment]
Thank you @lametaweb :)
I suppose that it's ok for you now @jxxcarlson, if not feel free to reopen the issue :+1:
