### ISSUE TITLE
Question about embedding javascript

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.io#172]
@anthonny , are you OK with embedding code as in 

http://home.noteshareblog.io/2015/04/02/Embedding-Javascript-Code.html ?

I use this at Noteshare.io, but am unsure of the security impliciations.  I'd appreciate your advice on this. (For now I only allow trusted users to embed code)

**Comment by lametaweb** [comment]
Hi again, I think it is a good technique. You should better put the script at the end of the document in order to let all the html load before, so the user won't experiment any delays when rendering the page.
Cheers.

**Comment by anthonny** [comment]
Thank you again @lametaweb :smile: 
I suppose that it's ok for you now @jxxcarlson, if not feel free to reopen the issue :smile:

**Comment by wols** [comment]
What's the way to do this?
