### ISSUE TITLE
newer posts lost after editing older post?

### ISSUE THREAD

**Issue by alxndr** [HubPress/hubpress.io#175]
I seem to have lost my newest two posts, when I went back and edited the 3rd-oldest post.

[Here's a commit publishing a post](https://github.com/alxndr/blog/commit/81bd203bb5935071b51ab4ada79ca8fde645db60) a week ago. Then two days ago [I edited a post from a month ago](https://github.com/alxndr/blog/commit/911979f2f8570064f7bf4646f02b807cb1c668cb) and some other posts. When I then updated the config file, the lists of posts it re-published didn't include that post from a week ago ([the commits after the update don't show that post](https://github.com/alxndr/blog/compare/42fb5a5...945d7d3)).

Since then I've tried republishing all entries by modifying my settings (changing the theme) a couple times, but the newest two posts are still missing.

Any ideas? Thanks.

(Also: are there supposed to be so many identical-looking "Publish page-1 tag" commits? e.g. [one](https://github.com/alxndr/blog/commit/4f4ed22d2791202ec1aff418f6738c3326d11467), [two](https://github.com/alxndr/blog/commit/162109bad9cada1ec1bd4f1786f491fba5c9a629), [three](https://github.com/alxndr/blog/commit/15bd6bb94a448b621aedf925bd2152c0230c9752), [four](https://github.com/alxndr/blog/commit/10eb264356939299239728463d5971a125a8d3d3)...)

**Comment by jaredmorgs** [comment]
Do you still see this behaviour happening now on 0.6.x

Sorry For not triaging his bug earlier.

**Comment by jaredmorgs** [comment]
Closing out due to lack of response from OR.

**Comment by alxndr** [comment]
I haven't noticed this happening lately. Thanks!
