### ISSUE TITLE
Allow the user to specify the excerpt for each post

### ISSUE THREAD

**Issue by Techbrunch** [HubPress/hubpress.io#177]
It would be a nice improvement to be able to specify the excerpt for each post as defined here: http://themes.ghost.org/v0.5.8/docs/excerpt

**Comment by benavern** [comment]
:+1:

**Comment by jaredmorgs** [comment]
This is out of scope for HubPress. 

HubPress provides a base set of themes that let you get started quickly.

If you want to make a theme customised, you need to make the adjustments that suit your needs.
