### ISSUE TITLE
Weird »

### ISSUE THREAD

**Issue by robsd** [HubPress/hubpress.io#179]
Can't remove wierd: »

It appears on every blog post - really annoying

**Comment by anthonny** [comment]
Hi @robsdixon!

The » link is like a "Read more" link, that is a part of the Casper theme

**Comment by adityadalal924** [comment]
You can change the » (`&raquo;`) into something else by editing [this line](https://github.com/HubPress/hubpress.io/blob/master/themes/Casper/partials/loop.hbs#L13) in the theme.
