### ISSUE TITLE
Provide author page on Casper theme.

### ISSUE THREAD

**Issue by adericbourg** [HubPress/hubpress.io#182]
Using _Casper_ theme, on a post, the _author_ link and _Read more posts by this author_ link are targeting the current post's URL.

See https://github.com/HubPress/hubpress.io/blob/master/themes/Casper/post.hbs#L43

**Comment by anthonny** [comment]
Yes that's because HubPress do not build an author page yet.

**Comment by jaredmorgs** [comment]
Themes will become much more robust with the addition of static pages in Release 9
