### ISSUE TITLE
Bad AsciiDoc behavior

### ISSUE THREAD

**Issue by adericbourg** [HubPress/hubpress.io#183]
AsciiDoc rendering goes wrong using inline code sample.

For instance, 

    `egrep '\(\ *\)\ *\{' /var/log/nginx/*`
    
Will render 

    egrep '\(\ \)\ *\{' /var/log/nginx/

instead of 

    egrep '\(\ *\)\ *\{' /var/log/nginx/*

(note the missing stars)

**Comment by anthonny** [comment]
Could you add this attribute in your document : 
`:compat-mode: true`

I can't explain now but i'll add an explanation soon.

**Comment by adericbourg** [comment]
Tested an approved. Thanks!

**Comment by jaredmorgs** [comment]
Ping me once done and I'll update the docs.

**Comment by jaredmorgs** [comment]
@anthonny I'm going to add this parameter to /development, and I'm going to have a go at working out what it does. 

You'll need to confirm once I'm done. I'll reference this issue once done.

**Comment by jaredmorgs** [comment]
This is in the User guide now. https://hubpress.gitbooks.io/hubpress-knowledgebase/content/parameters/compat_mode.html
