### ISSUE TITLE
Saving a post : Dexie.min.js.map is missing

### ISSUE THREAD

**Issue by achaabni** [HubPress/hubpress.io#186]
Trying to save a post it says :
GET https://achaabni.github.io/hubpress/scripts/Dexie.min.js.map 404 (Not Found)

**Comment by anthonny** [comment]
Hi @achaabni !

The name of your repository is achaabni.github.io so you must set master as the default branch and then update the config.json on master.

**Comment by achaabni** [comment]
Thanks 
but it's actually on Master and my config.json on Master is updated

**Comment by anthonny** [comment]
ok, your config is good,
Could you show me the content that you try to save?

**Comment by achaabni** [comment]
I probably find it.
I should update the settings page to define the number of posts by page. If there is not a value the post can't be saved.

Now it's solved.
Thank you for your quick response

**Comment by anthonny** [comment]
Hmmm if the number of posts by page is not set the default value is 10.
I think it's a cache problem, and when you have saved the settings, the config.json has been refreshed

No matter, if everything is OK now i can close this issue :smile:.

**Comment by achaabni** [comment]
Hmmmm Cache problem  :)
Well when I save the settings without putting a value the config will be changed to postsPerPage":""

At least I can configure it manually or by administration page by setting a value.
