### ISSUE TITLE
Why so slow so slow background login

### ISSUE THREAD

**Issue by fxdan** [HubPress/hubpress.io#188]
http://fxdan.github.io/hubpress/

**Comment by felixinx** [comment]
I have the same problem.
Check the console for errors

**Comment by felixinx** [comment]
Try to change your config to;
`{"meta":{"username":"fxdan","repositoryName":"fxdan.github.io","branch":"master","cname":"http://www.fxdan.com","delay":"2000"},"site":{"title":"FxDan","description":"记录点点滴滴...","postsPerPage":"10","url":"http://www.fxdan.com"},"socialnetwork":{},"theme":{"name":"Saga","url":"//fxdan.github.io/themes/Saga"}}`
(Change the theme to `Saga` and not `saga`) This error may come from the config file.

**Comment by jaredmorgs** [comment]
@fxdan are you still experiencing this issue? If you aren't would you mind closing off the issue?
