### ISSUE TITLE
Unable to save post

### ISSUE THREAD

**Issue by antoinesd** [HubPress/hubpress.io#189]
Hi,

I set up Hubpress by following the doc. Everything works perfectly until I try to save a post, then I get the following message:

*Remote save*
Your post was not saved. See your browser's developer console for the cause of the error.

This occurs on Opera 28 and Chrome 41 under Mac OS X 10.10.3. Looking in my JS console I don't see any error.

**Comment by anthonny** [comment]
Could you show me the content that you try to save?
The minimum requirement is a title, the following content should work:

= my title 

M'y content

**Comment by antoinesd** [comment]
My mistake. I pasted an Asciidoc content starting with a second level titel for my test. I just changed it to level one and now it works.
Perhaps having a less general error message could help dumb newbies like me to to avoid this kind of error?

Anyway, thanks for this nice piece of software

**Comment by anthonny** [comment]
> Perhaps having a less general error message could help dumb newbies like me to to avoid this kind of error?

i must have a review of all the messages :smile: 

> Anyway, thanks for this nice piece of software

Thank you for giving it a try :+1:

**Comment by jaredmorgs** [comment]
I think the problem at the moment is that the "Check Console for
Information" message is applicable for a number of HubPress failures. It
would be better to add better granularity to the error messages so HubPress
can better detect the root cause of the issue given the specific set of
circumstances.
