### ISSUE TITLE
404, images, syntax highlight, themes, asciiDoc tuto?

### ISSUE THREAD

**Issue by benavern** [HubPress/hubpress.io#191]
Salut, 

_D'abord merci pour hubpress, c'est vraiment simple à mettre en place, et très intuitif à utiliser. j'aime :)
J'ai tout de même quelques questions:_
- Y aurait-il un moyen de créer une page 404 personnalisée sur hubpress ou est-ce obligatoire de passer par celle de github?
- Est-il prévu d'ajouter un utilitaire pour uploader des images et les intégrer facilement?
- est-il possible de choisir le theme du syntax highliter car par défaut il est sur fond blanc et j'aimerais l'avoir avec un theme plus monokai
- Est-il prévu d'intégrer plus de thèmes?
- (Enhancement) Serait-il possible d'intégrer un lien ou une boite pour avoir une aide rapide pour écrire en asciidoc ? par exemple http://powerman.name/doc/asciidoc cette liste est pas mal foutue.

Merci d'avance et bon courage. :)

**Comment by jaredmorgs** [comment]
Je vais vous laisser prendre celui @anthonny, et proche si vous vous sentez la question est trop vieux maintenant.

**Comment by jaredmorgs** [comment]
Closing due to age. Please reopen if still an issue.
