### ISSUE TITLE
CNAME issue

### ISSUE THREAD

**Issue by benavern** [HubPress/hubpress.io#192]
Hi,
today I tried to add my own domain name on my hubpress blog. (master branch)

I created a "blog" subdomain on "caradeuc.info" witch is my domain name. (bought it on hostinger) 
I suppressed the "A Name" and added a "CNAME" pointing on "benavern.github.io"
in the meantime I added "http://blog.caradeuc.info" in the CNAME file.

at the begining I was just redirected on the empty folder of hostinger and now this is a 404! :(

What did I do wrong ?

**Comment by anthonny** [comment]
Hi @benavern, 

Your configuration seems to be good, i think that the changes made on hostinger are not effective.
I use gandi and sometime it can take 24h.

**Comment by benavern** [comment]
Ok, tank you, I'll and see :-)

**Comment by benavern** [comment]
still nothing ... 
http://blog.caradeuc.info/
![capture](https://cloud.githubusercontent.com/assets/5999900/7256121/b8553578-e84d-11e4-85c6-70594b810f05.PNG)
do I have to put "blog" in A(HOST) settings ?

**Comment by felixinx** [comment]
Do you have read the [Github support for CNAME](https://help.github.com/articles/adding-a-cname-file-to-your-repository/)? What @anthonny was talking is about the [`CNAME` file](https://github.com/benavern/benavern.github.io/blob/master/CNAME). Try to go with the [A Host setting](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/). Github help is very helpful! :smile:

**Comment by anthonny** [comment]
It works now :)

**Comment by benavern** [comment]
No, i putted back the github cname on benavern.github.io and just made a redirection on blog.caradeuc.info
I don't like to wait and after 48h I said myself "why did I choose hostinger" ?!! I did want a more professional mail address and I can't use their smtp on Gmail - _-'

**Comment by jaredmorgs** [comment]
I believe this was an issue with a hosting provider. Closing out.
