### ISSUE TITLE
Generic export / import?

### ISSUE THREAD

**Issue by danmbox** [HubPress/hubpress.io#195]
Other than setting up a git repo with appropriate data, are there any easy ways to import / export an entire hubpress? This would aid with migrations.

**Comment by jaredmorgs** [comment]
Just doing a bit of issue maintenance (as you can see, it's well overdue on this repo 😞).

There is no one click solution, apart from downloading the zip file of the repo from GitHub. There are no plans to make a dedicated export feature.
