### ISSUE TITLE
Removal of share buttons 

### ISSUE THREAD

**Issue by gjd3** [HubPress/hubpress.io#196]
I'd like to remove the share buttons (Facebook,twitter, etc) but don't know in which section of the repo the relevant bits of js are. If someone could point me in the right direction that would be very helpful. I don't need or want to get rid of the social media/contact options from the hubpress webapp but rather the share buttons from my own personal blog.

**Comment by adityadalal924** [comment]
You would need to edit the Handlebars template of your theme to delete the "Share" templating code from the post.

For example, in **Casper**, that code would be in [post.hbs](https://github.com/HubPress/hubpress.io/blob/master/themes/Casper/post.hbs#L58)

```html
<section class="share">
    <h4>Share this post</h4>
    <a class="icon-twitter" href="https://twitter.com/share?text={{encode title}}&amp;url={{url absolute="true"}}"
        onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
        <span class="hidden">Twitter</span>
    </a>
    <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{url absolute="true"}}"
        onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
        <span class="hidden">Facebook</span>
    </a>
    <a class="icon-google-plus" href="https://plus.google.com/share?url={{url absolute="true"}}"
       onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
        <span class="hidden">Google+</span>
    </a>
</section>
```

Similarly, in **Roon**, it is [here](https://github.com/HubPress/hubpress.io/blob/master/themes/Roon/post.hbs#L24)

```html
<menu>
    <a href="" id="btn_share" class="btn" title="Share">
        <span aria-hidden="true" data-icon="S"></span>
        <strong>Share</strong>
    </a>
    <a href="http://twitter.com/share?text={{encode title}}&url={{url absolute="true"}}" onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;" id="btn_comment" class="btn" target="_blank">
        <span aria-hidden="true" data-icon="C"></span> Comment on Twitter
    </a>
</menu>
```

Hope this helps!

**Comment by jaredmorgs** [comment]
Just doing a bit of issue maintenance (as you can see, it's well overdue on this repo 😞).

I'll close of the issue due to its age.
