### ISSUE TITLE
Multi-factor auth doesn't work anymore

### ISSUE THREAD

**Issue by scottdarch** [HubPress/hubpress.io#197]
I can no longer log in to my admin/authoring console. I use two factor auth and when I enter in all my credentials I get a "welcome back" message but I don't actually get access. I'm just forever stuck on the login page without any error messages.

**Comment by anthonny** [comment]
Hi @scottdarch!

You must upgrade your instance of hubpress with the version 0.3.0. 
The Github authorization has changed and the 0.2.0 can't work anymore

You can find a blog post here https://blog.hubpress.io

**Comment by scottdarch** [comment]
Doh! Right you are. I hadn't merged the 0.3.0 change properly.
