### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by robsd** [HubPress/hubpress.io#200]
I used to be able to login through http://robsdixon.github.io/blog/hubpress or http://robdblog.ml/hubpress but when I enter my credentials, it comes up with a green box saying:
Authentication
Welcome back Robert S Dixon
But stays on the login page and when I refresh the page, it clears my inputted credentials and asks me to login again :-(
Arrrggg! This is so annoying! I would hate to have to reset the blog because I have made posts.
Pleeeeaaaaassseee help me thanks

**Comment by anthonny** [comment]
Hi @robsdixon!

You must upgrade your instance of hubpress with the version 0.3.0. 
The Github authorization has changed and the 0.2.0 can't work anymore

You can find a blog post here https://blog.hubpress.io

**Comment by robsdixon** [comment]
Thanks, soz about slow reply, I've been away

**Comment by simevidas** [comment]
@anthonny This Firefox warning message when trying to access the blog is expected?

![capture](https://cloud.githubusercontent.com/assets/716405/7552189/df259280-f6a6-11e4-85fb-51e06e4bb5ea.PNG)

**Comment by adityadalal924** [comment]
That error is because `blog.hubpress.io` is actually hosted at GitHub Pages (`http://hubpress.github.io/blog.hubpress.io/`).

http://blog.hubpress.io should be fine.
