### ISSUE TITLE
Can NOT post blog

### ISSUE THREAD

**Issue by Red54** [HubPress/hubpress.io#202]
When posting a blog, there is a problem:

Request URL: https://api.github.com/repos/red54/hubpress.io/git/trees?1430435974884

Request method: POST

Status code: 422 Unprocessable Entity

Response JSON content:

message: "tree.path contains a malformed path component"

documentation_url: "https://developer.github.com/v3/git/trees/#create-a-tree"

**Comment by jaredmorgs** [comment]
Have you rebased your HubPress instance to the latest upstream. A GitHub
authentication change requires all HubPress Users to update.

**Comment by Red54** [comment]
I JUST forked it yesterday!!

**Comment by anthonny** [comment]
Hi @Red54!

Sorry to have been so long to give you an answer.
This error occurs when you use the branch gh-pages and you have not set this branch as default in the settings of your repository.

I saw that you have deleted your fork and i understand, i would have made the same thing.
If you want to try HubPress again, i will do my best to be more reactive.

I close the issue, feel free to reopen if necessary.
