### ISSUE TITLE
Add a button or toast to the editing page for jumping to position that you were at last time

### ISSUE THREAD

**Issue by lametaweb** [HubPress/hubpress.io#205]
Hi, 
my proposal consists of including a button or a floating toast for jumping to the post position that you were at last time you edited or simply watched at it (cursor position). I think it would be very useful because you usually check your posts contents one or two times before publishing it, and you cannot always complete the revision in only one web session.

Cheers.

**Comment by jaredmorgs** [comment]
@lametaweb Still a valid issue for you, or should we close it out?
