### ISSUE TITLE
Bad Credential on admin connect 

### ISSUE THREAD

**Issue by flug** [HubPress/hubpress.io#209]
Hi, 
I test your pages generator and when I try to connect I have a message that tell me I can not log in.
I realized that I had in the console reference: 
/Users/anthonny/00-Development/hubpress.io/src/hubpress/scripts/services/AuthServices.js
I'm not sure that it is normal?

**Comment by anthonny** [comment]
Hi @flug and thank you,

I think i have some issues with the sourcemap file, you are right :+1:, it's not normal but it's not a real problem.

It seems you want to use **flug.github.io**, you must use the branch master instead of the gh-pages.
