### ISSUE TITLE
Can't log in -- was out of touch in Beijing for a month

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.io#212]
Hi there.  I have two Hubpress blogs but cannot log in to either of them.  I just read the post about the April 20 deadline.  Unfortunately, I just got back from a month-long gig in Beijing during which time gmail, hubpress, etc. were inaccessible to me.  What can I do now to restore functionality?  The blogs are home.noteshareblog.io and concentric engineering.github.io/blog.

Note:  when I put in my credentials, I am told that am authenticated, but then nothing  further happens -- i am stuck at the login page.

**Comment by ialex** [comment]
Go to https://github.com/settings/tokens Delete tokens related to hubpress then try to login again it should work.

**Comment by jxxcarlson** [comment]
That did it.  Thank you!

**Comment by jxxcarlson** [comment]
I spoke too soon. If I create another post and try to save it, I get an error; 

```
Remote save
Your post was not saved. See your browser's developer console for the cause of the error.
```

**Comment by jaredmorgs** [comment]
Just checking that you rebased to the latest HubPress in /master. This has
the new GitHub authentication code baked in.

**Comment by jxxcarlson** [comment]
I did do that earlier today and before I contacted you — on the home.noteshareblog.io
blog, in any case.  The repo for that is 

jxxcarlson <https://github.com/jxxcarlson>/jxxcarlson.github.io <https://github.com/jxxcarlson/jxxcarlson.github.io>


Here is my config.son file.For some reason it now appears as a single line:

{"meta":{"username":"jxxcarlson","repositoryName":"jxxcarlson.github.io","branch":"master","cname":"home.noteshareblog.io","delay":"200"},"site":{"title":"Noteshareblog.io","description":"A blog about the publishing app noteshare.io","logo":"icon.png","postsPerPage":"6","googleAnalytics":"UA-61465165-1","disqus":"noteshareblog","url":"http://home.noteshareblog.io"},"socialnetwork":{"email":"jxxcarlson@mac.com","github":"jxxcarlson.github.io"},"theme":{"name":"Roon","url":"//home.noteshareblog.io/themes/Roon"}}

**Comment by jxxcarlson** [comment]
I watched the video, followed instructions, then made a pull request, and merged.
Jim

http://noteshare.io <http://noteshare.io/>
http://home.noteshareblog.io <http://home.noteshareblog.io/>

**Comment by anthonny** [comment]
Hi @jxxcarlson,

Your repository seems to be good.
Could you show me the content you try to save ?

FYI, there is a limit with the actual token management, you can't work on more than 1 blog at the same time.

Could you follow the following tests : 
1. Logout from HubPress
2. Remove tokens with a name containing HubPress
3. Login in HubPress
4. Check your token, you'll see something like this (here is for Chrome on OSX) : hubpress-Chrome-OS-X-10103
5. Try to save an existing post

If you don't have any error message, all is good.

**Comment by booleanbalaji** [comment]
No, actually, this was an issue for me too. You just need to update your fork of Hubpress. You can find the directions in the main repo.

What was happening was that I entered the username and password, and it would successfully authenticate, but wont move beyond the login page

**Comment by jxxcarlson** [comment]
All OK now -- thanks!
