### ISSUE TITLE
NOTE: -- work in preview, not in final output.

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.io#219]
In the example below, from http://home.noteshareblog.io/2015/05/21/Writing-Chemistry-in-Noteshare.html,
the admonition is properly rendered in preview, but not on the blog site itself.

```
NOTE: Asciidoc-LaTeX documents can be converted into LaTeX documents 
by the command `$ asciidoctor-latex foo.adoc`.  This is a still-experimental
feature, but it is advancing rapidly and has been used to successfully
convert many documents on http://www.noteshare.io.
```

**Comment by jaredmorgs** [comment]
Hi James

What theme are you using there?

I think I'm getting admonitions on the theme I'm using on
http://jaredmorgs.github.com so that could suggest there is an issue with
the admonition icons in the theme you're using.

@anthonny will need to fix this up for you. There is certainly nothing
wrong with your Asciidoc markup.

**Comment by abhayghatpande** [comment]
Hi Anthonny,

Admonitions are not being displayed yet in any theme. Do you think this is something that will be fixed soon? I'm not able to use other icons using the `:icons: font` tag either.

**Comment by tkralphs** [comment]
I just wanted to add that this is not working for me either and I was wondering if this is going to be addressed.

**Comment by jaredmorgs** [comment]
@jxxcarlson @abhayghatpande @tkralphs Sorry for the late follow-up with this issue. Can any of you confirm this is still happening on the 0.6.x released themes? If I don't get a response in a week I'll assume the issue no longer occurs and close off the issue. I'm trying to reduce the noise for @anthonny a bit. Thanks for your help with this.
