### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by msluyter** [HubPress/hubpress.io#22]
It doesn't appear that syntax highlighting appears to be supported, at least according to the asciidoc documentation. 

For example:

http://msluyter.github.io/blog/2015/02/09/foo.html

compared to:

http://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks

Is this something that you've managed to get working?

**Comment by anthonny** [comment]
Hi @msluyter !

Syntax highlighting is not supported yet. Sure it will. 
I think the fix is simple, just add https://highlightjs.org/ in each theme.

I'll make a try.

**Comment by sscarduzio** [comment]
+1

**Comment by jaredmorgs** [comment]
+1

**Comment by anthonny** [comment]
same as #94
