### ISSUE TITLE
[blue]# ... # Not working on blog site. OK in editor on computer.

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.io#220]
The following text, taken from http://home.noteshareblog.io/2015/05/18/You-Own-It-Part-II.html, 
is buggy: the blue color is properly rendered in Preview but not at all on the blog site.

```
Click on "[blue]#this link#" 
and the download will begin after a brief delay.
```

**Comment by raisedadead** [comment]
Hi @jxxcarlson,

I guess this is the same as #193 

thanks,
raisedadead

**Comment by jaredmorgs** [comment]
Based on #193 I'm closing this issue out as well.
