### ISSUE TITLE
Can't log in with ver. 0.3.0

### ISSUE THREAD

**Issue by jnorthr** [HubPress/hubpress.io#226]
have forked hubpress to my own repo, changed config.json, confirmed this is hubpress 0.3.0 and uploaded to my https://github.com/jnorthr/hubpress.io account. 

Now have 'log on' panel at http://jnorthr.github.io/hubpress/#/login 

![screenshot 2015-05-29 18 45 06](https://cloud.githubusercontent.com/assets/382990/7888512/836d29f6-0639-11e5-9c9c-bd05bbaab337.png)
![screenshot 2015-05-29 19 22 13](https://cloud.githubusercontent.com/assets/382990/7888513/8386ef12-0639-11e5-928b-8c2b09211d36.png)
![screenshot 2015-05-29 19 23 24](https://cloud.githubusercontent.com/assets/382990/7888514/8394ea5e-0639-11e5-8694-0573bc772211.png)

as shown in hubpress demo, but no combination of user name or email plus password gets me thru. Only box top-right says 'consult console for more informations' but where is that console ? and should i be using my github credentials to log on or some thing else ?

**Comment by jnorthr** [comment]
update of javascript console screen prints when logging in from firefox / chrome /opera browsers

**Comment by anthonny** [comment]
Hi @jnorthr,

In your repository, on each branch, you did not change the `config.json` file.

**Comment by jnorthr** [comment]
merci for that idea -

does this mean my config.json values must be identical for each branch in
jnorthr/hubpress.io <https://github.com/jnorthr/hubpress.io>/hubpress
<https://github.com/jnorthr/hubpress.io/tree/master/hubpress>/config.json*
?*

*thx*

**Comment by jnorthr** [comment]
since here is only one branch on my hubpress.io git repo have changed config.json to same as all other places it is held. Tried to log in with a safari 5.1.10 browser i've not used before for this task. Which fails to load due to line 51 in app.js looking for 'map' variable, so maybe this is something else ? pls see this:
![screenshot 2015-05-29 22 26 10](https://cloud.githubusercontent.com/assets/382990/7892155/c3875e1c-0652-11e5-9aa6-43ea564c7dd2.png)

**Comment by jnorthr** [comment]
my google chrome browser still fails with this 404 page fault even after all fixes as suggested 

![screenshot 2015-05-29 22 37 11](https://cloud.githubusercontent.com/assets/382990/7892254/5a74ef56-0653-11e5-8519-0b38031aebfa.png)

**Comment by anthonny** [comment]
if you do not use the `jnothr.github.io` name for your repository, you can't use the branch `master`

* In the configuration f your repository, you must set the branch `gh-pages` as **default**.
* On the branch `gh-pages`, you must update the file `config.json` with your `username` and the `repositoryName` (here hubpress.io)
* You can access to HubPress via the URL http://jnorthr.github.io/hubpress.io/hubpress

**Comment by jnorthr** [comment]
thank you for your patience :-)  

at the moment i have a master and a gh-pages branch in https://github.com/jnorthr/jnorthr.github.com/tree/master and https://github.com/jnorthr/jnorthr.github.com/tree/gh-pages

Both are exact copies of hubpress.io 0.3.0  and because i don't really know what i am doing i also have a repo at https://github.com/jnorthr/hubpress.io with hubpress.io 0.3.0 and 3 branches: master, development and gh-pages. 

Please advise WHICH repo needs to have the gh-pages set as the default ?  Then i will try to learn how to adjust github to make that happen. Also which config.json in which branch of which repo needs to have the correct values ?

Right now i have http://jnorthr.github.io/ working and am guessing that it is coming from the master branch of https://github.com/jnorthr/jnorthr.github.com/tree/master. I am also guessing that when i have hubpress.io working then any new posts i make thru hubpress.io will come back into https://github.com/jnorthr/jnorthr.github.com/tree/master (or gh-pages?)

So can we say that hubpress.io is really like a publishing tool that lets users write new posts in a given repo within github ?  peut-être i have lost the plot  ;-D

**Comment by jnorthr** [comment]
am using this link to learn http://octopress.org/docs/deploying/github/  what is possible - hopefully

**Comment by jnorthr** [comment]
Ok, have confirmed all branches of both repos have identical credentials and point to https://github.com/jnorthr/hubpress.io

also made gh-pages as default on both repos.

Next: when attempting a log on, there is a module failure at app.js line 51 that says missing variable : Map

**Comment by anthonny** [comment]
The repositoryName in your config.json is not good. You must put the repository name only (in your case **hubpress.io**), not the url

**Comment by jnorthr** [comment]
ok merci for that. Have made that change to :

{   "meta": {"username": "jnorthr","repositoryName": "hubpress.io",branch":
"gh-pages"},   "theme": {   "name": "Casper"   }
}

and http://jnorthr.github.io/hubpress/#/login now gets me to signin page.

Enter jnorthr+password gives 404 as shown in this screen shot. It is
looking for https://github.com/jnorthr/hubpress.io?143... but cannot find
it. But if i manually enter https://github.com/jnorthr/hubpress.io into
browser address bar, it correctly locates target. This makes me think it is
a token failure now. Is that possible ?

thx jim

**Comment by jnorthr** [comment]
WELL Houston - I think i have lift-off !!!  Did all the changes to my config.json repository name in four different branches :  master and gh-pages in both my jnorthr.github.com and my hubpress.io repo too. I still do not understand which of these repos is being used by hubpress. 

But anyway, i have started testing on yet another iMac PPC that i had not used before to access hubpress. So am thinking the cookies/connect tokens for my other browsers on other machines may have been stopping hubpress from working. Will let you know how it goes.

merci for your time
jim
