### ISSUE TITLE
published_date setting isn't working

### ISSUE THREAD

**Issue by naveensrinivasan** [HubPress/hubpress.io#23]
I have tried using the   
``:published_date: 2010-01-31 ``  

but the post still shows the current date as the published setting. What could be wrong?

Thanks

**Comment by anthonny** [comment]
Hi @naveensrinivasan , 

Thanks for reporting this issue.

There is a mistake in the doc, the good attribute is : 

```
:published_at: 2010-10-31
```

I'll update the README

**Comment by naveensrinivasan** [comment]
Thanks. I see the update.
