### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by mubix** [HubPress/hubpress.io#231]
Is this project dead? Haven't seen any updates to the code in months and a some pending pull requests that have been there a while. I love this project and would love to see it continue but I don't want to invest converting my entire set of blog posts unless there is some hope that a few of the still pending issues will be worked on.

**Comment by anthonny** [comment]
Hi @mubix,

I understand, Hubpress is not a dead project.
The fact is that actually i haven't a lot of time (2nd baby, new gig ...) and that's why i'm not really active atm.
I hope that you understand my position, i'll do my best to be back soon

**Comment by mubix** [comment]
@anthonny of course, need to get more developers into the fold ;-) Awesome project don't want it to go away ;-)

**Comment by anthonny** [comment]
I must say that this kind of issue is a really good source of motivation, thank you :+1:

**Comment by jelitox** [comment]
@anthonny <https://github.com/anthonny> congrats! for you baby, maybe if
you publish a roadmap with the  issues and milestone on it many of the
users can contribute hubpress it's a huge project well be nice contribute
for him ;)

2015-06-13 12:55 GMT-04:30 Anthonny Quérouil <notifications@github.com>:

> I must say that this kind of issue is a really good source of motivation,
> thank you [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/231#issuecomment-111734813>
> .
>



-- 
Javier Enrique León
0416- 2546908
GNU/Linux user  # 327958
Running Linux!

[Mi Blog... ]
http://blog.javierleon.com.ve/
[Linkedin... ]
https://ve.linkedin.com/in/jelitox/en
[Twitter... ]
https://twitter.com/jelitox
[Github... ]
https://github.com/jelitox

**Comment by jaredmorgs** [comment]
Just doing a bit of issue maintenance (as you can see, it's well overdue on this repo 😞).

We still need to do a roadmap, but will plan that out in a fresher ticket.

**Comment by malys** [comment]
3 years later. The same question. The project is it alive? Are there alternatives?

**Comment by jaredmorgs** [comment]
It's definitely not being actively maintained. Any changes to GitHub that
break the authentication will likely not be fixed by anyone.

I'm not aware of any 1:1 replacements that allow you to fork and run from
GitHub. If you want a WYSIWYG interface you might consider checking out
NetlifyCMS. It supports Asciidoc last time I looked

>

**Comment by anthonny** [comment]
Thank you @jaredmorgs,

Like @jaredmorgs said, the projet is not maintained anymore. I will update the README

**Comment by malys** [comment]
@anthonny You could change the project's status to ARCHIVE.

**Comment by jaredmorgs** [comment]
I agree with this approach. Good suggestion!

>
