### ISSUE TITLE
Saga theme: bad image rendering

### ISSUE THREAD

**Issue by adericbourg** [HubPress/hubpress.io#232]
Using *Saga* theme, image CSS directives are:

    img, q {
        max-width: 110%;
        width: 110%;
        /** other stuff */
     }

    img {
        width: calc(100% + 40px);
        /** other stuff */
    }

It makes images in the articles very big. It can be pleasant for pictures for instance but it is annoying for diagrams for instance. 

Eg: 

> ![diagram](https://cloud.githubusercontent.com/assets/615743/8183475/aeb48ad4-1438-11e5-9cea-dba2b597851d.png)

**Comment by lametaweb** [comment]
Hi @adericbourg 
You could use image dimensions attributes, i.e:
`image::https://raw.githubusercontent.com/lametaweb/lametaweb.github.io/master/images/003/post003-fig068.png[100,100]`
I hope it helps.

**Comment by anthonny** [comment]
Hi @adericbourg 
Does the solution of @lametaweb work for you?
