### ISSUE TITLE
Adding Disqus

### ISSUE THREAD

**Issue by dgrizzla** [HubPress/hubpress.io#235]
I'm new into Hubpress, and I was trying to add Disqus into my blog, I already made a Disqus shortname and put it in the settings page (but I'm not quite sure if it is right)

![disqus](https://cloud.githubusercontent.com/assets/6843339/8509301/8c5176a8-2259-11e5-9fce-368b73c8dfa4.PNG)

And all I am getting is this

![comments](https://cloud.githubusercontent.com/assets/6843339/8509307/ace4f98a-2259-11e5-9f98-bb99984be455.PNG)

Thanks for your help in advance.

**Comment by anthonny** [comment]
You must use your shortname, i think for it's **dgrizzla**.

Could you try with this value ?

**Comment by dgrizzla** [comment]
@anthonny Yeah it worked, I didn't knew it was just the shortname, I was adding the whole url. Thanks!

**Comment by anthonny** [comment]
You're welcome :) Have fun with HubPress :D
