### ISSUE TITLE
Could not load,why? 

### ISSUE THREAD

**Issue by chenjundong** [HubPress/hubpress.io#237]
Could not load,why? The configuration errors？
I need a solution,THX
![image](http://i3.tietuku.com/343c9ca38f542c43.png)

**Comment by anthonny** [comment]
Hi @chenjundong,

In the file https://github.com/MarkCoder/hubpress.io/blob/gh-pages/hubpress/config.json

You must set the branch to **gh-pages**

**Comment by kevinlanning** [comment]
I have the same error. Tried setting up blog using both "Use the github.io domain" and "Use a Custom Domain .." instructions.  Error happens in both Chrome and IE under Windows 8.1

Branch is already set to gh-pages...thanks.

https://github.com/kevinlanning/WritingIsTheHardestPart/blob/gh-pages/hubpress/config.json

**Comment by anthonny** [comment]
Hi @kevinlanning!

Could you try with this : 

```json
{
  "meta": {
    "username": "kevinlanning",
    "repositoryName": "WritingIsTheHardestPart",
    "branch": "gh-pages"
  },
  "theme": {
    "name": "Casper"
  }
}
```

It should work

**Comment by kevinlanning** [comment]
On Mon, Jul 6, 2015 at 11:11 AM, Anthonny Quérouil <notifications@github.com
> wrote:

> {
>   "meta": {
>     "username": "kevinlanning",
>     "repositoryName": "WritingIsTheHardestPart",
>     "branch": "gh-pages"
>   },
>   "theme": {
>     "name": "Casper"
>   }
> }
>
>
​and it does! thanks for the quick fix...​


----------------------------------
Kevin Lanning
Professor, Wilkes Honors College
Florida Atlantic University
voice: (561)799-8652  | fax: (561)799-8412

**Comment by chenjundong** [comment]
@anthonny Thank you very much，Can I change the node of Google font, in China can't use Google font

**Comment by anthonny** [comment]
@chenjundong yes you can change fonts, but i could but a problem when you will update your copy of hubpress from the upstream
