### ISSUE TITLE
post not showing up

### ISSUE THREAD

**Issue by hhimanshu** [HubPress/hubpress.io#242]
I added a new post and got confirmation from hubpress that it is published  

<img width="1280" alt="screen shot 2015-07-10 at 7 23 51 am" src="https://cloud.githubusercontent.com/assets/6589036/8620481/a8deb27a-26d4-11e5-9604-635547274d97.png">

However when I go to my [blog](https://hhimanshu.github.io/), I do not see my post there

Does it takes time to federate?

I also see my [post](https://github.com/hhimanshu/hhimanshu.github.io/tree/master/2015/07/10) in my github repository

Thanks

**Comment by anthonny** [comment]
Hi @hhimanshu1

The index.html is good https://github.com/hhimanshu/hhimanshu.github.io/blob/master/index.html#L50

I suppose that it's a cache problem, could you try to save your post again to force the invalidation of the cache ?

**Comment by hhimanshu** [comment]
@anthonny , I tried saving multiple times, do I need to provide publish date? I assume its not mandatory

**Comment by hhimanshu** [comment]
I updated the blog, the post is available in repository https://github.com/hhimanshu/hhimanshu.github.io/blob/master/_posts/2015-07-10-Partially-Applied-Functions-in-Scala.adoc but not showing up at all

GitHub [status](https://status.github.com/messages) is good as well

**Comment by hhimanshu** [comment]
showed up, https://hhimanshu.github.io/2015/07/10/Partially-Applied-Functions-in-Scala.html, closing issue, Thanks @anthonny
