### ISSUE TITLE
Next milestone

### ISSUE THREAD

**Issue by ziyaddin** [HubPress/hubpress.io#243]
Hi All, the issue tracker is great for developing project of course, but what if you put the milestones for this project: what problems developers need to solve in the next milestones? It will ease the development process I think.

**Comment by anthonny** [comment]
:+1: I agree with you.

HubPress is not ready for dev contribution. I'm fixing the build in // on the refactoring of the admin IHM.
After that, it will be easier to contribute and work with milestones

**Comment by jaredmorgs** [comment]
Just doing a bit of issue maintenance (as you can see, it's well overdue on this repo 😞).

Milestones would be great. We really need to work out the future of HubPress long term.
