### ISSUE TITLE
Contribution README for PR's

### ISSUE THREAD

**Issue by ziyaddin** [HubPress/hubpress.io#247]
Hi All,

Hubpress really needs a Contribution README to make it clear how to send PR's for development. I am really confused with sending PR's right now. I don't know which branch I need to use for PR.

Dear, @jaredmorgs @anthonny take a look at it, please.

Thanks!

**Comment by anthonny** [comment]
Hi @ziyaddin,

That's true, i must write this HOW-TO. FYI, every PR must be done on the development branch.
I'm refactoring the admin IHM, after that, i'll write a "Contributing" doc.

**Comment by ziyaddin** [comment]
@anthonny great! :+1:

**Comment by raisedadead** [comment]
:+1:

**Comment by jaredmorgs** [comment]
https://hubpress.gitbooks.io/hubpress-knowledgebase/content/develop/contribute_pr.html covers this now
