### ISSUE TITLE
Using HubPress as part of a GitHub Organization

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#249]
Because I use HubPress for my personal blog, I was unable to fork another copy of the repo to create a completely separate instance (with a separate gh-pages branch).

I've created https://github.com/BlahCade and forked Hubpress to https://github.com/BlahCade/podcast

What I'm unsure about is what to put in the config.json for the user. 

Looking at the blog.hubpress.io repo, it uses the organization name "hubpress" as the username, with the repo name "blog.hubpress.io" on the "gh-pages" branch (which may have something to do with how you have the primary site configured @anthonny ).

```
"meta":{"username":"hubpress","repositoryName":"blog.hubpress.io","branch":"gh-pages","cname":"blog.hubpress.io","delay":"500"}
```
So I've mirrored this config in the BlahCade gh-pages setup, but I'm not having any luck. I tried setting it to podcasts.blahcade.io but got no placeholder. So I changed it to just `podcasts` to see if that would work better. But it doesn't seem to be.

Am I missing something obvious here, or is there another setting or config combination I need to set up. If so, I'll add the specific details to the README.

**Comment by jaredmorgs** [comment]
http://blahcade.github.io/podcasts/ is now live. So I'm not sure what was going on here.

**Comment by anthonny** [comment]
Hi @jaredmorgs,

If you want to use `podcasts.blahcade.io`, you must buy the domain name `blahcade.io` and configure a CNAME for the domain `podcasts.blahcade.io`.

That's what i have done for `blog.hubpress.io`
