### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by wcp1231** [HubPress/hubpress.io#25]
Will hubpress.io support markdown ?

**Comment by anthonny** [comment]
Hi @wcp1231,

You are not the first to ask this question :smile: 
HubPress is powered by Asciidoctor (@mojavelinux) which provide a compatibility to Markdown http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility-asciidoctor-only

Could it be enough for you ?

**Comment by wcp1231** [comment]
Oh ! Please forgive my carelessness. I love hubpress very much ~ Thx ~ :smile:

**Comment by anthonny** [comment]
No problem :smile:, have fun with HubPress !
