### ISSUE TITLE
Cannot save post or publish post

### ISSUE THREAD

**Issue by liyucun** [HubPress/hubpress.io#250]
Hi everyone,

I just followed the instruction "Use a Custom Domain or GitHub Page Domain Already In Use" to set my own page, because my own github.io have been using for another project. I think it is authentication problem, but have no idea how to figure it out.

When I click save, the error shows below:

![image](https://cloud.githubusercontent.com/assets/4750970/8760530/518acf5a-2cf0-11e5-9d78-a5d6280ea1ac.png)

![image](https://cloud.githubusercontent.com/assets/4750970/8760532/67e6b4e4-2cf0-11e5-95a7-682e127acc86.png)

Please let me know if there any other detail would you like to know.

Thanks

**Comment by anthonny** [comment]
Hi @liyucun,

Could you show me the content that you try to save ?

**Comment by liyucun** [comment]
Hi @anthonny ,

After many tries, I finally find the problem is because I am using Chinese character as my tag. If I am using Chinese character in my tag, it will raise the problem--failure to post. Below is some Chinese words, you can pick up to reproduce the problem.

搞笑，贪玩， 逗乐
