### ISSUE TITLE
Dynamic hp-* attributes or meta attribute

### ISSUE THREAD

**Issue by mgreau** [HubPress/hubpress.io#252]
Hi,

I have finally upgraded my blog at http://mgreau.com/blog to HubPress :) 
I use a theme named ghostium http://ghostium.oswaldoacauan.com/

I started to customize this theme and I wanted to add some new stuffs for my posts like time-reading or language.
First I was thinking about the possibility to be able to have every custom `hp-*` attributes available in the post template, like:
```
* hp-language available as {{language}}
* hp-time-reading available as {{time-reading}}
* hp-my-custom-attribute available as {{my-custom-attribute}}
```
But after a discussion with @anthonny , there could be a problem with the fact that each post object could have a lot of attributes.

So the second option would be to have a sort of meta attribute like `hp-meta` which gives the possibility to define several attributes on one line like for example:

``` text
hp-meta: language=EN, time-reading=20mn, my-custom-attribute=someValue....
```

WDYT?

**Comment by jnorthr** [comment]
I am having a similar problem in the CloudFoundry platform. It serves me a large Json structurei need to consume and make into a map. But some attributes have the same name so i get name-space collision on duplicate keys. So how to resolve that? Like you, am also thinking some metadata when storing the key into my map. But waiting for inspiration 😉

**Comment by jaredmorgs** [comment]
What are your thoughts @anthonny ? Wontfix, or leave it open as an enhancement?
