### ISSUE TITLE
Improve visibility of the documentation for developers

### ISSUE THREAD

**Issue by mgreau** [HubPress/hubpress.io#253]
Hi,

I think that it could be interesting to enhance the visibility of the documentation for developers (http://doc.hubpress.io/) with for example:
* add a link on the official website
* add a link in the README.adoc of hupress.io
* explain the Stack used to develop (Frameworks...)

It could encourage some developers to develop some features or send PR to the project.

**Comment by jaredmorgs** [comment]
I think the contribution side of things from the developer perspective is
just something that Anthonny hasn't had a chance to flesh out yet.

The API docs you see there were just a treat of a docs chain used to
produce API docs. The docs are nowhere near fleshed out.

On Thu, 23 Jul 2015 at 08:36 Maxime Gréau <notifications@github.com> wrote:

> Hi,
>
> I think that it could be interesting to enhance the visibility of the
> documentation for developers (http://doc.hubpress.io/) with for example:
>
>    - add a link on the official website
>    - add a link in the README.adoc of hupress.io
>    - explain the Stack used to develop (Frameworks...)
>
> It could encourage some developers to develop some features or send PR to
> the project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/253>.
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
https://hubpress.gitbooks.io/hubpress-knowledgebase/content/develop/contribute_pr.html covers how to contribute. No further developer docs are planned at this stage.
