### ISSUE TITLE
other personal/professional/academic/etc website field(s)

### ISSUE THREAD

**Issue by ian-bertolacci** [HubPress/hubpress.io#254]
Would it be possible for HubPress (and themes) to include fields for other websites?
I imagine that I could edit the configs/scripts/css by hand, but that seems to defeat the purpose of the nearly seamless HubPress.

Academics such as myself keep a website listing their work that does not fit the blog stylings of my github.io site.
It would be nice if, along with the links to twitter, github, linked-in, email, I could place links to one or more external sites. 

This way I can place the github.io link on everything, and the github.io site links to everything, so my tangle of social media/profiles/networks is slightly more navigable. 

Further, it could be useful to link to full product/business pages from the developers blog.

**Comment by Cribstone** [comment]
I emphatically second this request!  I've been using Hubpress to host my blog but now I need something that can act as a landing page with links to an "About Me" along with links to my blog, social media etc... I tried using the Uno theme with Ghost before moving to Hubpress and I found it only gets me halfway there.  After spending almost two full days fruitlessly trying to edit Jekyll themes to get what I want, I wound up back at Hubpress and the UNO theme again...  I guess halfway there is better than nothing but it still doesnt do what I want.

**Comment by jaredmorgs** [comment]
Doing some backlog grooming for HubPress and came across this issue. 

HubPress is designed to get you up and running quickly with a blog site. Where you take it from there is up to you. There are no plans to add extra fields into the Settings page at this stage. 

A workaround is to create an About Me blog post and future date it using the :published_at: attributed so it is "sticky" at the top of your blog.
