### ISSUE TITLE
Multiple desktops: synchronization issue in Admin Console 

### ISSUE THREAD

**Issue by Ardemius** [HubPress/hubpress.io#256]
Hi,

I encountered a *synchronization issue in the Admin Console when using several desktops*, all on Chrome.
Indeed, in the underlying IndexedDB, the `posts` object store is not updated when logging in, contrary to what is explained in [issue 76](https://github.com/HubPress/hubpress.io/issues/76).

When facing this issue, an easy workaround is to clear the IndexedDB object store using the Chrome Developer Tools.
Once done, you just have to relog in to successfully force the synchronization.

**Comment by jaredmorgs** [comment]
This issue is fixed by the Synchronise button. https://hubpress.gitbooks.io/hubpress-knowledgebase/content/buttons/about_synchronise_blog_posts_button.html
