### ISSUE TITLE
Saving / publishing issue when using some AsciiDoctor backend attributes in header

### ISSUE THREAD

**Issue by Ardemius** [HubPress/hubpress.io#257]
Hi,

I encountered a bug, in Admin Console, when **saving a post in which I added some *Deck.js* backend attributes in the header**.
This last was:
```
= How Git saved our project? (or nearly...)
some author info
:published_at: 2015-04-30
:hp-tags: some tags
:imagesdir: ./images
:backend: deckjs
...
```

This resulted in:
```
Your post was not published. See your browser's developer console for the cause of the error.
```

In Chrome Developer Tools, the following error was present:
```
Uncaught RuntimeError: asciidoctor: FAILED: missing converter for backend 'deckjs'. Processing aborted.
```

Could you catch the error, so as to bypass unsupported backends? (not only Deck.js)

I know that those attributes have no use in Hubpress, but, for me, one of the main advantages of AsciiDoc(tor), is to use a single flat file for different uses (book, slides, blog, etc.).

Thanks :wink: 

Thomas

**Comment by jaredmorgs** [comment]
I've captured this issue in a FAQ entry. It's not perfect as a solution to your specific suggestion, but it will suffice as a stop-gap measure for other users encountering the same issue. 

Thanks for raising the RFE.

**Comment by jaredmorgs** [comment]
https://hubpress.gitbooks.io/hubpress-knowledgebase/content/develop/other_asciidoctor_backends.html
