### ISSUE TITLE
Any way to list all tags?

### ISSUE THREAD

**Issue by peer2peer** [HubPress/hubpress.io#262]
I wanna to have a navigation column for my blog  and one tag as one navigation item.
But I don't know how to get the list of all the tags used in all my posts.

Then any way? 

Thank you all.

**Comment by jaredmorgs** [comment]
Doing some backlog grooming and came across this issue. 

There is no way to do this with the supplied HubPress Ghost Themes, unless you customise a theme to your specific requirements.
