### ISSUE TITLE
Not support for all Chinese characters title

### ISSUE THREAD

**Issue by liyucun** [HubPress/hubpress.io#263]
I have created a post with all Chinese title, and the bug is post will not be able to generate a html name for this post. So, the name for this post is .html something, and the chrome browser will download it instead of opening it once user go to post page.

One solution is: at least contain some english characters in your title so that post can generate a non ".html" address post page.

**Comment by jabby** [comment]
It's a known bug. See https://github.com/HubPress/hubpress.io/issues/43

You can use an alternative title. You can follow the explanation in the readme file. https://github.com/HubPress/hubpress.io#hp-alt-title-to-specify-an-alternative-title

**Comment by liyucun** [comment]
Thanks Jabby
