### ISSUE TITLE
publishElements error TypeError: i is undefined

### ISSUE THREAD

**Issue by gitfvb** [HubPress/hubpress.io#272]
Hi, when saving and publishing my first post I get the following error message in the javascript console:

PostsServices - publishElements error TypeError: i is undefined
Stack-Trace:
["/Users/anthonny/00-Development/hubpress.io/src/hubpress/scripts/services/PostsServices.js"]</</w</<.publishPost.value/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/app.js?v=0.3.0:50:27084
e@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:34744
l@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35565
o@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35298
t/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:34487
v/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35805
e@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:34686
l@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35565
o@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35298
t/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:34487
v/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35805
e@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:34901
l@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35565
o@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35298
t/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:34487
v/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:35805
f/this._transPromiseFactory/</</<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:9043
at/<@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:29586
f/<._promise/</e</o.oncomplete@http://gitfvb.github.io/hubpress.io/hubpress/scripts/vendor.js?v=0.3.0:13:19077

**Comment by csiebler** [comment]
If you're not using your github.io domain to host HubPress, you need to set your default branch to gh-pages. Then it should work!

**Comment by jaredmorgs** [comment]
closing due to issue age.
