### ISSUE TITLE
Question: What's the best way to add multiple languages?

### ISSUE THREAD

**Issue by ArmandDu** [HubPress/hubpress.io#273]
Hi, I am using Hubpress and I was wondering what was the best way to have my blog in two languages?

**Comment by tiago-peixoto** [comment]
I have the same question.

**Comment by jaredmorgs** [comment]
At the moment, HubPress is English language only. There is no currently supported way of switching between languages for the user natively.

As users, if this feature was to be scoped and implemented, how would you want to control multi-language posts?
