### ISSUE TITLE
Error Occured on Publishing and saving

### ISSUE THREAD

**Issue by endrureza** [HubPress/hubpress.io#28]
when i want to post the first time, just after i wrote down everything and intended to save and publish at that time error occured.

saving error -> an error occures see your console [remote save]

publishing error -> an error occures see your console [publishing]

any idea why?

**Comment by phai** [comment]
because of this :
GET http://<username>.github.io/hubpress/scripts/Dexie.min.js.map 404 (Not Found)
GET http://<username>.github.io/__opal_source_maps__/opal.js.map 404 (Not Found)

**Comment by endrureza** [comment]
what ? then how am i gonna fix that one ?

**Comment by anthonny** [comment]
There is effectively a 404 for the map files @phai but @endrureza should be able to log in.

Can you show me the content that you try to save ? It is not in the documentation (my bad) but a post need a title, can you try to post this sample :

```
= Title

My content
```

**Comment by endrureza** [comment]
i've already done that. like i said, after i wrote an article and then want to save, suddenly the error is appeared

**Comment by anthonny** [comment]
Can you give me the right to push on your repo please ? i'lll make a test.

**Comment by endrureza** [comment]
ah never mind dude, it's already fixed by itself. Don't know why, but thank's for staying with me so far :+1:

**Comment by anthonny** [comment]
W00t ! You're welcome, have fun with HubPress :smile:
