### ISSUE TITLE
Improve post writing interface

### ISSUE THREAD

**Issue by isaacrg** [HubPress/hubpress.io#293]
Please could it be made clear that a title is needed to make a new post, as it just fails

**Comment by jabby** [comment]
Do you think that a more complete information should be provided in the readme ? https://github.com/HubPress/hubpress.io#blog-title-and-headings

**Comment by jaredmorgs** [comment]
https://github.com/HubPress/hubpress.io/blob/master/README.adoc#blog-title-and-headings
does provide this info.

On Tue, 3 Nov 2015, 23:21 Isaac Reid-Guest <notifications@github.com> wrote:

> Please could it be made clear that a title is needed to make a new post,
> as it just fails
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/293>.
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
I've completely restructured the README in the /development branch, but
@anthonny needs to do another release.

Check out that README and give me your feedback.

On Wed, 4 Nov 2015, 07:16 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

>
> https://github.com/HubPress/hubpress.io/blob/master/README.adoc#blog-title-and-headings
> does provide this info.
>
> On Tue, 3 Nov 2015, 23:21 Isaac Reid-Guest <notifications@github.com>
> wrote:
>
>> Please could it be made clear that a title is needed to make a new post,
>> as it just fails
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HubPress/hubpress.io/issues/293>.
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/titles_and_headings.html describes the implemented Save button disable feature.
