### ISSUE TITLE
Upgrade to Asciidoctor.js 1.5.3

### ISSUE THREAD

**Issue by Mogztter** [HubPress/hubpress.io#294]
Could you please test that everything is working fine with version 1.5.3-preview.2 ? If this is the case I will release a final version. 

Thanks :smile:

**Comment by mojavelinux** [comment]
Should we update the title to 1.5.4?

**Comment by Mogztter** [comment]
Yes, 1.5.4 will be out soon (hopefully). I need to test that the new build and release tasks produce the expected result. I think I will release a preview version, just to make sure that I didn't miss something.

**Comment by mojavelinux** [comment]
Preview sounds good, though perhaps just call it a release candidate?

**Comment by mojavelinux** [comment]
That's probably a conversation for the version thread, but my understanding is that "preview" means "early prototype", something that is only partially implemented. Another option here is "beta", though I think release candidate more accurately describes where we are.

**Comment by jaredmorgs** [comment]
@anthonny What version of asciidoctor.js are we consuming now?
