### ISSUE TITLE
Multi updates needed before the modification of the post to be accepted

### ISSUE THREAD

**Issue by javathought** [HubPress/hubpress.io#298]
I need to modify at least 2 times post until the post is really updated : the hubpress post editor show the old version after saving modification the first time.

**Comment by jaredmorgs** [comment]
@javathought does this behavior still happen for you? If not, would you mind closing out the bug?

**Comment by javathought** [comment]
I did not do post updates since your comment. Tried one today : it's ok and did not happen.
