### ISSUE TITLE
push of some posts freezes the admin page 

### ISSUE THREAD

**Issue by javathought** [HubPress/hubpress.io#299]
The hubpress/#/posts admin page freezes on pushed post asciidoc posts. 

I've a migration tool https://github.com/javathought/wordpress-exit (forked from https://github.com/binout/wordpress-exit). One of the enhancement I've made is to format source code blocks for hubpress with [source] tag.

I've noticed it's on posts with this tag that the pages freezes. It's should not as creating a post and copying/pasting the generated post does not freeze the admin page.

**Comment by jaredmorgs** [comment]
Does this behaviour still happen for you @javathought ? If it no longer happens with 0.6.x, please close the issue.

**Comment by javathought** [comment]
I've migrated and tested button many posts since : I did not reproduced.
