### ISSUE TITLE
Can't close the last toast message

### ISSUE THREAD

**Issue by jabby** [HubPress/hubpress.io#3]
In Hubpress.io administration, I can't close the last toast message. 

When I edit a blog post, the eye button to show the rendering of my blog post is hidden. It's a little bit annoying.

**Comment by anthonny** [comment]
I moved the toastr from top:12px to top:40px (6307007)
I not a final fix but now you can on the eye.

I must find why some messages don't disappear

**Comment by jaredmorgs** [comment]
I reported the same issue about toast messages, which I'll subsequently close.

**Comment by denyeo** [comment]
Having the same problem here. I'm using Firefox 36.0.

**Comment by anthonny** [comment]
I close this issue, now i use materialui
Feel to reopen if necessary
