### ISSUE TITLE
Sign in fails

### ISSUE THREAD

**Issue by RWOverdijk** [HubPress/hubpress.io#310]
Using TFA, signing in seems to fail.

```
XMLHttpRequest cannot load https://api.github.com/repos/RWOverdijk/rwoverdijk?1450860341936. The request was redirected to 'https://api.github.com/repositories/48451896?1450860341936', which is disallowed for cross-origin requests that require preflight.
app.js:80540 AuthServices - login error Object {path: "/repos/RWOverdijk/rwoverdijk", request: XMLHttpRequest, error: 0}(anonymous function) @ app.js:80540r @ app.js:49989(anonymous function) @ app.js:50015D.g.when @ app.js:50249n.promiseDispatch @ app.js:49933(anonymous function) @ app.js:49749a @ app.js:49295i @ app.js:14743
```

**Comment by anthonny** [comment]
Hi @RWOverdijk ,

In your `config.json`, the value of the `repositoryName` must be `rwoverdijk.github.io`

**Comment by RWOverdijk** [comment]
Ah right, I forgot. I'm an idiot.

thanks.

**Comment by ulisesantana** [comment]
Hey! I had another curious issue about sign in. I was trying sign in with the master branch and I couldn't. Then I tried to sign in setting gh-pages as branch in config.json and it works! I just change it again to master and still working (I guess its about tokens).
