### ISSUE TITLE
Downloading html instead of display it in the browser

### ISSUE THREAD

**Issue by blackgun** [HubPress/hubpress.io#317]
Reproduce steps: 

1. Open my blog: blackgun.github.io
2. Click an blog

Expected result: open my article in the browser

Actual result: downloading a html file

My env: 

- Mac OS X 10.11.3
- Chrome Version 48.0.2564.97 (64-bit)
- hubpress: forked today, https://github.com/blackgun/blackgun.github.io

**Comment by blackgun** [comment]
found the reason, the = {article name} can't be Chinese..

**Comment by hinaloe** [comment]
Please read :`hp-alt-title:` 设定第二名称 section on readme

**Comment by anthonny** [comment]
Hi @blackgun, i hope that the answer of @hinaloe can help you.

Thank you @hinaloe :smile:
