### ISSUE TITLE
Post preview in Roon theme

### ISSUE THREAD

**Issue by nikitablack** [HubPress/hubpress.io#322]
Hello.

Is it possible to change the preview in the loop - the number of words, html keep. I tried to change settings in `loop.hbs`  - tried `{{excerpt words="10"}}` and `{{content words="10"}}` but it have no effect - there're always 45 words and no html, pictures.

**Comment by jaredmorgs** [comment]
You'd need to check with the Ghost Theme docs to work out what is going on there. Closing off because I feel it is most likely a mod to the theme that is required, which is not something HubPress is focusing on for users.
