### ISSUE TITLE
Administration.adoc Korean Translation

### ISSUE THREAD

**Issue by dakeshi** [HubPress/hubpress.io#327]
I have completed korean translation for Administration.adoc.

**Comment by jaredmorgs** [comment]
Thanks for your work on Korean translations @dakeshi 

I'll be calling on you and the community once I wrap up outstanding changes to the GitBook Knowledgebase for translation support. Until then, we'll keep the repo-stored translations.

**Comment by dakeshi** [comment]
Thanks you @jaredmorgs 👍
