### ISSUE TITLE
Can't access to admin login

### ISSUE THREAD

**Issue by deniz946** [HubPress/hubpress.io#329]
hello, i can't access to admin panel, im putting my github credentials and i get this error "An error has occurred, see your console for more informations.
"

My repo is deniz946.github.io

**Comment by anthonny** [comment]
Hi @deniz946,

The repositoryName in your config.json must be : 
```
"repositoryName": "deniz946.github.io",
```
and not **.com**

**Comment by deniz946** [comment]
Fixed, thanks you!

**Comment by kskarthik** [comment]
Just followed the steps for setting up the blog & went to the address http://hubpress.github.io/demo.hubpress.io/hubpress to login
What happened

    First login was successful
    Right from the 2nd login the page is just not redirecting to the editor but stuck right there but showing successful authentication message.

I am using firefox 43 browser on linux

**Comment by anthonny** [comment]
@kskarthik move your issue here https://github.com/HubPress/hubpress.io/issues/333
