### ISSUE TITLE
Can't use anchors neither table of content(toc)

### ISSUE THREAD

**Issue by chbailly** [HubPress/hubpress.io#335]
Hi,

In my page I ,use 
  [[anchor]] to define the anchor
  \<\<anchor>> to call it

It does not work, it calls the link which is not correct:
https://\<myname>.github.io/hubpress/#\<anchor>

Also, I can not insert a table of content
I just create a page like this

= my page
:toc:

No table of content is visible
Thanks,

**Comment by jaredmorgs** [comment]
Normally the syntax you've used for anchors should work just fine.

Have you tried to specify the :setanchors: attribute in the post. Sometimes
that is required to discretely link to sectanchors.

For the toc, I've found that the :toc: attribute on it's own does not
generally work on any asciidoctor.js versions of Asciidoctor (of which
HubPress uses). Native Ruby Asciidoctor doesn't have this issue.

Try specifying this instead:

:toc: macro

Then where you want your toc to appear, specify:

toc::[]

See if that renders the TOC as you would expect.

On Tue, 1 Mar 2016 at 07:49 chbailly <notifications@github.com> wrote:

> Hi,
>
> In my page I ,use
> [[anchor]] to define the anchor
> <> to call it
>
> It does not work, it calls the link which is not correct:
> https://.github.io/hubpress/#
>
> Also, I can not insert a table of content
> I just create a page like this
>
> = my page
> :toc:
>
> No table of content is visible
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/335>.
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
sorry, that should have been :sectanchors: and not :setanchors:

On Wed, 2 Mar 2016 at 11:13 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> Normally the syntax you've used for anchors should work just fine.
>
> Have you tried to specify the :setanchors: attribute in the post.
> Sometimes that is required to discretely link to sectanchors.
>
> For the toc, I've found that the :toc: attribute on it's own does not
> generally work on any asciidoctor.js versions of Asciidoctor (of which
> HubPress uses). Native Ruby Asciidoctor doesn't have this issue.
>
> Try specifying this instead:
>
> :toc: macro
>
> Then where you want your toc to appear, specify:
>
> toc::[]
>
> See if that renders the TOC as you would expect.
>
> On Tue, 1 Mar 2016 at 07:49 chbailly <notifications@github.com> wrote:
>
>> Hi,
>>
>> In my page I ,use
>> [[anchor]] to define the anchor
>> <> to call it
>>
>> It does not work, it calls the link which is not correct:
>> https://.github.io/hubpress/#
>>
>> Also, I can not insert a table of content
>> I just create a page like this
>>
>> = my page
>> :toc:
>>
>> No table of content is visible
>> Thanks,
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HubPress/hubpress.io/issues/335>.
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by chbailly** [comment]
Thanks a lot, it works great as expected !
I hope hubpress will continue to develop, I am satisfied with it.
