### ISSUE TITLE
Change font of the notifications to default for the login/dashboard, for consistency

### ISSUE THREAD

**Issue by raisedadead** [HubPress/hubpress.io#336]
Just being picky on this one :wink: 

![image](https://cloud.githubusercontent.com/assets/1884376/13420413/010314c4-dfac-11e5-8f49-0464d693463b.png)

**Comment by jaredmorgs** [comment]
Yep, the notification toast does need some work.

For example, when you change your settings, the toast message concatenates.
The way messages were presented before in pop-up toasts allowed for quite
long messages (I was responsible for the wording), but they are no longer
suitable.

On Tue, 1 Mar 2016 at 17:22 Mrugesh Mohapatra <notifications@github.com>
wrote:

> Just being picky on this one [image: :wink:]
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1884376/13420413/010314c4-dfac-11e5-8f49-0464d693463b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/336>.
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
Toast behaviour has been improved in 0.6.x revisions. Thanks for the report.
