### ISSUE TITLE
username.github.io site not found.

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#340]
This I can see, and it has been configured.

https://github.com/peter-lawrey/peter-lawrey.github.io

however, 

http://peter-lawrey.github.io/

gives a site not found.

**Comment by anthonny** [comment]
Hi @peter-lawrey!

Really glad to see you here! 
Sometime github take some to time to consider a repository, but more than a hour is too much.
Could you try to delete the repository and refork the HubPress one please ?

**Comment by anthonny** [comment]
we will add a note in the documentation because @peter-lawrey you are the second user that encounter this issue

**Comment by peter-lawrey** [comment]
I have re-forked, renamed the repo and setup config.json again.

**Comment by peter-lawrey** [comment]
And now it is there!

**Comment by jaredmorgs** [comment]
What was the root cause of this issue so I can document the full issue.

On Sun, 20 Mar 2016, 01:09 Anthonny Quérouil <notifications@github.com>
wrote:

> we will add a note in the documentation because @peter-lawrey
> <https://github.com/peter-lawrey> you are the second user that encounter
> this issue
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/340#issuecomment-198719169>
>
-- 

Sent from Mobile.

**Comment by peter-lawrey** [comment]
The root cause wasn't clear.

The solution was to delete the repo and start again if it doesn't appear
within an hour.
