### ISSUE TITLE
I get an error when I try to post.

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#341]
I am trying to post a Hello World and I get an error

app.js?version=0.4.0-1454500827630:68 PostsServices - publishElements error TypeError: Cannot read property 'original' of undefined(…)

**Comment by peter-lawrey** [comment]
When I try to save a post, I get "Your post was not saved, See your browser's developer console for the cause of the error"  However in the console, there is no error.

app.js?version=0.4.0-1454500827630:64 PostsActionCreators - remoteSave
app.js?version=0.4.0-1454500827630:64 PostsActionCreators - remoteSave 7e9794a7-64e1-4d1a-8333-093861ee188e
app.js?version=0.4.0-1454500827630:68 SettingsStores - dispatcher
app.js?version=0.4.0-1454500827630:68 SettingsStores - dispatcher Object {type: "REMOTESAVE_POST", id: "7e9794a7-64e1-4d1a-8333-093861ee188e"}
app.js?version=0.4.0-1454500827630:68 AuthStores - dispatcher
app.js?version=0.4.0-1454500827630:68 AuthStores - dispatcher Object {type: "REMOTESAVE_POST", id: "7e9794a7-64e1-4d1a-8333-093861ee188e"}
app.js?version=0.4.0-1454500827630:68 AuthStores - dispatcher nothing to do
app.js?version=0.4.0-1454500827630:68 ThemeStores - dispatcher
app.js?version=0.4.0-1454500827630:68 ThemeStores - dispatcher Object {type: "REMOTESAVE_POST", id: "7e9794a7-64e1-4d1a-8333-093861ee188e"}
app.js?version=0.4.0-1454500827630:68 PostsStores - dispatcher
app.js?version=0.4.0-1454500827630:68 PostsStores - dispatcher Object {type: "REMOTESAVE_POST", id: "7e9794a7-64e1-4d1a-8333-093861ee188e"}
app.js?version=0.4.0-1454500827630:65 PostsStore.isLoading() true
app.js?version=0.4.0-1454500827630:68 AppStores - dispatcher
app.js?version=0.4.0-1454500827630:68 AppStores - dispatcher Object {type: "REMOTESAVE_POST", id: "7e9794a7-64e1-4d1a-8333-093861ee188e"}
app.js?version=0.4.0-1454500827630:67 PostsServices - remoteSave
app.js?version=0.4.0-1454500827630:67 PostsServices - remoteSave 7e9794a7-64e1-4d1a-8333-093861ee188e
app.js?version=0.4.0-1454500827630:64 PostsActionIDBCreators - receiveRemoteSave
app.js?version=0.4.0-1454500827630:64 PostsActionIDBCreators - receiveRemoteSave Object {message: Object}
app.js?version=0.4.0-1454500827630:68 SettingsStores - dispatcher
app.js?version=0.4.0-1454500827630:68 SettingsStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js?version=0.4.0-1454500827630:68 AuthStores - dispatcher
app.js?version=0.4.0-1454500827630:68 AuthStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js?version=0.4.0-1454500827630:68 AuthStores - dispatcher nothing to do
app.js?version=0.4.0-1454500827630:68 ThemeStores - dispatcher
app.js?version=0.4.0-1454500827630:68 ThemeStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js?version=0.4.0-1454500827630:68 PostsStores - dispatcher
app.js?version=0.4.0-1454500827630:68 PostsStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js?version=0.4.0-1454500827630:65 PostsStore.isLoading() false
app.js?version=0.4.0-1454500827630:68 PostsStore - getPost
app.js?version=0.4.0-1454500827630:68 PostsStore - getPost 7e9794a7-64e1-4d1a-8333-093861ee188e
app.js?version=0.4.0-1454500827630:68 AppStores - dispatcher
app.js?version=0.4.0-1454500827630:68 AppStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}

**Comment by anthonny** [comment]
Could you show me the content that you try to save ?
The minimum requirement is a title.

This content should work : 
```
= My title

My content
```

**Comment by anthonny** [comment]
I see your post ;)

**Comment by peter-lawrey** [comment]
I still have the default home page. How do I fix that?

**Comment by peter-lawrey** [comment]
I tried

= My title

My content // no new line

And it failed. but when I added a new line to the end, it saved ok.

**Comment by anthonny** [comment]
Certainly the cache of your browser 
<img width="1395" alt="capture d ecran 2016-03-19 a 16 35 40" src="https://cloud.githubusercontent.com/assets/2006548/13899524/b9a3ceea-edf0-11e5-8c92-519e2094695d.png">

**Comment by peter-lawrey** [comment]
That looks great.
