### ISSUE TITLE
Error when publishing a new post with an extra comma at the end of hp-tags attribute

### ISSUE THREAD

**Issue by Mogztter** [HubPress/hubpress.io#342]
### Steps to reproduce

 1.Create a new blog post with the following content

```
= Bug
:hp-tags: test,
```

 2.Save and publish the blog post

```
POST https://api.github.com/repos/indusbox/indusbox.github.io/git/trees?1458430101792 422 (Unprocessable Entity)

PostsServices - publishElements error Object {path: "/repos/indusbox/indusbox.github.io/git/trees", request: XMLHttpRequest, error: 422}
  (anonymous function) @ app.js?version=0.4.0-1454500827630:68
  o @ app.js?version=0.4.0-1454500827630:26
  c @ app.js?version=0.4.0-1454500827630:26u @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  o @ app.js?version=0.4.0-1454500827630:26
  c @ app.js?version=0.4.0-1454500827630:26
  u @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  s @ app.js?version=0.4.0-1454500827630:52
  (anonymous function) @ app.js?version=0.4.0-1454500827630:52
  T.m.when @ app.js?version=0.4.0-1454500827630:52
  r.promiseDispatch @ app.js?version=0.4.0-1454500827630:52
  (anonymous function) @ app.js?version=0.4.0-1454500827630:52
  n @ app.js?version=0.4.0-1454500827630:52
  t @ app.js?version=0.4.0-1454500827630:52
```

Error message from the GitHub API is:
```json
{
  "message": "tree.path contains a malformed path component",
  "documentation_url": "https://developer.github.com/v3/git/trees/#create-a-tree"
}
```

**Comment by jaredmorgs** [comment]
Ah yeah, the comma after the tag is causing that.

The last tag in the list must not contain a comma.

On Sun, 20 Mar 2016, 09:37 Guillaume Grossetie <notifications@github.com>
wrote:

> Steps to reproduce
>
> 1.Create a new blog post with the following content
>
> = Bug
> :hp-tags: test,
>
> 2.Save and publish the blog post
>
> POST https://api.github.com/repos/indusbox/indusbox.github.io/git/trees?1458430101792 422 (Unprocessable Entity)
>
> PostsServices - publishElements error Object {path: "/repos/indusbox/indusbox.github.io/git/trees", request: XMLHttpRequest, error: 422}
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:68
>   o @ app.js?version=0.4.0-1454500827630:26
>   c @ app.js?version=0.4.0-1454500827630:26u @ app.js?version=0.4.0-1454500827630:26
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:26
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:26
>   o @ app.js?version=0.4.0-1454500827630:26
>   c @ app.js?version=0.4.0-1454500827630:26
>   u @ app.js?version=0.4.0-1454500827630:26
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:26
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:26
>   s @ app.js?version=0.4.0-1454500827630:52
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:52
>   T.m.when @ app.js?version=0.4.0-1454500827630:52
>   r.promiseDispatch @ app.js?version=0.4.0-1454500827630:52
>   (anonymous function) @ app.js?version=0.4.0-1454500827630:52
>   n @ app.js?version=0.4.0-1454500827630:52
>   t @ app.js?version=0.4.0-1454500827630:52
>
> Error message from the GitHub API is:
>
> {
>   "message": "tree.path contains a malformed path component",
>   "documentation_url": "https://developer.github.com/v3/git/trees/#create-a-tree"
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/342>
>
-- 

Sent from Mobile.
