### ISSUE TITLE
After updating a post it no longer displayes.

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#346]
I can see it is here

https://github.com/Vanilla-Java/vanilla-java.github.io/blob/master/_posts/2016-03-22-Micro-services-for-performance.adoc

and

https://github.com/Vanilla-Java/vanilla-java.github.io/blob/master/2016/03/22/Micro-services-for-performance.html

and

https://vanilla-java.github.io/2016/03/22/Micro-services-for-performance.html

but not

https://vanilla-java.github.io/

At first when I saved the page, the .html for the page disappeared but when I republished, it was rebuilt, however the index page hasn't updated.

**Comment by anthonny** [comment]
The index.html page is update : 
https://github.com/Vanilla-Java/vanilla-java.github.io/blob/master/index.html#L138

But i think it's the cache of github pages that has not be invalidate.
Could you just resave the post?

**Comment by peter-lawrey** [comment]
I have re-saved it and the HTML has disappeared again.

**Comment by peter-lawrey** [comment]
Saving it doesn't help but if I publish again (a second time) it appears.

And it's on the home page now.

So it appears if I keep trying to re-publish, eventually it works. Maybe.

**Comment by rorosaurus** [comment]
I'm seeing something weird like this as well.  The index page is updated but the site still lags.

Republish doesn't work for me, but publishing a new post appears to fix all the old posts.  (But new post isn't visible...)

**Comment by rorosaurus** [comment]
Resaving the new post fixes that.  This is a weird one!  I wonder if this is a bug in HubPress or Github Pages...

**Comment by jaredmorgs** [comment]
@peter-lawrey @rorosaurus Have either of you folks seen this behaviour since reporting the issue in April. 

I've got a feeling that it's all good now, but just wanted to check before closing off.

**Comment by peter-lawrey** [comment]
I haven't thank you.
