### ISSUE TITLE
[Enhancement] [Editor] WYSIWYG Mode

### ISSUE THREAD

**Issue by Murazaki** [HubPress/hubpress.io#35]
Could be useful for people who don't know a thing about Ascii docs. I didn't find one online but maybe you have an idea ?

**Comment by jaredmorgs** [comment]
I think that might be what the live preview is all about. I do find that I need to go and have a look at asciidoctor.org's cheatsheet daily for AsciiDoc syntax. I think it's a choice you make when you select any mark-up language. You actually need to learn the language and experiment.

**Comment by anthonny** [comment]
Hi @Murazaki ,

I agree with @jaredmorgs.
For writers the power of a markup is that the syntax keeps you focused on the content.
We are aware that the use of Asciidoc can be complicated at the beginning, we will add some helpers https://github.com/HubPress/hubpress.io/issues/77 https://github.com/HubPress/hubpress.io/issues/15

**Comment by Murazaki** [comment]
I understand that you want to stick with AsciiDoc.
Just a point though, it could be good for further UX improvements : The choice of a markup language is not the user's choice here, but the developer's.

**Comment by jaredmorgs** [comment]
You have a live preview of your AsciiDoc markup. That's about as WYSIWYG as
asciidoc gets. HubPress actually makes it easier than normal.

And it's the user's choice to select this solution knowing that asciidoc is
the underlying markup language. Choose HubPress over all the other fork and
write solutions like jekyll-now and you're making a conscious decision to
learn AsciiDoc.

**Comment by ryanmavilia** [comment]
We could always implement a toolbox (for automatic AsciiDoc markup), that would be easy to turn off for those who don't want to focus on the markup aspect.

**Comment by jaredmorgs** [comment]
I did suggest having quick formatting buttons in another issue from memory.
Use some of the UI real-estate up the top of the editing window to add
things like sections, bulleted lists, ordered lists, etc.

**Comment by jaredmorgs** [comment]
This issue is somewhat stale now, and was previously marked as wontfix over a year ago. I am going to close this out as part of project maintenance.
