### ISSUE TITLE
Broken H1 link

### ISSUE THREAD

**Issue by wols** [HubPress/hubpress.io#350]
My repo is `https://<username>.github.io/<repositoryName>/`.

The rendered `YYYY/mm/dd/MyPost.html` contains the posts title `MyPost` with a H1 link to `/YYYY/mm/dd/MyPost.html` - this gives a `404`.

The right way is `/<repositoryName>/YYYY/mm/dd/MyPost.html`.

**Comment by anthonny** [comment]
Hi @wols,
Thank you for pointing me this bug :+1:

**Comment by wols** [comment]
The used theme was `ghostium`.

**Comment by anthonny** [comment]
Fixed with the 0.6.0 see https://github.com/HubPress/hubpress.io/issues/414#issuecomment-234722077
