### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by bigkahuna1uk** [HubPress/hubpress.io#353]
http://bigkahuna1uk.github.io/hubpress/#/login

I just get a spinning icon.  I've tried on different browsers and cleared cache with same negative results.

I had tried to change the theme to Casper but it doesn't look like this was published as my blog is still using uno-zen.

I can't edit my blog anymore. Any ideas?

**Comment by anthonny** [comment]
Hi @bigkahuna1uk,

The name of the theme must be `Casper` and not `casper`, i think that the problem is here

**Comment by bigkahuna1uk** [comment]
Thanks, that solved the problem.

**Comment by anthonny** [comment]
Good news ;)
