### ISSUE TITLE
i cannot log into the console of the hubpress

### ISSUE THREAD

**Issue by wzy632051146** [HubPress/hubpress.io#355]
After filling my Github username and password, the console tells me that "An error has happened,please see your console for more information."

I am sure that both my username and password are right.But it just keeps telling me that there is an  error.

**Comment by anthonny** [comment]
In your config.json https://github.com/wzy632051146/wzy632051146.github.io/blob/master/hubpress/config.json, the value of the repository name is not good:

`"repositoryName": "hubpress.github.io"`

It must be:
`"repositoryName": "wzy632051146.github.io"`

**Comment by jaredmorgs** [comment]
Closing due to no further comments.
