### ISSUE TITLE
How to add utf-8 title?

### ISSUE THREAD

**Issue by yokas** [HubPress/hubpress.io#360]
when use utf-8 char in

= UTF-8-TITLE

it ends up with a `.html` file

**Comment by hinaloe** [comment]
You can use `:hp-alt-title:` :)
https://github.com/HubPress/hubpress.io/blob/master/Writers_Guide.adoc#34-hp-alt-title-to-specify-an-alternative-title

**Comment by yokas** [comment]
@hinaloe thank you
