### ISSUE TITLE
How to control order of the posts?

### ISSUE THREAD

**Issue by yokas** [HubPress/hubpress.io#362]
I posted two posts, but the order is old post in the front of new post

----home page-----
header

old-post-title

new-post-title

footer

**Comment by jaredmorgs** [comment]
Did you set a :published-at: attribute in the post that could be changing
the post order?

On Wed, 6 Apr 2016, 20:26
greasgreasgreasgreasgreasgreasgreasgreasgreasgreasgreasgreas <
notifications@github.com> wrote:

> I posted two posts, but the order is old post in the front of new post
>
> ----home page-----
> header
>
> old-post-title
>
> new-post-title
>
> footer
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/362>
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
Closed due to lack of response.
