### ISSUE TITLE
Is there anyway to get a local preview of my site?

### ISSUE THREAD

**Issue by fusion809** [HubPress/hubpress.io#366]
Hi,

I was wondering if it might be possible to generate my Hubpress site (including local, uncommitted changes) locally and preview it in my web browser, similarly to how I can do this with Jekyll by installing Jekyll locally and running:

    jekyll serve

from my site's top-level directory, and opening my browser to the link provided by this command (usually 0.0.0.0:4000).

Thanks for your time,
Brenton

**Comment by metasean** [comment]
It's not really possible at this time.  This functionality has already been requested in issue #324 (that issue also has some discussion).
