### ISSUE TITLE
Acronyms in the title.

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#369]
When choosing a URL for the title, it appears to break up Acronyms.  Can we have Acronyms stay as they are. e.g.

https://vanilla-java.github.io/2016/04/12/A-J-D-B-C-Gateway-Microservice.html

A more obvious URL might be

A-JDBC-Gateway-Microservice.html

**Comment by anthonny** [comment]
Thank you for pointing me this bug.
It will fix in the next version, i have added a test: https://github.com/HubPress/hubpress-core-slugify/blob/master/test/slugify.js#L40

It will be available really soon

**Comment by jaredmorgs** [comment]
@peter-lawrey Can you verify this is fixed for you in v0.5.1 (just released)

**Comment by peter-lawrey** [comment]
I will the next time I use an acronym ;)
