### ISSUE TITLE
Any plan to release the raw source code of admin script?

### ISSUE THREAD

**Issue by lilee** [HubPress/hubpress.io#37]
Any plan to release the raw source code of admin script? now there is only compiled "app.js"

**Comment by anthonny** [comment]
Hi @lilee ,
I plan to release the raw source for the end of the month, earlier if i can

**Comment by lostfictions** [comment]
Seconded. I'm not comfortable using this without an easy way to modify (or even see!) what goes in the concatenated file!

**Comment by jaredmorgs** [comment]
Closing off issue as it is being tracked in #73.

**Comment by lostfictions** [comment]
Uhh, I just looked at #73 and the only reference to this issue is... literally a link back to this issue. #73 is closed and this is still not resolved, so it'd be nice to re-open this or start a new issue to track it.

**Comment by anthonny** [comment]
If you are loooking for sources, they are available on the development branch

**Comment by lostfictions** [comment]
Thanks!
