### ISSUE TITLE
No meaningful error message when saving post with no title

### ISSUE THREAD

**Issue by rorosaurus** [HubPress/hubpress.io#374]
Newly created fork, https://github.com/shaynemhayes/shaynemhayes.github.io

Trying to create my first post and get the ````"Your post was not saved. See your browser's developer console for the cause of the error."```` telling me to check console.  I see the following error in console.

````PostsServices - publishElements error TypeError: Cannot read property 'original' of undefined````

Is this a known issue?  Am I doing something wrong?  This seems like the most basic test, but it's not working.  I've disabled my browser add-ons and tried in incognito mode.

**Comment by rorosaurus** [comment]
Original title: Cannot save or publish a new post
New title: No meaningful error message when saving post with no title

I was very confused when my first post failed to post, but after some digging I realized I might need to start each post with 

```
= Update: What's New in Version 0.4.0
:hp-tags: release
```

Or something similar, to define the title and tags.  Updating the post to include these, it posts fine.
So I propose we give a more obvious error message for this case.

**Comment by rorosaurus** [comment]
I see it mentioned in the writer's guide now, (https://github.com/rorosaurus/hubpress.io/blob/gh-pages/Writers_Guide.adoc#blog-title-and-headings) but I do think it's worth giving an actionable error here, since many people seem to gloss over documentation anyway! ;)

**Comment by jaredmorgs** [comment]
This is being improved in 0.5.0.

The save button will be unavailable until you start the blog post with an
equals sign.

On Mon, Apr 25, 2016, 13:26 Rory Hayes <notifications@github.com> wrote:

> I see it mentioned in the writer's guide now, (
> https://github.com/rorosaurus/hubpress.io/blob/gh-pages/Writers_Guide.adoc#blog-title-and-headings)
> but I do think it's worth giving an actionable error here, since many
> people seem to gloss over documentation anyway! ;)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/374#issuecomment-214110218>
>
-- 

Sent from Mobile.
