### ISSUE TITLE
Administration page stuck on spinner in Edge browser

### ISSUE THREAD

**Issue by rorosaurus** [HubPress/hubpress.io#375]
![image](https://cloud.githubusercontent.com/assets/908662/14771149/f7ce5750-0a36-11e6-9902-8623d43f55ec.png)

**Comment by jaredmorgs** [comment]
https://github.com/HubPress/hubpress.io/blob/master/README.adoc#browser-compatibility
list the compatible browsers.

On Mon, Apr 25, 2016, 09:10 Rory Hayes <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/908662/14771149/f7ce5750-0a36-11e6-9902-8623d43f55ec.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/375>
>
-- 

Sent from Mobile.
