### ISSUE TITLE
IE11 appears to default to a mobile view for admin login

### ISSUE THREAD

**Issue by rorosaurus** [HubPress/hubpress.io#376]
Despite requesting a desktop version of the site.

![image](https://cloud.githubusercontent.com/assets/908662/14772667/dad9f568-0a55-11e6-9787-e67c9cecc7d4.png)

**Comment by jaredmorgs** [comment]
Chrome and Firefox are the only supported browsers. See
https://github.com/HubPress/hubpress.io/blob/master/README.adoc#browser-compatibility

On Mon, Apr 25, 2016, 12:51 Rory Hayes <notifications@github.com> wrote:

> Despite requesting a desktop version of the site.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/908662/14772667/dad9f568-0a55-11e6-9787-e67c9cecc7d4.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/376>
>
-- 

Sent from Mobile.
