### ISSUE TITLE
Not able to customize a 404 page

### ISSUE THREAD

**Issue by rorosaurus** [HubPress/hubpress.io#377]
https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

This doesn't work, due to the .nojekyll file I assume.  Perhaps we can get rid of the _posts directory and re-enable jekyll if we do switch to PouchDB in 0.5.0?  Or is there a way to do with without Jekyll on Github pages?

**Comment by anthonny** [comment]
Hi @rorosaurus,

PouchDB is used in the browser, we still need to store the posts in a backend ie the _posts directory.
I will look if it is possible to have a 404 page without a jekyll context

**Comment by rorosaurus** [comment]
@anthonny seems the answer is yes.

I asked: 

> Is it possible to have a 404 page for a Github pages site that explicitly disabled Jekyll with the ".nojekyll" file?

I got the following reply: 

> Hey Rory,
Yes you can, just call the file 404.html.
The major difference is that you don't put any yaml front matter in.
Regards,
Daniel
@danayel
GitHub Support

So it is possible.  Might be nice to support theme's 404 pages in the future, but it's possible to create your own today if you're willing to create the .html file directly.

**Comment by anthonny** [comment]
@rorosaurus so for having be sooo long to answer. Thank you for the informations about the 404.

**Comment by jaredmorgs** [comment]
Closing this off and will get this feature added to pages support in #438
