### ISSUE TITLE
Not updating consistently

### ISSUE THREAD

**Issue by reggert** [HubPress/hubpress.io#379]
Sometimes, when I edit an unpublished post on one machine and then switch to another, the changes don't show up when I try to edit the post on another machine (though they do show up in version control). I actually had to clone the repository locally and copy and paste the contents into the browser to force it to display the latest changes, several days after I made them. Additionally, publishing posts seems to be extremely unreliable. I've found that I need to edit and revert index.html and then push those non-changes to get anything new to show up on GitHub Pages.

These issues render HubPress nearly unusable for me.

**Comment by anthonny** [comment]
Hi @reggert,

I have added a *synchronize* button for the next version.

> Additionally, publishing posts seems to be extremely unreliable.

I agree, but if you look at the `index.html` after a publishing, it is up-to-date. I think it is more a problem with the cache of github

**Comment by jaredmorgs** [comment]
@reggert The new version is out now. Pull the latest changes down to your repo by following the Administration Guide.

**Comment by anthonny** [comment]
@reggert the problem should be fixed, feel free to reopen if necessary
