### ISSUE TITLE
tags link to 404

### ISSUE THREAD

**Issue by jericksanjuan** [HubPress/hubpress.io#38]
Tags added to posts are shown but links to the github 404 page.

**Comment by anthonny** [comment]
Hi @jericksanjuan,

Tags urls are not implemented yet that's why you have a 404.

**Comment by jasonswearingen** [comment]
This impacts discovery and makes the site feel broken in it's current state.  This is literally the 2nd feature I tested out (after the Saga post images).

As is, does not seem usable for a real blog.

**Comment by anthonny** [comment]
Hi @jasonswearingen,

I agree, tags will be available really soon (few hours). Have you some problems with the Saga post images ?

**Comment by jasonswearingen** [comment]
Hi @anthonny, Saga works well (it's the only theme I tried) and no problems with post images, as I was following the guide.

The roughest part of the editing experience is embedding attachments/images, as they need to be uploaded somewhere first before adding to the post.  I would suggest in the docs, you highlight an example blog using HubPress that can be used for examples/inspiration, because there's a lot of functionality to asciidoc and it's a bit overwhelming to newbies.

**Comment by jaredmorgs** [comment]
Hi Jason

I have actually created a sample blog template that would be loaded when a
user first provisions HubPress. It blends AsciiDoc comments in-line with
sample mark-up, and explains some of the techniques to get images and other
stuff that first-time AsciiDoc users might trip up on.

Users can switch between raw and rendered modes and see how the sample
looks real-time (comments are not rendered).

I think @anthonny just needs to hook it into the first-run experience. It's
on the /development/docs/ branch.

**Comment by anthonny** [comment]
@jaredmorgs you're right, i need to hook it, certainly in the next release.
@jericksanjuan @jasonswearingen tags are available now, could you merge from the upstream and test? If it's ok for you we can close the issue

**Comment by jasonswearingen** [comment]
works for me (as does updating by pulling from hubpress upstream) though I have only tested it in a very limited fashion (only one post/one tag).  I will file an issue if anything else comes up!

FYI, now that that tags issue is fixed, it seems hubpress is now usable for a "real" blog!  (the previous 404 on tag click was the only showstopper i saw)

**Comment by anthonny** [comment]
> FYI, now that that tags issue is fixed, it seems hubpress is now usable for a "real" blog!
Great news :+1: Thank you :)

**Comment by alxndr** [comment]
Will existing posts need to be re-published to have their tags fixed?

**Comment by anthonny** [comment]
@alxndr yes, you can submit your settings it'll republish all your published posts.
