### ISSUE TITLE
false DB ERROR: InvalidStateError occurred when opening database <dbname>.github.io. A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by volyx** [HubPress/hubpress.io#380]
I cannot login in my account, see exception in console -

`false DB ERROR: InvalidStateError occurred when opening database  <dbname>.github.io. A mutation operation was attempted on a database that did not allow mutations.`
What does it mean?

**Comment by volyx** [comment]
How can I restore previous state? I cannot login in my account.

![Hanging](https://i.gyazo.com/8c8b0b1c858f4c1496d3228fcb170d62.gif)

**Comment by anthonny** [comment]
Hi @volyx 
I must make more research to understand what happen.

You can delete your database, the only problem is that you will loose your draft (every posts that are not saved on github).

In the resource tag, your can see your indexedDB database `hubpress-volyx-volyx.github.io`, for example for my blog:
<img width="660" alt="capture d ecran 2016-05-01 a 11 56 06" src="https://cloud.githubusercontent.com/assets/2006548/14941209/bd441680-0f93-11e6-8d13-1aed6226b677.png">

Go to this url http://volyx.github.io/hubpress/#/login and in your console run this:
```shell
window.indexedDB.deleteDatabase('hubpress-volyx-volyx.github.io')
```

Then refresh your page and login, it should work

**Comment by anthonny** [comment]
I'm really sorry, i took so much time to answer 😢

**Comment by jaredmorgs** [comment]
No response from the OP. I'm closing it off assuming the issue was resolved.
