### ISSUE TITLE
Just Installed Hubpress, Test Post Failing to Exception

### ISSUE THREAD

**Issue by ToddAT** [HubPress/hubpress.io#383]
I just forked hubpress, set up the config, and launched the site. Everything comes up fine but when I go into the Admin interface and try to test post or update the meta information, I get back the following error:

>`Exception: asciidoctor: FAILED: <stdin>: Failed to parse source, undefined is not an object (evaluating 'e.$chr')`

My test post, as an example, was "This is a test." Any ideas?

EDIT:

I get a slightly different error if I try to `publish` instead of `save`:

>`PostsServices - publishElements error - TypeError: undefined is not an object (evaluating 'n.original')`

**Comment by jabby** [comment]
Did you add a title in your article or just the sentence "This is a test." ? You can find documentation here : https://github.com/HubPress/hubpress.io/blob/master/Writers_Guide.adoc

Try with this valid blog post :
```
= Title

My content
```

**Comment by ToddAT** [comment]
Aha, did not add a title. Will try that and report back. Thanks.

**Comment by ToddAT** [comment]
So that worked as far as *saving* the post went. However, I still get an error when I try to publish the file:
>`[Error] Failed to load resource: the server responded with a status of 404 (Not Found)`

The path is:
>https://api.github.com/repos/ToddAT/hexed.press/contents/_posts/2016-05-14-Test.adoc

The post is visible and editable from the admin screen but it won't publish.

**Comment by anthonny** [comment]
Hi @ToddAT,

You repository is named `hexed.press` so you must use the `gh-pages` branch. See https://github.com/ToddAT/hexed.press#33-use-a-custom-domain-or-github-page-domain-already-in-use

**Comment by ToddAT** [comment]
I was aware of using `gh-pages` which I was. Missed the step to set it to the `default` branch. Thanks.
