### ISSUE TITLE
Unable to post

### ISSUE THREAD

**Issue by mufarooqq** [HubPress/hubpress.io#384]
Hi,
I have just forked this repo. I have completed all the steps for installation and the blog is up now. I just tried to make a blog post but it gave me this error:
"Your post was not saved. See your browser's developer console for the cause of the error."

I have tried deleting tokens from https://github.com/settings/tokens but it didn't work.

**Comment by anthonny** [comment]
Hi @mufarooqq,

Could you show me the content you try to save?
The minimum requirement for a post is title, this content should work: 
```adoc
= My title

My content
```

**Comment by mufarooqq** [comment]
Please see this image:
![image](https://cloud.githubusercontent.com/assets/12568979/15469056/37cc1d20-2101-11e6-973f-87ac8e82ef80.png)

**Comment by anthonny** [comment]
That's it, you need a title for your blog post ;)

**Comment by mufarooqq** [comment]
WOW!!!!!!!! Thanks a ton man! (y)
