### ISSUE TITLE
can not login admin  width custom domin

### ISSUE THREAD

**Issue by senola** [HubPress/hubpress.io#385]
i use  latest  chrome , and use a custom domin “hubpress.io” 。 do witdh HubPress tips ,but no work !

site: http://deepwind.github.io/hubpress.io/hubpress/#/login

help me, please~

![20160527200839](https://cloud.githubusercontent.com/assets/6022948/15607627/e74c6532-2446-11e6-98eb-e3e7295fc647.png)

**Comment by anthonny** [comment]
Hi @senola 

If you want to use the domain `deepwind.github.io`, you do not need to use a CNAME

**Comment by jaredmorgs** [comment]
No response from the OP. Closing off assuming the issue was resolved.
