### ISSUE TITLE
Administration site won't load

### ISSUE THREAD

**Issue by lauesa** [HubPress/hubpress.io#386]
I am currently working to set up a blog for my personal website using Hubpress. Using the subdomain blog: [blog.scottlaue.com](blog.scottlaue.com) I am able to reach the successful configuration page, but the administration site presents a loading icon that never loads: [http://blog.scottlaue.com/hubpress](http://blog.scottlaue.com/hubpress)

**Comment by anthonny** [comment]
Hi @lauesa 
I think you have added the CNAME manually, so the config.json is not sync.

Edit your config.json like this: 

```json

{
  "meta": {
    "username": "lauesa",
    "repositoryName": "Blog",
    "branch": "gh-pages",
    "cname": "blog.scottlaue.com"
  },
  "theme": {
    "name": "Casper"
  }
}

```

**Comment by lauesa** [comment]
That worked. Thanks for the help @anthonny
