### ISSUE TITLE
Can not Post Blog

### ISSUE THREAD

**Issue by hhimanshu** [HubPress/hubpress.io#39]
When I try to save my first blog post entry, I see 

![screen shot 2015-02-09 at 7 45 49 pm](https://cloud.githubusercontent.com/assets/6589036/6121265/68f411ca-b094-11e4-90ae-207a57b6bc20.png)
and my console looks like 

![screen shot 2015-02-09 at 7 45 59 pm](https://cloud.githubusercontent.com/assets/6589036/6121268/717fce4c-b094-11e4-89f9-b20f67e0e283.png)

I am authenticated correctly and I am using Google Chrome as Browser
Let me know @anthonny

**Comment by anthonny** [comment]
Can you show me the content you try to save ?

A title is required (my bad it's not in the doc), can you try to save this sample :+1: 
```
= Title

My content
```

**Comment by byoigres** [comment]
I have the exactly same problem, I create a new post, then pressed save and publish and this are the messages that I got from console.error: (You can parse the string to JSON please)

    "[{"0":"PostsServices - publishElements error","1":{"path":"/repos/byoigres/byoigres.github.io/contents/_posts/2015-02-10-Title.adoc","request":{"statusText":"Unprocessable Entity","status":422,"responseURL":"https://api.github.com/repos/byoigres/byoigres.github.io/contents/_posts/2015-02-10-Title.adoc?1423553505644","response":"{\n  \"message\": \"Invalid request.\\n\\nMissing required keys \\\"sha\\\" in object; keys are \\\"branch, content, message\\\".\",\n  \"documentation_url\": \"https://developer.github.com/v3/repos/contents/\"\n}\n","responseType":"","responseXML":null,"responseText":"{\n  \"message\": \"Invalid request.\\n\\nMissing required keys \\\"sha\\\" in object; keys are \\\"branch, content, message\\\".\",\n  \"documentation_url\": \"https://developer.github.com/v3/repos/contents/\"\n}\n","upload":{"ontimeout":null,"onprogress":null,"onloadstart":null,"onloadend":null,"onload":null,"onerror":null,"onabort":null},"withCredentials":false,"readyState":4,"timeout":0,"ontimeout":null,"onprogress":null,"onloadstart":null,"onloadend":null,"onload":null,"onerror":null,"onabort":null,"dataType":"json"},"error":422}},{"0":"PostsServices - publishElements error","1":{"path":"/repos/byoigres/byoigres.github.io/contents/_posts/2015-02-10-Title.adoc","request":{"statusText":"Unprocessable Entity","status":422,"responseURL":"https://api.github.com/repos/byoigres/byoigres.github.io/contents/_posts/2015-02-10-Title.adoc?1423553505644","response":"{\n  \"message\": \"Invalid request.\\n\\nMissing required keys \\\"sha\\\" in object; keys are \\\"branch, content, message\\\".\",\n  \"documentation_url\": \"https://developer.github.com/v3/repos/contents/\"\n}\n","responseType":"","responseXML":null,"responseText":"{\n  \"message\": \"Invalid request.\\n\\nMissing required keys \\\"sha\\\" in object; keys are \\\"branch, content, message\\\".\",\n  \"documentation_url\": \"https://developer.github.com/v3/repos/contents/\"\n}\n","upload":{"ontimeout":null,"onprogress":null,"onloadstart":null,"onloadend":null,"onload":null,"onerror":null,"onabort":null},"withCredentials":false,"readyState":4,"timeout":0,"ontimeout":null,"onprogress":null,"onloadstart":null,"onloadend":null,"onload":null,"onerror":null,"onabort":null,"dataType":"json"},"error":422}}]"

![screenshot from 2015-02-10 00 36 20](https://cloud.githubusercontent.com/assets/1704690/6123254/ef237eca-b0bc-11e4-914f-63c20e91c18e.png)

**Comment by anthonny** [comment]
Hi @byoigres !
If you want to use your domain **byoigres.github.io**, you must work on the master branch.
Can you set your master as default branch, update your config.json on the master and try again ?

**Comment by anthonny** [comment]
@byoigres I see your post congrats and welcome in hubpress

**Comment by byoigres** [comment]
It works, I'll do more test tommorow, thanks.

**Comment by hhimanshu** [comment]
Yea it works
Document should clearly mention that heading has to be

=

Thanks a lot

**Comment by naveensrinivasan** [comment]
README has been updated with the information.

**Comment by anthonny** [comment]
Yes thanks to @naveensrinivasan :+1:

**Comment by polarbill** [comment]
I had the same issue, and the master branch was not set as default. Thank you for your help.
