### ISSUE TITLE
How to use the include directive?

### ISSUE THREAD

**Issue by simevidas** [HubPress/hubpress.io#390]
Sorry if this is a n00b question 😅. I would like to use the [`include::` directive](http://asciidoctor.org/docs/user-manual/#include-directive). Is it supported?

I would like to include .adoc files from my HubPress repo on GitHub; I’m in the HubPress web editor and I’m trying to figure out in which format the relative path must be; I keep getting:

```
Unresolved directive in <stdin> - include::foo.adoc[] === Why?

Indication for user that external resource is over non-secure HTTP Also helps me detect
such resources when creating releases.
```

***

Btw, my concrete use case is this: I would like to start a multi-part series of blog posts. At the end of each such blog post, there should be a box with a full list of all the posts in this series. I could maintain this list in a separate file, end then just `include::` this file at the end of each post in the series.

**Comment by jaredmorgs** [comment]
I've got a feeling that you'd need to use the RAW link to your file. I don't believe that HubPress currently is aware of the source posts from a re-use perspective. 

For example:

```
include::https://raw.githubusercontent.com/jaredmorgs/jaredmorgs.github.io/master/_posts/2016-04-11-Being-Switzerland-Has-Its-Advantages.adoc[Being Switzerland Has Its Advantages]
```

You can try that first, then report back. Just use the same approach with one of your blog posts.

**Comment by anthonny** [comment]
Includes work in the 0.5.1 and gist too.
@jaredmorgs is right, you must use the raw version of the file which is a plain text version of your file.

To use gist: 
```adoc
gist::7786310[]

/// With lines for example
gist::7786310[lines=1...3]

```

**Comment by simevidas** [comment]
@jaredmorgs Here’s the live page I’m using for testing: http://simevidas.com/2015/05/10/Blowing-up-pixel-art-on-the-Web.html; I’ve tried a bunch of URLs, but I get the same “Unresolved directive” error. 

Note that the internal page sub-resources (CSS, JS) currently don’t load because 0.5.1 updated the Casper theme directory to no longer be capitalized, but the generated HTML pages still contain URLs with capitalized Casper in them; not sure how to resolve this.

**Comment by anthonny** [comment]
> Note that the internal page sub-resources (CSS, JS) currently don’t load because 0.5.1 updated the Casper theme directory to no longer be capitalized, but the generated HTML pages still contain URLs with capitalized Casper in them; not sure how to resolve this.

It's breaking change with tthe 0.5.1, we will communicate about that in our future blog post.
To fix the problem, you just have to go in the **Settings** page of your HubPress instance and click on **Save**
It will regenerate all your posts

**Comment by anthonny** [comment]
Just try include with personal blog:

<img width="949" alt="capture d ecran 2016-06-19 a 17 24 14" src="https://cloud.githubusercontent.com/assets/2006548/16178234/b9da2888-3642-11e6-97f4-b13fdcda1e9f.png">

Do you have the same UI? Just to be sure that is not a problem with browser cache

**Comment by simevidas** [comment]
@anthonny Uh, my apologies; I’ve pulled 0.5.1 (via GitHub) just now but didn’t reload the web editor since then. Works now 🙌
