### ISSUE TITLE
After updating the version of hubpress can we see in the GUI it has been updated.

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#391]
A hubpress version would be nice, on the menu bar.

"Hubpress 0.5.1"

**Comment by alxndr** [comment]
Tangentially related: can the Changelog get an update to show what's important in v0.5.x?

**Comment by anthonny** [comment]
@peter-lawrey i agree, it will in the next version

@alxndr my bad, i made the release too fast and i totally omit the Changelog. I'll update it tomorrow.
Most of the changes are here : http://blog.hubpress.io/2016/06/20/Update-Whats-New-in-Version-051.html

**Comment by anthonny** [comment]
@alxndr CHANGELOG is up-to-date now 😄

**Comment by anthonny** [comment]
with the 0.6.0, the version is now displayed in the menu bar ;)
