### ISSUE TITLE
:hp-image: not working with local files

### ISSUE THREAD

**Issue by dchun** [HubPress/hubpress.io#400]
:hp-image: works when adding an external image with a link but not with files uploaded to the images folder. Example [here](https://github.com/dchun/dchun.github.io/tree/master/_posts)

**Comment by anthonny** [comment]
Hi @dchun 

Have you the problem in the preview? because in you published content  i can see the image : 
https://dchun.github.io/2016/07/15/Testing-hubpress-blog.html

<img width="755" alt="capture d ecran 2016-07-15 a 18 32 33" src="https://cloud.githubusercontent.com/assets/2006548/16881473/a79c26b2-4aba-11e6-947a-fc306ed65f9b.png">

**Comment by dchun** [comment]
I'm referring to the header image. I tried a variety of ways but it doesnt seem to appear here: https://dchun.github.io/

**Comment by anthonny** [comment]
Ok i understand now, sorry i did not take attention to the `hp-image` in your issue.

`:hp-image: /images/cover/mui_ne.jpg` will work.

**Comment by dchun** [comment]
@anthonny still doesn't work. It also seems to run contrary to the advice in the docs:  https://github.com/HubPress/hubpress.io/blob/master/Writers_Guide.adoc#31-hp-image-for-blog-post-cover-images

**Comment by anthonny** [comment]
I can see your cover: 
<img width="807" alt="capture d ecran 2016-07-16 a 01 28 59" src="https://cloud.githubusercontent.com/assets/2006548/16891046/ce2f01a2-4af4-11e6-8631-ddf52af06675.png">

Certainly the cache of your browser

**Comment by dchun** [comment]
Perfect! thanks! So I guess the docs are outdated?

**Comment by anthonny** [comment]
The note is true for all images except :hp-images: 😢 
The doc need an update that's true

**Comment by anthonny** [comment]
You're welcome, FYI i have just release the 0.6.0

**Comment by jaredmorgs** [comment]
I have added clarification to this in https://hubpress.gitbooks.io/hubpress-knowledgebase/content/parameters/hp-image.html
