### ISSUE TITLE
Logo redesign

### ISSUE THREAD

**Issue by starchvser** [HubPress/hubpress.io#404]
I thought about having the logo redesigned. I personally don't find the hexagon shape very appealing and I thought about making it simpler and perhaps more appealing.
What about something like that?

![logo](https://cloud.githubusercontent.com/assets/8578085/16895429/81af9b22-4b7e-11e6-8a72-bd7a05e62b43.png)

If you do decide to incorporate this in the project, I can make similar looking assets (buttons, favicon, etc)

**Comment by jaredmorgs** [comment]
Thanks for taking the time to create this logotype @Ryiseld 

The thing that is good about the original HubPress logo is that it is quite compact and looks good on the login screen. 

I'm not sure how HubPress would incorporate the logotype into the original UI design. 

I'm going to leave the issue open to see if bumping it will encourage others to collaborate with you and lead on from your initiative. 

Thanks again for taking the first step.
