### ISSUE TITLE
What is an easy way to add web usage metrics to hubpress?

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#409]
I am sure there is lots of options, but I don't know any.

**Comment by anthonny** [comment]
Hi @peter-lawrey 

You mean some metrics for your instance of hubpress ? for that you can use google analytics (just set your code UA-XXXXX-XXXX in the settings panel)

Or something more general like how many people use HubPress ?

**Comment by peter-lawrey** [comment]
Yes, thank you.
