### ISSUE TITLE
Deploying Hubpress outside github 

### ISSUE THREAD

**Issue by kskarthik** [HubPress/hubpress.io#410]
Hubpress is amazing ! but sad that it's confined to github :cry:  great thing is it can run without a runtime. so, can be deployed on any server, But as far my knowledge we only have problem with authentication. Can it be solved by using any other means ? (fb, twitter, dropbox api's)

**Comment by anthonny** [comment]
Hi @kskarthik 

> Hubpress is amazing !

Thank you so much!

I working on a gitlab integration.
The problem is not only the authentication, HubPress use the github api for everything (https://github.com/HubPress/hubpress-plugin-github)

I must work on the documentation to make contribution easier

**Comment by kskarthik** [comment]
@anthonny i am also taking about hosting on any server we like. Are there any hurdles for it ?

**Comment by kskarthik** [comment]
@anthonny since few days i am unable to login to my blog https://kskarthik.github.io/hubpress It's loading in unlimited loop. Please help me. You have admin rights on my repo https://github.com/kskarthik/kskarthik.github.io

**Comment by anthonny** [comment]
> @anthonny since few days i am unable to login to my blog https://kskarthik.github.io/hubpress It's loading in unlimited loop. Please help me. You have admin rights on my repo https://github.com/kskarthik/kskarthik.github.io/invitations

Fixed, a typo in the name of the theme https://github.com/kskarthik/kskarthik.github.io/commit/a89413f8fc6041c3b96515bee5df89560a30e76a

**Comment by kskarthik** [comment]
Thanks a lot ! Now i remember switching themes few days ago

**Comment by kskarthik** [comment]
@anthonny  I also added two ghost themes shell & odin https://github.com/kskarthik/kskarthik.github.io/tree/master/themes I tried mapping them in theme.js but they aren't working. Should i work more on them ? Is there any guide which can help me. Please suggest.

**Comment by kskarthik** [comment]
close this issue ?

**Comment by pierreozoux** [comment]
Any advance on gitlab support? Thanks!

**Comment by jaredmorgs** [comment]
From what I could tell, it would be like a new product. Ripping out the API would be non-trivial.

Love the idea, but I don't think it's feasible.
