### ISSUE TITLE
Don't seem to be able to configure Disqus

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#413]
I have setup discus in my configuration with my user id

```
  "site": {
    "disqus": "peterlawrey"
```

 which can log in to.

https://disqus.com/by/peterlawrey/

However when I try to use trouble shooting guide it says

Disqus seems to be taking longer than usual. Reload?

I image it's configuration problem but I can't work out what.

**Comment by anthonny** [comment]
Hi @peter-lawrey,

have you create a site?

Here is a screen of a part of my config for my personal site:
<img width="1330" alt="capture d ecran 2016-07-23 a 12 20 48" src="https://cloud.githubusercontent.com/assets/2006548/17077411/5ead7eee-50d0-11e6-87c3-d939634f5570.png">

See the *shortname*, it's what i use in my hubpress configuration

**Comment by peter-lawrey** [comment]
Yes, the shortname was mine, not for a site.

Thank you again,
   Peter.
