### ISSUE TITLE
broken older and newer link in ghostium

### ISSUE THREAD

**Issue by wols** [HubPress/hubpress.io#414]
As already #350 the 'older posts' link in `ghostium` is broken:
The **repo name is missing** in renderd `/page/2/` instead of `/<repositoryName>/page/2/`.

Please fix it.

**Comment by anthonny** [comment]
Look here: 
https://demo-hubpress.github.io/blog/

After the upgrade of your hubpress instance, did you go the settings page and click on Save to force a rebuild? If not, please and tell if it's ok for you

**Comment by wols** [comment]
Updated to 0.6.0
#350 is fixed for new and edited(!) posts now :-)

But the 'Older >>' link is broken - see https://wols.github.io/time/ please.

The test post https://wols.github.io/time/2016/07/23/New-Post.html was publishd 14:38:19 UTC...
```
commit a60887ddccd8397bab20aaacd57abbfd4c34f76d
Author: wols <git@wols.org>
Date:   2016-07-23T16:38:19+02:00

    Publish 2016-07-23-New-Post.adoc
```
...but the top left corner says "17 hours ago" here?

**Comment by wols** [comment]
Sorry! Too fast! It rocks now - the links are right. THX!

The timestamp question remains open.

**Comment by jaredmorgs** [comment]
Whoops, premature closing @wols .

Updated title to capture the timestamp issue.

**Comment by alxndr** [comment]
I previously had this problem; updating to 0.6.0 has fixed it. Thanks!

**Comment by jaredmorgs** [comment]
Thanks @alxndr. Will keep the issue open for the date stamp mismatch issue @wols reported.

**Comment by anthonny** [comment]
@wols actually HubPress only consider the date that's why you see "17 hours ago".

I will open a specific issue for this problem and close this one

**Comment by anthonny** [comment]
For the timestamp see #345
