### ISSUE TITLE
[HubPress Theme] GhostDance by iacchus

### ISSUE THREAD

**Issue by iacchus** [HubPress/hubpress.io#416]
Hello, not really an issue. I a have a variation of GhostScroll/ Purple Slimerr theme for Ghost, and would like to share:

https://github.com/iacchus/ghostdance

Only the links partial is not implemented yet as I don't use it.

Demo here:

https://iacchus.github.io/

**Comment by kskarthik** [comment]
looks good !

**Comment by jaredmorgs** [comment]
Thanks for sharing it @iacchus 

Another good one for the HubPressers Theme Honour Roll, @anthonny

**Comment by anthonny** [comment]
@iacchus i have for project to build a "theme manager" where all themes will be centralized

Be sure that i will notice you when i will start to work on it.
