### ISSUE TITLE
Cannot reach my first blog essay

### ISSUE THREAD

**Issue by hitjackma** [HubPress/hubpress.io#418]
The webpage at https://hitjackma.github.io2016-07-28.adoc/ might be temporarily down or it may have moved permanently to a new web address.

My blog address is http://hitjackma.github.io
I don't know what I did wrong, please point it up, thanks:)

**Comment by anthonny** [comment]
Hi @hitjackma 

you must use the attribute **:hp-alt-title:** to specify the english version of your title 
For example:

:hp-alt-title: The decathlon

It is because i use a library to slugify the title that do not support chinese characters

**Comment by hitjackma** [comment]
Thanks a lot @anthonny , now it works.
I haven't see any content about your "must do" in README, so will you add this "MUST DO" to README, or try some other library to solve this problem?

**Comment by jaredmorgs** [comment]
This should help out other bloggers who write in languages other than images. https://hubpress.gitbooks.io/hubpress-knowledgebase/content/parameters/hp-alt-title.html

I'll add this topic into a reference topic once I get more content into the FAQ. It's a slow process joining all the docs.

**Comment by hitjackma** [comment]
Thanks, I'll try to update README-zh.adoc about alternative title
