### ISSUE TITLE
is it possible to build and be hosted on a linux vps?

### ISSUE THREAD

**Issue by luckypoem** [HubPress/hubpress.io#433]
is it possible to build and be hosted on a linux vps?

thanks.

**Comment by jaredmorgs** [comment]
Sorry @luckypoem I'm not sure.

Can you comment @anthonny ?

**Comment by anthonny** [comment]
Hi @luckypoem,

It's not possible yet sorry.

We need to create an implementation of the Github API for the endpoints that we use in HubPress.
We must also think about the storage (files, database...)
