### ISSUE TITLE
add support for static pages

### ISSUE THREAD

**Issue by rorosaurus** [HubPress/hubpress.io#438]
For example, Ghost has support for "static pages" which do not appear as blog posts, but could be a static contact/about/links page.  These are useful to provide some extra information that isn't necessarily blog-able.

This feature would go great with custom URLs (per https://github.com/HubPress/hubpress.io/issues/437)

**Comment by jaredmorgs** [comment]
I've just gone through some of the older issues relating to this and closed them out. 

However, it *may* be worth adding to the backlog for consideration. No promises about implementation, but there seems to be a demand for it.

**Comment by zemian** [comment]
It would be nice to be able to add extra custom menu item with link to other asciidoc besides blog post. A common use case is About or Disclaimer page that people would like to permanently display along in their blog site.

**Comment by jaredmorgs** [comment]
#354 relates to this.

**Comment by rorosaurus** [comment]
Added in 0.9.0!  Thanks, devs! 😃

**Comment by anthonny** [comment]
Thank you @rorosaurus for being here more than a year after the creation of that issue 👍😘
