### ISSUE TITLE
Post is not publishing

### ISSUE THREAD

**Issue by pramodjg** [HubPress/hubpress.io#444]
When I tried to publish my post I always getting the message 

> post not published. check your browser console

I tried with chrome and firefox and getting the same thing in both.

**Comment by jaredmorgs** [comment]
Can you link to your repo so @anthonny can take a look for you?

Can you save the post, but not publish it live?

Have you checked https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/problems_with_posts.html for some common causes, and related articles that might help you fix the issue?

**Comment by pramodjg** [comment]
I have checked everything specified in the link provided. All the content is showing in preview. but no luck with publishing

**Comment by anthonny** [comment]
Could you set the gh-pages as default branch of your repository an retry presse?

**Comment by pramodjg** [comment]
I tried that too.  The post is getting saved to the repo, but not publishing.

**Comment by anthonny** [comment]
I see your repository with the master setting by default:

<img width="832" alt="capture d ecran 2016-10-06 a 11 09 39" src="https://cloud.githubusercontent.com/assets/2006548/19146820/9212d7be-8bb5-11e6-8716-c956dac66c9a.png">

**Comment by pramodjg** [comment]
how to change to gh-pages by default

**Comment by anthonny** [comment]
Here: 

<img width="973" alt="capture d ecran 2016-10-06 a 11 35 01" src="https://cloud.githubusercontent.com/assets/2006548/19147570/0214cbbe-8bb9-11e6-8079-66b10d608967.png">

**Comment by pramodjg** [comment]
It worked . Thanks for your valuable time @anthonny and @jaredmorgs

**Comment by jaredmorgs** [comment]
No problem @pramodjg 

Your specific issue is not the first time we've seen this problem. Often, GitHub configuration is a primary cause of failure.

I've expanded https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/problems_with_posts.html with details, prompted by this bug. 

So thanks for prompting me to write more troubleshooting info about the issue.
