### ISSUE TITLE
The post title is too big on preview screen

### ISSUE THREAD

**Issue by zemian** [HubPress/hubpress.io#448]
Hi, When I preview my post, the title of the post is way too big and annoying. Can this be adjust/fix?

**Comment by jaredmorgs** [comment]
I noticed this as well, but wasn't particularly concerned. 

Should be pretty easy to fix.

**Comment by jaredmorgs** [comment]
H1 Headings in the preview is much more balanced in 0.7.x @zemian 

Please update to the latest version and check out the new editor.
