### ISSUE TITLE
Log in page is not loded

### ISSUE THREAD

**Issue by MingyuJeon** [HubPress/hubpress.io#449]
How can I solve this problem?
I can't even log in hubpress.

![image](https://cloud.githubusercontent.com/assets/15281293/19303675/8d21ef08-90a4-11e6-97ae-dc975c3629e3.png)

![image](https://cloud.githubusercontent.com/assets/15281293/19303697/a2e9ad4e-90a4-11e6-9922-3eeba387397b.png)

**Comment by anthonny** [comment]
Hi @MingyuJeon,

Your configuration is good, but look:
```
    "repositoryName": "mingyujeon.github.io"
```

And your repository is named **MingyuJeon**, just rename your repository to **mingyujeon.github.io** and it should be good

**Comment by anthonny** [comment]
A good practice is to keep lowercase and uppercase in names, try with this configuration:
```json
{
  "meta": {
    "username": "MingyuJeon",
    "repositoryName": "MingyuJeon.github.io",
    "branch": "master"
  },
  "theme": {
    "name": "Casper"
  }
}
```

**Comment by MingyuJeon** [comment]
@anthonny Thank you for the fast reply! 👍

**Comment by jaredmorgs** [comment]
What about the title case of the theme name, @anthonny. Needs to be
lowercase "casper", correct?

See
https://hubpress.gitbooks.io/hubpress-knowledgebase/content/fields/about_themes.html


-- 

Sent from Mobile.
