### ISSUE TITLE
Config.json Default values

### ISSUE THREAD

**Issue by anthonny** [HubPress/hubpress.io#46]
Add a message on the login screen if config.json contains default values

**Comment by jaredmorgs** [comment]
Is this still necessary for a good user experience @anthonny ?

Is this issue difficult or easy to implement?

If it is easy, I propose the following microcopy:

"Default config.json values detected. You must customise the information in the config.json file before HubPress will load the Admin console. See the README.adoc file for further instructions."

**Comment by jaredmorgs** [comment]
Keep or close, @anthonny ?

**Comment by anthonny** [comment]
Keep, it is totally possible to do and it is a good improvement for the UX

**Comment by anthonny** [comment]
Done in the 0.8.0 with the configuration form
