### ISSUE TITLE
Cannot update post - 422 Invalid Request

### ISSUE THREAD

**Issue by pdudits** [HubPress/hubpress.io#463]
Hello,

Upon attempt to save or publish my the post after I initially saved it,  I get _Post not saved, see your browser console_.

The console says

````
{
  "message": "Invalid request.\n\n\"sha\" wasn't supplied.",
  "documentation_url": "https://developer.github.com/v3/repos/contents/"
}
````

A previous version is already existing in the gh_pages branch, but cannot be updated.

**Comment by anthonny** [comment]
Hi @pdudits,

In the settings of your repository, you must set the branch `gh-pages` as the **default branch**.

**Comment by pdudits** [comment]
Oh yes, should've paid more attention to Readme file. 

Thanks!
