### ISSUE TITLE
Cant log in to admin

### ISSUE THREAD

**Issue by robsd** [HubPress/hubpress.io#471]
I enter my GitHub credentials into http://robsd.github.com/hubpress and clicked "Login" but nothing happens

**Comment by jaredmorgs** [comment]
Sorry for the delay @robsd 

Are you still experiencing this issue? 

Have you checked to ensure you have the correct repository branch configured, and your config.json is correct per the README?

One of the most common things blocking login is initial misconfiguration of the branch and the json.

In the Readme for 0.7.0 I've done some major rework of the initial configuration instructions so folks should have a better "first run" experience.

**Comment by anthonny** [comment]
@robsd if you are interested to give a new try to HubPress, feel free to make a new fork and i will do my best to answer faster.

**Comment by jaredmorgs** [comment]
@robsd sorry for the trouble you experienced. 

I'll close this ticket off, but do open another one if you still have the issue after updating to 0.7.1 or later.
