### ISSUE TITLE
Configuring hubpress correctly

### ISSUE THREAD

**Issue by sadeg** [HubPress/hubpress.io#472]
I forked hubpress on https://github.com/sadeg/mirror and while trying to log in as admin loading process last forever! (I read submitted login issues by others but couldn't find a solution for my problem)
I would be grateful if sb take a look at my config.json and help me to find the problem.

**Comment by anthonny** [comment]
Hi @sadeg,
if you want to use the master branch you need to rename your repository to `sadeg.github.io` and change your config file to match with the new name of your repository

**Comment by sadeg** [comment]
I changed pages source to gh-pages branch and it works fine now, thanks.
