### ISSUE TITLE
Login panel loading problem

### ISSUE THREAD

**Issue by akoskovacsblog** [HubPress/hubpress.io#473]
Hello,

I forked and setted the repository, but login screen isn't loading. Here is the blog: https://akoskovacsblog.github.io/hubpress/#/login

**Comment by jaredmorgs** [comment]
It's working for me now in Chrome. Try again and if it's working please
close off this issue.

> [image: Screen Shot 2017-01-09 at 9.15.18 am.png]
-- 

Sent from Mobile.

**Comment by akoskovacsblog** [comment]
Yes, I see login form with use of Chrome, but can't login with my Github credentials.

**Comment by anthonny** [comment]
Hi,

Your username is akoskovacsblog, not akos.
Fix your config.json and it should work

**Comment by akoskovacsblog** [comment]
Thank you, it is ok at this time!
