### ISSUE TITLE
Error with http request (and not https) for included stylesheet

### ISSUE THREAD

**Issue by javathought** [HubPress/hubpress.io#475]
I use Uno theme

`Mixed Content: The page at 'https://<username>.github.io/#blog' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Raleway:400,700|Roboto+Slab:300,400)'. This request has been blocked; the content must be served over HTTPS.`

hubpress version : release 0.6.0

**Comment by jaredmorgs** [comment]
Are you still experiencing this issue @javathought ?

0.7.0 has been soft-launched, so you might want to try updating and seeing if the problem persists.

**Comment by anthonny** [comment]
See https://github.com/HubPress/hubpress.io/pull/427

**Comment by anthonny** [comment]
I propose to add this issue to the next version @jaredmorgs

**Comment by anthonny** [comment]
I have released the 0.7.1, the problem should be fixed.
@javathought could you take a minute to test and confirm?

**Comment by javathought** [comment]
Hi,

I've tested on 0.7.1and reproduced the error : 
https://javathought.github.io/2016/12/12/Heroku-Memo-for-postgresql.html 

`Mixed Content: The page at 'https://javathought.github.io/2016/12/12/Heroku-Memo-for-postgresql.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Raleway:400,700|Roboto+Slab:300,400)'. This request has been blocked; the content must be served over HTTPS.`

**Comment by anthonny** [comment]
Hi @javathought 
Do you have regenerated your content?

If not, go in the Settings panel and Save, it will generate all your content

**Comment by anthonny** [comment]
My bad...
I have omitted to report themes during the release...
Welcome 0.7.3

**Comment by javathought** [comment]
No problem, 
It can happen.

**Comment by anthonny** [comment]
0.7.2 is here @javathought 
If you have a minute to test ;)

**Comment by javathought** [comment]
Tested and ok 👍

**Comment by anthonny** [comment]
😎
