### ISSUE TITLE
Unable to login on Chrome - error 401

### ISSUE THREAD

**Issue by javathought** [HubPress/hubpress.io#476]
Error 401 Unauthorized on request https://api.github.com/repos/<username>/javathought.github.io?

hubpress version : release 0.6.0

**Comment by javathought** [comment]
The issue was with chrome. My login to others sites were broken too. 

Removed my chrome profile and then recreated it.

**Comment by anthonny** [comment]
ok but you repo is not in 0.6.0, it is in 0.3.0
https://github.com/javathought/javathought.github.io/blob/master/hubpress/index.html#L30

**Comment by javathought** [comment]
I pulled directly on gh-pages : 
https://github.com/javathought/javathought.github.io/blob/gh-pages/hubpress/index.html#L47 

bad method ?

**Comment by anthonny** [comment]
you must upgrade the master, not the gh-pages ;)

**Comment by anthonny** [comment]
And it's strange, it seems that the branch gh-pages is now the default branch of your repo. You must set the master as default branch

**Comment by javathought** [comment]
ok, some confusion with config of pages of another repo. I didn't rebase this one for a while and mixed usages.
