### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by thomaszahr** [HubPress/hubpress.io#477]
Hi,

I have tried to include an image into a blog post:

---

= ... baking bread

:hp-tags: bread

== Recipe 1:

* 1000 g flour (wheat or spelt)
* 60% - 65% water (60% with spelt)
* 2% salt
* yeast

Knead, proof over night, pre-heat oven (incl. baking stone) and a cast iron pot with lid (Dutch oven) to 265 C or the maximum temperature of you oven.

Form the loaf and proof (on a sheet of baking parchment) until well risen.

Move loaf with the parchment into the pre-heated pot, return to the oven, turn down the oven to 250 C and bake for 1 hour.

image::https://goo.gl/photos/Y3Me5nvBQ9xfdHsp9[Fresh Loaf]

---

![bild1](https://cloud.githubusercontent.com/assets/12052558/22933687/ae9cc754-f2cc-11e6-925f-ba00935e4828.png)

As you see, the image does not render. Where did I go wrong?

**Comment by anthonny** [comment]
Hi @thomaszahr 

The url point on a google page, not on  an image file.
Could you try with this url https://lh3.googleusercontent.com/vn3bs-PMEBTTnDjQdQl_rN655mNtUZtoabAGbNqiB_U3qqx1irQ02nLiz3Anbl4RXgHOTsgqcny_OYZTXQ5SRaG2KWTbuJxZSd0wuU5-hWP3CmcZ77t-Qkjmz9N4glnK69clapk=w716-h954-no ?

**Comment by thomaszahr** [comment]
thanks, that was it.

**Comment by anthonny** [comment]
🎉🎉
