### ISSUE TITLE
Kept getting 409 errors when saving things.

### ISSUE THREAD

**Issue by jsiu22** [HubPress/hubpress.io#479]
Got a lot of 409 errors when it performed GET actions (these were console errors).
This occurs when I tried to save posts (which eventually started working but remains buggy, it only works half the time).
However the main issue is saving settings (never worked for me).

**Comment by anthonny** [comment]
Hi @jsiu22,

You must set the gh-pages as the default branch of your repository in the settings of it

**Comment by jsiu22** [comment]
@anthonny Thank's for the speedy response, I will give it a try when I can and get back to this thread!

**Comment by jsiu22** [comment]
That was perfect, thank you!

**Comment by anthonny** [comment]
Perfect 🎉🎉
