### ISSUE TITLE
Change admin URL

### ISSUE THREAD

**Issue by sebie** [HubPress/hubpress.io#48]
> Tags relevant: `enhancement`, `minor`

----

The title explains this well, but if it was possible to change the admin URL it might prevent Hubpress users from *some* attacks, which would use the default `/hubpress` URL.

**Comment by mvisonneau** [comment]
Is it really useful since it use Github authentification methods ?

**Comment by sebie** [comment]
I would say it is. Regardless if you have 2FA or just a password, whilst using HubPress everyone will know where they can try to login.

**Comment by anthonny** [comment]
Hi @sebie,
Hubpress is open source, change the url will bring nothing more, it's easy to find the path by reading code.

wdyt ?

**Comment by jaredmorgs** [comment]
I tend to agree, for the reasons @mvisonneau cited. Proposing wonfix close @HubPress/contributors ?

**Comment by sebie** [comment]
Tbh, I do not mind if this gets implemented or not, it was only a suggestion. Personally, I tried HubPress, but didn’t continue with it because: it has a backend and because it didn’t work through a proxy (at-least I think that was the problem).


Anyhow good luck with it. And feel free to close this.


~Sebie

**Comment by jaredmorgs** [comment]
Thanks for your feedback @sebie , and thanks for giving HubPress a go.
