### ISSUE TITLE
Problem to show all content of a blog post

### ISSUE THREAD

**Issue by jabby** [HubPress/hubpress.io#483]
Hubpress Version : 0.7.0
Firefox Version : 52.0b9

I tried a little the new version of Hubpress. Thanks for the work. It's a shiny version.

I have some problems to read all content of a blog post. As you can see in attached screenshots, If I use the keyboard arrow to go at the end of the post, I can't see the last line entirely. 

Second problem is about the top of the blog post. If I go to the bottom then I can't see the top except if I use keyboard arrows to go up. It's not very handy.

![hubpress-v0 7 0-missing-top](https://cloud.githubusercontent.com/assets/1883932/23383090/14465ac0-fd45-11e6-8456-5f96a3f2f8ec.png)
![hubpress-v0 7 0-missing-top-after-go-to-bottom-and-use-slider-to-go-up](https://cloud.githubusercontent.com/assets/1883932/23383091/144993fc-fd45-11e6-9aee-a5194c9fa722.png)
![hubpress-v0 7 0-missing-bottom](https://cloud.githubusercontent.com/assets/1883932/23383092/144b8dec-fd45-11e6-8df9-c2babb0cdcce.png)

**Comment by jaredmorgs** [comment]
G'day @jabby and thanks for the report. @anthonny and I are also working through some other issues which I'll convert into public bugs today (at work at the moment) for transparency.

**Comment by anthonny** [comment]
@jabby the 0.7.1 is out, could you upgrade and try please?

**Comment by jabby** [comment]
@anthonny It's better but there is still an issue. It's not a blocking one just a little bit annoying.

The scrollbar is now OK but the bottom of the last line is not display.

**Comment by anthonny** [comment]
Could you give me a screenshot?
Because i cannot reproduce on OSX with FF 52.0b9

**Comment by jabby** [comment]
OS : Windows 10 
Screenshot here : [link to the screenshot](https://framapic.org/V2tfzheY7ovJ/hfgKVo0ROwoh.PNG)

**Comment by anthonny** [comment]
Could you upgrade your version of FF to 53.b01?

Here is the result for me:

![image](https://cloud.githubusercontent.com/assets/2006548/23822522/85efb0ba-064e-11e7-8cea-62df256c372a.png)

**Comment by jabby** [comment]
I upgraded but there is still the problem. 

Thanks for your time :-)

**Comment by anthonny** [comment]
Ok i reproduce with  your content, i'll investigate
