### ISSUE TITLE
ld+json is null

### ISSUE THREAD

**Issue by davidthewatson** [HubPress/hubpress.io#488]
I have 9 posts (all of them) with null ld+json data:

    <script type="application/ld+json">
    null
    </script>

I just upgraded to version 0.7.0.

**Comment by jaredmorgs** [comment]
Thanks for reporting David. 

I'll add this to the next milestone for investigation by @anthonny

**Comment by davidthewatson** [comment]
np @jaredmorgs 

I'm not sure when this started but I believe it was working at one point as I noticed that my SEO rankings dropped off significantly when it broke.

**Comment by jaredmorgs** [comment]
Interesting. I can't say I pay a lot of attention to my rankings, but I'm sure you're not the only one who would be affected by this.

So thanks for identifying it.

**Comment by anthonny** [comment]
@davidthewatson thank you 👍 
I'll check that for the next release

**Comment by anthonny** [comment]
@davidthewatson it will be fixed in the next version, a bugfix version of the 0.7.0

**Comment by anthonny** [comment]
@davidthewatson the 0.7.1 is out, could you upgrade and save your settings to force a generation of all your posts? Then could you check that the ld+json is correctly filled please?

**Comment by davidthewatson** [comment]
@anthonny I installed this evening and indeed, all the ld+json is properly populated!

Thanks!
