### ISSUE TITLE
rss feed

### ISSUE THREAD

**Issue by naveensrinivasan** [HubPress/hubpress.io#49]
How do we setup the rss feed for the blog? I didn't see it in the documentation or the settings. Could it be set to feedburner?

Thanks

**Comment by KamesCG** [comment]
It's not currently setup.

**Comment by cmosetick** [comment]
I propose that the huge RSS badge be removed from the default theme, if it's just going to error 404. Currently it's just a broken link.

**Comment by naveensrinivasan** [comment]
I agree to @cmosetick  If it isn't implemented it should be removed!

**Comment by elfrasco** [comment]
Like @naveensrinivasan, I agree to @cmosetick too. The RSS badge should be removed from the default theme.

**Comment by anthonny** [comment]
rss badge has been removed from all themes, i'll work on RSS asap

**Comment by elfrasco** [comment]
Thank you, @anthonny!!

**Comment by anthonny** [comment]
@elfrasco you're welcome!

**Comment by jabby** [comment]
:+1:

**Comment by alvarosanchez** [comment]
Until RSS support is officially added, I recommend using http://feed43.com/ to "externally" generate an RSS feed. I have tried and it works so far :)

**Comment by alvarosanchez** [comment]
Another alternative: http://alvarosanchez.github.io/2015/05/05/Generating-an-RSS-feed-for-HubPressio.html

**Comment by mubix** [comment]
No one has posted their method for extracting the RSS info using Feed43 yet, so here is my filters:

Here is my global filter:
```
<main class="content" role="main">{%}</main>
```

And here is my Item Search Pattern filter:
```
<article class="post tag{*}">{_}<header class="post-header">{_}<span class="post-meta"><time datetime="{*}">{*}</time>{*}</span>{_}<h2 class="post-title"><a href="{%}">{%}</a></h2>{_}</header>{_}<section class="post-excerpt">{_}<p>{%}</p>{_}
```

**Comment by benavern** [comment]
Hey! I'd like to know if integrating a rss feed is still on the roadmap. 
In fact I am trying ionic framework these days and was saying myself that making an app that can display a feed of my blog would be nice, and that is what misses ...

**Comment by anthonny** [comment]
Yes it's still in the road map.
I had a lot of rework on the technical stack of HubPress, now it's better and i'm pretty sure that it will be easier to work on new functionnality

**Comment by cbeams** [comment]
Looking forward to this @anthonny, thanks.

**Comment by anthonny** [comment]
The 0.6.0 is here and RSS too.
I close this issue, feel free to open a new one if you have problem or bugs with RSS
