### ISSUE TITLE
Any dark themes for Hubpress?

### ISSUE THREAD

**Issue by Shurikan117** [HubPress/hubpress.io#497]
I noticed a distinct lack of darker themes in the repo. Would you consider adding any in the future?

**Comment by anthonny** [comment]
Hi @Shurikan117 thank you for giving a try to HubPress!

Actually it is not planned but if you find a ghost theme that you like and you would love to see in HubPress, we could add it.

**Comment by anthonny** [comment]
I will work on this one https://github.com/mityalebedev/The-Shell, right? 😄

**Comment by Shurikan117** [comment]
Nice! Thanks for the quick reply!

**Comment by anthonny** [comment]
If you want to make some tests on casper, you should duplicate the casper folder in something like my-casper and work on this copy.

I say that because if you change casper you will have possible conflicts when you will upgrade your fork

**Comment by anthonny** [comment]
The dark theme is here @Shurikan117 http://blog.hubpress.io/2017/03/23/Update-Whats-New-in-Version-080.html
