### ISSUE TITLE
Custom Domain & Netlify

### ISSUE THREAD

**Issue by greatwarlive** [HubPress/hubpress.io#498]
Is it possible to set Github Pages Hubpress up with a custom domain on Netlify.

Netlify is a static constant host for projects on Github Pages.

**Comment by enjikaka** [comment]
Hi @greatwarlive 

If you just follow the HubPress steps like you would for a normal setup with GH pages, you should then be good to go setting it up in Netlify without any further modification!

Just create a new site in Netlify and choose your repo with HubPress, use the gh-pages branch as "Branch to deploy" and continue. I just tried this on enjikaka.github.io and set up this site with Netlify; http://choreographer-eagle-74080.netlify.com/

Did you not succeed with this? :)

**Comment by greatwarlive** [comment]
Hi @enjikaka 

Thank you for your support. My blog is available at https://greatwarlive.netlify.com

There is only one problem, everytime I click on a post it goes to a .github.io domain. How do you sort this?

**Comment by anthonny** [comment]
@greatwarlive in the settings of your HubPress instance, you have to set the `CNAME` to `greatwarlive.netlify.com`

**Comment by greatwarlive** [comment]
Thank you @anthonny 

Is there anyway that you can add sitemaps to submit to Google? Brilliant work - keep it up!

**Comment by anthonny** [comment]
Not yet like i said here https://github.com/HubPress/hubpress.io/issues/493
But it will, i can't say when

Thank you for your kind words ❤️

**Comment by anthonny** [comment]
I think we can close this issue, right?

Thank you so much for you tests, @greatwarlive and @enjikaka, now i can explain how to use Netlify with HubPress 👍

**Comment by anthonny** [comment]
I think we can close this issue, right?

https://www.youtube.com/watch?v=mLPklM1w5-s
