### ISSUE TITLE
Prevent index.html of Blog from Refreshing

### ISSUE THREAD

**Issue by Shurikan117** [HubPress/hubpress.io#499]
So i thought about adding a few lines of code to my index.html to spruce things up a little. It turns out however, once i went to my /hubpress admin area and updated a few settings my index.html reverted to back to normal (without my additional code). I tried this several times and found it quite vexing to restore whatever i typed in earlier everytime i changed something. 

Is there a way to fix it so that Hubpress updates the index.html as is instead of reverting it back to normal?

**Comment by anthonny** [comment]
Hi @Shurikan117,
The only way to update the index.html generated is to update the template file default.hbs of your theme.
To avoid merge conflicts during futur upgrade of your fork, duplicate your theme `casper` in something like `my-casper`. 
Modify the file `default.hbs` of this copy as you want
Then go in the Settings of your HubPress instance and set the theme to `my-casper`
Save and it will rebuild your site using your new theme

**Comment by Shurikan117** [comment]
@anthonny thanks! I'll look into it! ❤
