### ISSUE TITLE
[Android] [Chrome] Can't open HubPress UI

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#5]
I already had a GitHub Pages Markdown blog set up at http://jaredmorgs.github.io so I was able to access the auth page by declarding the name of the repo fork as described in the instructions.

But all I get is the spinning Circle.

http://jaredmorgs.github.io/blog/hubpress/#/login

Am I missing some config settings? Or is the issue here that I have content already at the GitHub Pages Root?

**Comment by anthonny** [comment]
You need to work on the gh-pages and follow https://github.com/jaredmorgs/blog/blob/master/README.adoc#use-a-custom-domain

I think i should rename this section to : 
Use a Custom Domain or username.github.io alredy use.

You are not the first in that situation, i need to improve my docs

**Comment by jaredmorgs** [comment]
I can help. Did you see my pull request?

**Comment by jaredmorgs** [comment]
Just fixed the issues with a slight rewrite. Hope it helps.

**Comment by jaredmorgs** [comment]
Issues in instructions are resolved. I was able to access the console.
