### ISSUE TITLE
When saving or publish I get "Error: 422 error making request POST … "Unprocessable Entity"  vendor.e2e21d9c993fa4b677a1.js:96:11726"

### ISSUE THREAD

**Issue by miroque** [HubPress/hubpress.io#505]
So, I making new Article(post) and want to save or publish, I get this error:

`Error: 422 error making request POST https://api.github.com/repos/miroque/myblog/git/trees: "Unprocessable Entity"  vendor.e2e21d9c993fa4b677a1.js:96:11726`

What I do wrong? Or It's a bug?

**Comment by InformatiQ** [comment]
I am getting the same

**Comment by InformatiQ** [comment]
#496 
refresh the posts fixes the issue

**Comment by InformatiQ** [comment]
I would say this is duplicate to #496

**Comment by miroque** [comment]
Yep it's duplicate to #496

> refresh the posts fixes the issue

In my case: refresh or synchronization not  fixes issue at all

It works only once, when I create new Post and save. Next I edit this Post, and I get this error "Error: 422..."

**Comment by anthonny** [comment]
Hi here, the 0.8.1 is out, could you upgrade your instance and tell me if now everything is ok please?

**Comment by miroque** [comment]
@anthonny You are my hero!
It's gone! The problem has gone!
At last my thoughts can fly freely! Yippee

**Comment by anthonny** [comment]
I apologise, i took so much to fix that. Thank you so much for having been so patient 👍

**Comment by miroque** [comment]
You know, I've found situation when I get again this error 422.

in this situation: 
when I using special symbols like this one « »

`== «My very special Topic»`

and again I see this 422. (it saves but not publish)

When I deleted this symbols, all started publishing.

I don't know reopen this issue or create new, or just not using this symbols :)

**Comment by anthonny** [comment]
Symbols are not the cause, delete is...
The problem is the cache of the browser, so i have to store the sha1 of the last commit i made to be sure that the next commit will be make on the HEAD and not on a old sha1
And i do not store the sha1 in the delete workflow

I will fix that asap (maybe at lunch)

**Comment by miroque** [comment]
Also, just now I tested more. 
Also it not work when I use Non Latin characters in Main Topic - Page Title. It works and not works.
Now I test with :hp-alt-title: 
````
= Шустрая IDE
:hp-tags: черновик
:hp-alt-title: Speedy IDE  <--- this may be help?
````

Thanks for your work! 

still testing...

**Comment by anthonny** [comment]
Yes Non latin character are not supported, that's why there is the `hp-alt-title` you are right.
It is because of the library that i use to slugify the title. I have to work on it but it is not really a problem since there is a workaround with the `hp-alt-title` attribute

**Comment by miroque** [comment]
Thanks for clarifying!

Now I trying clear my this post, and redone in new with this info

**Comment by miroque** [comment]
Damn, it not work not with help-tags and not with new post with Latin in Topic ))))
maybe I using FireFox, and it cashes in deeps this js

I try in another browser. But later, not today.

**Comment by anthonny** [comment]
Same problem for `hp-tags` and actually there is not alternative sorry.
For the title, this must work
```adoc
= Шустрая IDE
:hp-tags: черновик
:hp-alt-title: Speedy IDE
```
