### ISSUE TITLE
Constantly Publishes

### ISSUE THREAD

**Issue by rrenode** [HubPress/hubpress.io#513]
So I wrote up a blog post over the past few days and when I go to Publish, it loads forever with no success or "True Failure"(as in no error code). I've tried several time to Publish the post. Even left it for an hour to see if it was just going super slow. It's not lol. 

Anyway... it's on this repo: https://github.com/rrenode/blog

Thanks in advance!

It's stuck with this loading icon.
![captur3e](https://user-images.githubusercontent.com/13337715/29052709-c65ce538-7bb9-11e7-9360-5b3e8b7ddbc3.PNG)

**Comment by rrenode** [comment]
Found this error with using Google Dev Tools in the console:

![image](https://user-images.githubusercontent.com/13337715/29052670-8b0dca10-7bb9-11e7-8b5b-9ba125bf14ee.png)

![image](https://user-images.githubusercontent.com/13337715/29052691-b31d557a-7bb9-11e7-9db2-e09fe9865298.png)

**Comment by miroque** [comment]
welcome aboard to all who suffer from this mistake.
your issue repeats #505 and #496 
I also don't know what to do...

**Comment by rrenode** [comment]
Lol thank you. I've been doing some looking into the files. Now that I have more issues, I'll try to compare them see if I can solve it with some help.

**Comment by rrenode** [comment]
Currently, a good work around is to hard refresh the page.

**Comment by anthonny** [comment]
Hi here,

I'm trying to reproduce but actually it's a real random issue.
Do you reproduce this error each time you try to publish?
Have you identified a process to reproduce the issue?

I really try to reproduce https://github.com/demo-hubpress/demo-hubpress.github.io/tree/master/_posts

**Comment by rrenode** [comment]
It seems to be that after I change a setting it acts up. 

When I attempt to change a setting, whether it be my blog's description, title, theme etc, after clicking save for the settings it constantly loads. I  usually wait at least 10 seconds and then I refresh the page and the setting has changed. After attempting to publish a post or do anything, it now does the infinite publish. 

P.S. Sorry if this is a bit hard to understand, I'm writing this at 3:48 am.

**Comment by anthonny** [comment]
Bugfix is coming 👍

**Comment by rrenode** [comment]
Looking forward to it!

**Comment by rrenode** [comment]
Also if you care. It seems that the problem does not occur in Incognito Windows. It hasn't replicated yet in Incognito, but in normal windows it replicates constantly.

**Comment by miroque** [comment]
Totally the same with me like rrenode have wrote. Any changes in title, tag, anything else. Then it's impossible to save or publish. Although save works sometimes after refreshing. But publishing never.
I'm using non English letters (Cyrillic letters) maybe this also corresponding to this error? I don't know...
Bug fix would be great!

**Comment by anthonny** [comment]
Hi here, the 0.8.1 is out, could you upgrade your instance and tell me if now everything is ok please?

**Comment by peter-lawrey** [comment]
I have 0.8.1 latest and I see the same behaviour. The error I get is

```
Repository.js:922 Uncaught (in promise) TypeError: Cannot read property 'sha' of null
    at Repository.js:922
    at <anonymous>
```
