### ISSUE TITLE
Can't edit posts

### ISSUE THREAD

**Issue by kunicmarko20** [HubPress/hubpress.io#514]
If I try to edit a post I get a console error:

![screenshot at aug 11 08-48-24](https://user-images.githubusercontent.com/13528674/29203604-63697462-7e72-11e7-8c73-225b8a3a3477.png)

also, all my posts are now duplicated in admin panel and on frontend.

**Comment by anthonny** [comment]
Hi @kunicmarko20 
I think you can fix with a synchronize in the posts list.

Do you have this error for each post you create?

**Comment by kunicmarko20** [comment]
Hi @anthonny,

I can create post normally but if I synchronize my list it gets duplicated. 
That error occurs only for editing. I deleted posts and added them again and now they are not duplicated on frontend but I still get that error and they are duplicated in the admin panel.

**Comment by anthonny** [comment]
Ok i have a workaround to clean your list

1- Be sure that you have saved all your drafts
2- Open the dev tools on your HubPress page and in the console write that:
```
new PouchDB('hubpress-kunicmarko20-kunicmarko20.github.io').destroy().then(function(){console.log('destroyed')})
```
3- Refresh your tab / page
4- Sync your content

Then it should be cool

**Comment by anthonny** [comment]
Hi here, the 0.8.1 is out, could you upgrade your instance and tell me if now everything is ok please?

**Comment by kunicmarko20** [comment]
Works great now, thank you!
