### ISSUE TITLE
CSS wont load when using https (problem for users who use HTTPS-Everywhere)

### ISSUE THREAD

**Issue by Rixecker** [HubPress/hubpress.io#52]
Hey,

if you access a hubpress-blog via https://username.github.io Chrome and Firefox wont load the CSS (it looks like Safari doesn't care). This could be a problem for users who use the HTTPS-Everywhere extension because it automatically forces HTTPS when available.

**Comment by senola** [comment]
I also encountered this problem !

**Comment by anthonny** [comment]
it should be fixed with https://github.com/HubPress/hubpress.io/pull/44

**Comment by anthonny** [comment]
Finally it's not the same problem, i'll work on it asap

**Comment by anthonny** [comment]
@Rixecker, @senola can you merge the upstream, https should work now.
Can you give it a try and if it's ok, close the issue?

**Comment by anthonny** [comment]
I close, if you still have problem with https, feel free to reopen

**Comment by natsu90** [comment]
I have same problem but different case. I've setup hubpress as github page with custom domain and ssl from cloudflare. But I have github user page with another custom domain but no ssl. Although hubpress is pointing to `https://username.github.io/hubpress.io/themes/*` but the url redirect to the custom domain with no ssl. Check out `https://namial.us`.

**Comment by natsu90** [comment]
NVM. It's fixed after I fetched latest commit and click `Submit` in Hubpress admin. Thanks.
