### ISSUE TITLE
Force push causes having articles published twice

### ISSUE THREAD

**Issue by ochaloup** [HubPress/hubpress.io#528]
Hi,

I would like to ask for advice. By accident, I forced push to the gh-page branch of my blog page and it causes all the posts are doubled (they are published twice). When I did the force push it happens two instances of the same article being shown in the /hubpress/#/posts management gui and when I created a new post all articles are double published in html too.

Is there some way how to redo such double publish behaviour?

Thank you in advance
Ondra

**Comment by anthonny** [comment]
Hi @ochaloup,

You can sync your content in the posts page with:
![image](https://user-images.githubusercontent.com/2006548/34107765-ad373124-e3fd-11e7-9f8e-7ced2d0a7390.png)

Then go in your settings and click on save, it should regenerate all your published content

**Comment by ochaloup** [comment]
Yay, it works for me! Many thanks for the solution.
