### ISSUE TITLE
Add support for pages

### ISSUE THREAD

**Issue by adrianhopebailie** [HubPress/hubpress.io#53]
It would be great if HubPress supported static pages. This would make it ideal for hosting project pages on GitHub

**Comment by nbband** [comment]
+1 for support for "Pages" (as opposed to "Posts") since you are using Ghost themes

**Comment by metasean** [comment]
:+1:

**Comment by mubix** [comment]
+1

**Comment by jaredmorgs** [comment]
Interestingly, this dovetails quite well into the RFE I created about changing the readme into a full user guide. Check #153 and see what you all think.

 @nbband I'd be interested in hearing more about the capabilities you believe are possible with Ghost themes for static pages. You're talking about using HubPress more like WordPress, right. 

I'm approaching it from a docs perspective, and I can see HubPress being a perfect static docs hub as well if it could traverse a root document node and honor include statements.

**Comment by carc1n0gen** [comment]
Has this gone anywhere?  I recently found HubPress, and it works great.  I wanted to migrate my blog to it, but my blog is also my personal website. I would need the ability to create one or two other static pages.

**Comment by jaredmorgs** [comment]
Unfortunately @anthonny has not had a chance to make any progress on this. 

I agree that HubPress as a static site maintenance tool would be great. But if this was going to happen, it would need to be a fork, and not part of HubPress proper.

**Comment by jaredmorgs** [comment]
It's tempting to leave this issue open, because I'd love to see HubPress also support static page (non-blog post) generation. 

Based on the fact that stand-alone static page generation is not a core function of HubPress, and the age of this request, I'm officially closing off this request.
