### ISSUE TITLE
Adding a ghost theme...

### ISSUE THREAD

**Issue by taosx** [HubPress/hubpress.io#55]
I'm wondering how you implement a Ghost theme in hubpress. I chose a theme: "[Casper](https://github.com/haydenbleasel/ghost-themes/tree/cactus)", download it, unzip it and then I put it in the folder: /yourblog.github.io/themes/Cactus/. Next I tried to apply it from the hubpress admin panel but It wasn't replacing my current theme which is casper with cactus, I looked in the console and saw a 404 error at theme.json, I created a theme.json file for the new theme (cactus).Next I saw again a 404 error to partials/loop.hbs so I removed it. Now I am at this stage:

/yourblog.io/themes/Casper/theme.json
```javascript
{
  "files": {
    "comments": "partials/comments.hbs",
    "excerpts": "partials/excerpts.hbs",
    "index-meta": "partials/index-meta.hbs",
    "post-meta": "partials/post-meta.hbs",
    "share": "partials/share.hbs",
    "default": "default.hbs",
    "index": "index.hbs",
    "author": "author.hbs",
    "post": "post.hbs",
    "page": "page.hbs",
    "tag": "tag.hbs"
  },
  "version":"1.0.0"
}
}
```

But hubpress isn't applying it cause:
![Error](http://i.imgur.com/nVw0hhT.png)

Can someone translate to me what this error means?

**Comment by anthonny** [comment]
> "Missing helper: 'contentFor'

HubPress is not full compatible yet :cry: 
In your `default.hbs`, you can comment or remove : 
```
{{{block "meta"}}}
```

**Comment by samanx** [comment]
Nope, still not working, same error. It's ok that's not fully compatible with ghost themes, but what is error contentFor mean.

**Comment by anthonny** [comment]
`contentFor` is an helper exposed by express-hbs see http://dev.ghost.org/ghost-theme-tips-defining-content-blocks/

And contentFor is not implemented in HubPress, that's why you have this error.

**Comment by anthonny** [comment]
Ok, i find a way, but you will loose some meta tag. If SEO is not really important for you, it should not be a problem.

1. Remove index-meta and post-meta from the theme.json
2. Edit post.hbs and page.hbs, comment or remove >post-meta

Relog in hubpress, it should work

**Comment by anthonny** [comment]
Is it ok for you @taosx? can i close ?

**Comment by taosx** [comment]
Yes

**Comment by jaredmorgs** [comment]
added this edge case to https://hubpress.gitbooks.io/hubpress-knowledgebase/content/theme/develop_themes.html
