### ISSUE TITLE
Themes not fully compatible

### ISSUE THREAD

**Issue by guillaumevidal** [HubPress/hubpress.io#56]
The post pages generated from the .adoc files are not really compatible with the Ghost themes.
The uno theme in particular is completely broken: I only get a full screen cover image with the title, with no links to the posts (Chrome 40).

I guess this comes from using themes from Ghost that expect markdown-generated html ?
Not sure if this is really an issue for hubpress to fix, but if it could somehow be completely compatible with the Ghost themes, that would be awesome

Related: Would it be possible to have a theme that renders post just like the editor preview? It looks great !

**Comment by anthonny** [comment]
Hi @guillaumevidal !

Not sure Uno is broken, i use in on my personal blog : http://anthonnyquerouil.fr
You have a link *blog*, you click on this link and the cover slide on the left.

**Comment by guillaumevidal** [comment]
This doesn't work for me: [http://guillaumevidal.github.io/blog/](my blog on uno.

Probably because i'm not using hubpress on my base xxx.github.io repo, maybe something to do in the conf of the theme?

**Comment by anthonny** [comment]
:+1: but it's clearly a bug :cry: 
You can edit `partials/side-panel.hbs` and change `/blog` by `{{@blog.url}}/blog`

**Comment by guillaumevidal** [comment]
I tried that, it doesn't seem to work... 
Also, i'm not so sure that it works for you either, clicking the button shows the post list, but clicking on a post title to see it in full is a [404](http://anthonnyquerouil.fr/2015/02/03/test-wo-CNAME.html) for me :stuck_out_tongue:

**Comment by anthonny** [comment]
You must relog to reload theme files.

M'y blog seems to be a dev sandbox :)

Le mer. 11 févr. 2015 16:39, Guillaume Vidal <notifications@github.com> a
écrit :

**Comment by guillaumevidal** [comment]
Logged out and back in, same thing

**Comment by anthonny** [comment]
Ok i'll have look tonight

Le mer. 11 févr. 2015 16:58, Guillaume Vidal <notifications@github.com> a
écrit :

**Comment by anthonny** [comment]
Worked for me, with my demo-hubpress account : 
http://demo-hubpress.github.io/blog

Can you try to clear your cache, then login ?

**Comment by guillaumevidal** [comment]
Figured it out, I forgot the @ and placed the handlebar inside the quotes (I know nothing about javascript. Thanks for the help!

**Comment by demo-hubpress** [comment]
Thanks to you,  i know there is à bug in this theme

**Comment by anthonny** [comment]
:beers: 
Thanks to you i know there is a bug in the theme

**Comment by anthonny** [comment]
@guillaumevidal this bug is now fixed, can i close the issue?

**Comment by guillaumevidal** [comment]
Sure.
