### ISSUE TITLE
[Bug] Google Analytics not installed

### ISSUE THREAD

**Issue by RobertGiff** [HubPress/hubpress.io#63]
Checking the index.html shows the script code at the bottom of the file. However according to Google Analytics sight, it has not been installed correctly.

**Comment by anthonny** [comment]
Hi @RobertGiff ,

In the Google analytics field in the settings, you must put your tracking id, not the javascript snippet.
Just put : UA-59653924-1

**Comment by RobertGiff** [comment]
Thanks for the fast feedback!
I'm waiting for the next time it checks to see if it installed correctly. If it works I'll close this. 

Thanks so much!

**Comment by RobertGiff** [comment]
Google Analytics has updated but it is still telling me that I have failed to install the tracker.

**Comment by anthonny** [comment]
I suppose it's ok ? :smile:

**Comment by RobertGiff** [comment]
It just randomly started working..*shrugs*

**Comment by jeffmaury** [comment]
I have the same problem. Google Analytics tells me it is not installed. Any clue ?
