### ISSUE TITLE
Forked repository gives a 404 when named username/hupress.io

### ISSUE THREAD

**Issue by djacquel** [HubPress/hubpress.io#64]
I've just forked **https://github.com/HubPress/hubpress.io** to **https://github.com/statiktest/hubpress.io**.

When going to **http://statiktest.github.io/hubpress.io/** I get a 404 error.

Renaming the forked repo to **https://github.com/statiktest/hubpress** and going to **http://statiktest.github.io/hubpress/** works.

I've also tested on a repository with custom domaine name and it was the same **.../hubpress.io** KO, **.../hubpress** OK.

**Comment by jay3dec** [comment]
U need to rename it as `username.hupress.io`

**Comment by anthonny** [comment]
Hi @djacquel ,

I can't reproduce with an existing account http://demo-hubpress.github.io/hubpress.io/
Maybe there is a little delay before the url become available, i'll make test with a fresh account

@jay3dec thank you for your participation :+1: , but every attempt of @djacquel should work. Renaming the repository to username.*github.io* is only required if you use the master branch. @djacquel work actually on the gh-pages :

**Comment by anthonny** [comment]
@djacquel , that's really strange, you can delete your repository and refork please ?

**Comment by djacquel** [comment]
This is a really strange bug.

First time I fork  https://github.com/HubPress/hubpress.io to https://github.com/statiktest/hubpress.io.
There is no reaction. No generation and no error email from google.

I rename the repository to **hubpress**, this instantly works.
I rename back the repository to **hubpress.io**, this also works.

I get in touch with github support for this, I'll give feedback ASAP.

**Comment by jaredmorgs** [comment]
Any update from GitHub @djacquel ? Should we just close this issue?

**Comment by djacquel** [comment]
No news from github. But I can still reproduce it.
