### ISSUE TITLE
Create a docs page.

### ISSUE THREAD

**Issue by ryanmavilia** [HubPress/hubpress.io#66]
I can't contribute too much to the project due to experience but I could write documentation for it. I started a wiki however an actual docs page may be the better route to take.

**Comment by ryanmavilia** [comment]
We could just have a hub press blog like the ghost user guide (can't link on mobile) where selected people can write changes or they could possibly fork the support repo then push requests (if that is possible it would probably be messy). 

Let me know what you think!

**Comment by anthonny** [comment]
@ryanmavilia 

Sorry i'm completely busy atm :smile: 
A wiki is certainly a good thing in a first time.
For a blog with contributors, i need to work more on the organisation and the roadmap of the project, but it's a great idea :+1:

**Comment by ryanmavilia** [comment]
Glad to hear it if you can keep me updated! I'll beginning working on the wiki this weekend.
