### ISSUE TITLE
Organization blogs?

### ISSUE THREAD

**Issue by caryfitzhugh** [HubPress/hubpress.io#67]
Hi!

I couldn't log in, and then, poking around in the console, I realized that the API is trying to hit 
```
  /username/<repository>
```

In my case, that doesn't work since the username is me and the repository lives under the organization.

If someone wanted to point me in a direction, I could add some code?

Ideas?

For now I'll leave it on my repo - but moving it to the organization, and letting others write to it, etc. would be mighty nice!

**Comment by caryfitzhugh** [comment]
OK! Nevermind! I needed to put the username as the organization in the config.json..

Sorry!

Thanks! This looks sweet!

**Comment by anthonny** [comment]
No problem ;) Have fun with HubPress !

**Comment by caryfitzhugh** [comment]
Hrm. Well - maybe I spoke too soon.  I can log in now, and I can change the settings, but not create posts. ?  It tells me to look in the console for the error - but I see nothing of interest there.

**Comment by caryfitzhugh** [comment]
And.. I'm a dork. I shall no longer comment until I RTFM...

oy! Blog titles!

**Comment by anthonny** [comment]
:smile:
