### ISSUE TITLE
Use transaction with Dexie.js

### ISSUE THREAD

**Issue by anthonny** [HubPress/hubpress.io#69]

**Comment by az8321550** [comment]
I have the same question
why always 404 in the login page???

**Comment by anthonny** [comment]
hi @az8321550, sorry i didn't see your comment :cry: 
You must set your **username** and **repositoryName** in the **hubpress/config.json** of your branch **gh-pages** : 

```
{
  "meta": {
    "username": "az8321550",
    "repositoryName": "hubpress",
    "branch": "gh-pages"
  },
  "theme": {
    "name": "Casper"
  }
}
```
