### ISSUE TITLE
[Docs] Minor change to README.adoc

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#7]
Hey there @anthonny 

Just noticed a really small issue with the Own Domain/GH Pages instruction set.

Step 3 reuses the same image from the "untouched GitHub Pages" instructions, which shows the `master` branch. It should show the `gh-pages` branch in the screenshot.

![screenshot_2015-02-05-20-16-49](https://cloud.githubusercontent.com/assets/952793/6058588/6665b53a-ad74-11e4-9b1e-57cf06e6ecc4.png)

I wanted to change this for you, but I'd have to re-checkout the repo, and make the minor change. Could I trouble you to take the screenshot and do the minor tweak. No extra words should be required. Just the screenshot. 

It actually confused me not having the correct branch selected in the screenshot, so we should fix it. 

(hah, "we" should fix it). ;)

**Comment by anthonny** [comment]
:+1: **we** should fix it, I am going to take care of it in my lunch break !
