### ISSUE TITLE
Login screen isn't working

### ISSUE THREAD

**Issue by averyburnettmiller** [HubPress/hubpress.io#70]
Hey! I've followed the instructions, but when I go to mechadonkeys.averymiller.org/hubpages, I get a loading screen. It just keeps doing this. What did I do wrong?
Thanks,
Avery
![screenshot 2015-02-12 at 5 51 28 pm](https://cloud.githubusercontent.com/assets/4822424/6178731/d6265fda-b2df-11e4-9ed2-3b6b8e2864eb.png)

**Comment by anthonny** [comment]
Hi @averyburnettmiller !

Please, can you delete manually your CNAME file ?
Then go to http://averyburnettmiller.github.io/Mechadonkeys/hubpress

Log in and go to the settings page, then set github.averymiller.org in the CNAME field and submit.
A new CNAME file appear in your repo.

**Comment by averyburnettmiller** [comment]
Hey! I still get a loading page.
