### ISSUE TITLE
Unauthorized access when posting & saving settings

### ISSUE THREAD

**Issue by fnky** [HubPress/hubpress.io#73]
Using a [repository of a organization](https://github.com/onx/onx.github.io), where I have ownership, doesn't allow for POSTing content to Github—e.g. posting blog posts & saving settings.

I'll get the following output in console:

```
 PostsActionCreators - remoteSave
app.js:247 PostsActionCreators - remoteSave e8496f95-eb3a-4bd5-9484-76ea708d5d3d
app.js:4824 SettingsStores - dispatcher
app.js:4825 SettingsStores - dispatcher Object {type: "REMOTESAVE_POST", id: "e8496f95-eb3a-4bd5-9484-76ea708d5d3d"}
app.js:4434 AuthStores - dispatcher
app.js:4435 AuthStores - dispatcher Object {type: "REMOTESAVE_POST", id: "e8496f95-eb3a-4bd5-9484-76ea708d5d3d"}
app.js:4892 ThemeStores - dispatcher
app.js:4893 ThemeStores - dispatcher Object {type: "REMOTESAVE_POST", id: "e8496f95-eb3a-4bd5-9484-76ea708d5d3d"}
app.js:4579 PostsStores - dispatcher
app.js:4580 PostsStores - dispatcher Object {type: "REMOTESAVE_POST", id: "e8496f95-eb3a-4bd5-9484-76ea708d5d3d"}
app.js:4321 AppStores - dispatcher
app.js:4322 AppStores - dispatcher Object {type: "REMOTESAVE_POST", id: "e8496f95-eb3a-4bd5-9484-76ea708d5d3d"}
app.js:3929 PostsServices - remoteSave
app.js:3930 PostsServices - remoteSave e8496f95-eb3a-4bd5-9484-76ea708d5d3d
api.github.com/repos/onx/onx.github.io/contents/_posts/2015-02-13-Get-Jiggy-with-6to5.adoc?1423803815503:1 GET https://api.github.com/repos/onx/onx.github.io/contents/_posts/2015-02-13-Get-Jiggy-with-6to5.adoc?1423803815503 401 (Unauthorized)
app.js:310 PostsActionIDBCreators - receiveRemoteSave
app.js:311 PostsActionIDBCreators - receiveRemoteSave Object {message: Object}
app.js:4824 SettingsStores - dispatcher
app.js:4825 SettingsStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js:4434 AuthStores - dispatcher
app.js:4435 AuthStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js:4892 ThemeStores - dispatcher
app.js:4893 ThemeStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
app.js:4579 PostsStores - dispatcher
app.js:4580 PostsStores - dispatcher Object {type: "RECEIVE_REMOTESAVE", post: undefined, message: Object}
```

I have registred and logged in with this account (fnky), which wasn't an issue.

**Comment by anthonny** [comment]
Hi @fnky !

Your config seems to be good, 2 questions : 

1. Do you use 2FA authentication ?
2. Can you show me the content you try to save ?

**Comment by fnky** [comment]
1. No :-)

2.
```
= Get Jiggy with 6to5
:hp-tags: 6to5, JavaScript, ECMAScript

I recently went to get my hands dirty with https://6to5.org/[6to5]. So far, I like it a lot! I don't know wether it's writing ECMAScript 6 or because of the process.

It's stupid simple to setup and get started with. I tend to use https://gulp.io[Gulp] to automate my process, which makes life so much easier. But you can use whatever method you'd like.

[source,js]
----
var gulp = require('gulp');
var to5 = require('gulp-6to5');

gulp.task('to5', function() {
	return gulp.src('src/**/*.js')
        .pipe(to5)
    	.pipe(dest('dist'));
});
----

And then just run it like so:

[source,bash]
$ gulp to5

Pretty awesome huh.
```

and in I tried to change Title and Description.

**Comment by fnky** [comment]
Ok, this is weird. It seems to be working now. It has posted the post that couldn't be saved before (the one above) and just now I made a test post, which gave me no errors.

Seems that Github needed to update it's authentications. Might have to be documented, since I've seen other issues similiar to this, which had the same outcome.

**Comment by anthonny** [comment]
Glad to read that it is good for you now.
The delete is not implemented yet, you can unpublish a post.
If you have a new post to write, you can replace the content of an existing itwill produce a new post.

That's i did not implement the delete process for the preview

**Comment by fnky** [comment]
All right. Is there any way to contribute to the source code?

**Comment by ryanmavilia** [comment]
You can edit your forked version of the repo and add code. After you are done adding code you can push your code to this main repo which will create a pull request that the creator can approve. Hope that helps!

**Comment by fnky** [comment]
Aren't there any tools for building the app? Seems like a rather challenging process.

**Comment by anthonny** [comment]
see https://github.com/HubPress/hubpress.io/issues/37

**Comment by Carreau** [comment]
FYI, Got same issues. Had 2FA enabled. Work after ~10 minutes waiting.

**Comment by jaredmorgs** [comment]
Hey @anthonny 

Should we start a Roadmap on here so we can link up issues to it?

**Comment by jaredmorgs** [comment]
I'm calling this issue invalid (don't really like this label, but I'll run with it). Seems like it was a bit of a glitch with GitHub's 2FA. Issues about Delete Posts and Building from Source are separate issues covered elsewhere.
