### ISSUE TITLE
how to delete post

### ISSUE THREAD

**Issue by syswow** [HubPress/hubpress.io#74]
Hi, 
I rm the post, but the hubpress dash still show the index and the post.

**Comment by ryanmavilia** [comment]
Syswow edit your post then at the bottom right you should see a unpublish button next to the save button.

**Comment by anthonny** [comment]
Hi @syswow !

@ryanmavilia :+1: thank you, that's right to remove a post from the index, you must **unpublish** it.
Delete is not implemented yet.

As much as possible, try to make every change through hubpress not directly on your repo :smile:

**Comment by syswow** [comment]
It Works, Thanks.
I will close the issues.
