### ISSUE TITLE
Better workflow for making themes

### ISSUE THREAD

**Issue by fnky** [HubPress/hubpress.io#75]
Currently making themes for Hubpress is quite difficult process. It's not an easy task to setup the Hubpress from Git repository on a local machine and get everything working.

It could be done using a boilerplate template, which has tools to debug and build the theme.

**Comment by anthonny** [comment]
Hi @fnky !
You're right, like you, i think we need a tool :) :+1:

**Comment by jaredmorgs** [comment]
What type of vision do you have for the Theming Tool, @anthonny 

I think it would be good to get an idea about direction for this feature. @fnky, you're still interested in this type of feature, correct?

As a user, how would you like this tool to work, over what you have already suggested.

**Comment by jaredmorgs** [comment]
Let's rethink how we are going to support themes as part of the work being done for 0.7.0 onwards.
