### ISSUE TITLE
Multiple Users?

### ISSUE THREAD

**Issue by caryfitzhugh** [HubPress/hubpress.io#76]
Hola! Liking hubpress so far, thanks a lot.

A question arises - I had thought that whenever you saved / changed something on hubpress, it would serialize some JSON and commit it to the repository.  And when you opened the hubpress page, it would read that data out and display it. Similar to google docs.

As of now - it appears that all your post data is inside IndexedDB - which is great, in a way.  
But it does mean that I am unable to share posting with a friend (since if he adds a post, I believe the index page will be re-written as if his posts were the only ones available).  And likewise for myself.

The other trouble comes if I wanted to post from a different machine or a different browser, I would be unable to do that.

When you login, change settings, save a post, publish/unpublish - seem to be the times you would want to serialize your data, and push it to github.  Github may do a "pretty good" job of merging changes.  If there are conflicts... well - I'm not sure there is a great answer there. But for me, having this ability and even some draconian approach for conflict resolution (latest wins?) would be preferrable.  I find it hard to believe, that structured correctly, there would be many issues.  Keep each post in a directory, prefixed by username.  The only place conflicts could occur then would be... in the settings page? And in that case, latest wins.

Dunno.. thoughts?  I'm up for providing implementations if it's something you're interested in.

**Comment by anthonny** [comment]
Hola @caryfitzhugh :smile: !
I am glad that you like HubPress :+1: 

I'll explain the process.

## Login
When you login in HubPress, there is a synchronization, 
1. i get all the posts in the directory **_posts**, 
2. i extend each post with some attributes (html, isPublished, title, tags ...) 
3. i save each post in an IndexedDB in a table called posts.

> In the preview, synchronization occurs only on login, in a futur version i'll add a sync button.

## Editing
When you edit a post : 
1. each time you press a key, i convert the asciidoc content in html and i save the post in IndexedDb. If you close your browser or if your computer shutdown you have a locally recover. It's a "local" draft.
2. when you save the content with the button save, i push your content on github in the **_posts** folder. It's a "remote" draft.
3. when you publish your post, i push the HTML content of your post in the directory YYYY/MM/DD/title.html, and i rebuild pagination (index, page/2, ...).
4. If you save a post that you have published, i push the HTML content of your post in the directory YYYY/MM/DD/title.html, and i rebuild pagination (index, page/2, ...).

## Posts list
The border show some indication : 
1. orange == you have local change that you should remote save or publish
2. green == your post is published, no local change
3. no color == your draft is save remotely, no local change

## Settings
When you change settings : 
1. i take all the published posts in the IndexedDb
2. i rebuild the HTML of each post and push, 
3. then i rebuild pagination (index, page/2, ...).

------
I think it's more clear now, what happen if you work in team, or on multi device : 
1. latest wins,
2. in the preview, if you change the settings, all published posts will be rebuild and the author will be you. I'll work on this, be actually that's the behaviour
3. You can't share local draft

**Comment by jaredmorgs** [comment]
Hey @anthonny

I've noticed a bit of lag as I continue writing a larger post. For example, when I press and hold the delete key, the way the text is deleted on screen is choppy. The same goes for typing: text input lags about half a second behind keystrokes.

I have a feeling this could be solved by changing the live preview update to around 2 seconds (maybe 3, if this wouldn't result in users thinking there was "delay" in rendering), rather than instantaneously as it seems to be now.

I'm making this judgement based on how you described the process by which HubPress renders and writes a local recovery copy of the blog to memory so content isn't lost if the browser crashes. I have a feeling this could be causing a performance regression as the cached file grows.

**Comment by jaredmorgs** [comment]
I've documented how multiple user blogging works in HubPress over in the Knowledgebase.

https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/multiple_authors.html

I'll leave it up to close as the originator @caryfitzhugh if you are satisfied with the documented solution. If you think anything else is missing regarding multi-user docs, please let me know in this ticket and I'll take care of it.

**Comment by caryfitzhugh** [comment]
thanks!
