### ISSUE TITLE
Add AsciiDoc snippet buttons to help new users to onboard easily

### ISSUE THREAD

**Issue by anthonny** [HubPress/hubpress.io#77]
Add snippets in the Ui for a better UX proposal made by @jaredmorgs

**Comment by jaredmorgs** [comment]
Thanks for creating it, @anthonny nthonny.

The snippets I think would be great to have would be some of the image ones (with placeholder text):

* Hosted images - like you blogged about - cool feature!
* GitHub Stored Images
* Numbered List
* Bulleted List

What other snippets have folks told you about?

Looking at the UI, I think these buttons could be put on the left top bar of the left pane. The real trick will be getting the right iconography to use. The icons you have for the current UI buttons are really lovely, and it would be great to get more of these into the UX.

**Comment by anthonny** [comment]
wdyt about http://fortawesome.github.io/Font-Awesome/icon/code/
Then it could open a popup, you choose the snippets to apply.

**Comment by jaredmorgs** [comment]
Yeah, that's a lovely set of consistent icons. I trust you can invert the
colours and all that good stuff?

There's plenty of options for quick add buttons like the list and numbered
list as well. So you could have a balance of quick buttons for common stuff
like lists (only for those folks new to marking up AsciiDoc, and complex
mark-up in a popout list.

Not sure if you could code it in or not, but a copy paste button that dumps
the mark-up into the left pane would be sweet!

You could slide out the mark-up help menu over the rendered view, then it
would auto hide after a selection was made, or the UI button was tapped
again (similar to how the show/hide live render button works).

What do you think?

**Comment by jaredmorgs** [comment]
closing this off in preference of #485
