### ISSUE TITLE
login page's problem

### ISSUE THREAD

**Issue by vickydasta** [HubPress/hubpress.io#78]
i don't have any idea why,but the login page didn't comin up even after waiting for 5 minutes,
any idea why ?

**Comment by anthonny** [comment]
Hi @vickydasta !

Welcome in HubPress :smile: 

In the settings of your repository, you must set gh-pages as default branch.
Then, in your gh-pages branch, you must edit your config.json like this : 

```
{
  "meta": {
    "username": "vickydasta",
    "repositoryName": "hubpress.io",
    "branch": "gh-pages"
  },
  "theme": {
    "name": "Casper"
  }
}
```

**Comment by vickydasta** [comment]
@anthonny i've done that before

**Comment by anthonny** [comment]
With this configuration, your blog is enable at : 
http://vickydasta.github.io/hubpress.io

**Comment by vickydasta** [comment]
oh,surely,and the administrator/login page is : 
http://vickydasta.github.io/hubpress.io/hubpress/login
but,the only thing that i can see after 5 minutes is just the circle loading icon

![login page's screenshoot](https://cloud.githubusercontent.com/assets/7861544/6199422/56179358-b475-11e4-82be-7440583b18d5.png)

**Comment by vickydasta** [comment]
i'm not a web developer or something like that,so sorry for annoying you with this issue,i wish i could help you to solve this problem

**Comment by anthonny** [comment]
no problem, please add me as collaborator in your repo
You can do that in the settings of you repository

**Comment by vickydasta** [comment]
ok,wait then

**Comment by anthonny** [comment]
it's not work because in your **config.json**, your `repositoryName` must be : 
```
"repositoryName": "hubpress.io",
```

**Comment by anthonny** [comment]
I updated your config.json, now please set the default branch

**Comment by vickydasta** [comment]
i'm already set the default branch into gh-pages

**Comment by anthonny** [comment]
Ok, just to be sure, i'm not talking about this (in your config.json) : 
```
 "branch": "gh-pages"
```

I'm talking about the default in the settings of your Github repository : 
![capture d ecran 2015-02-14 a 12 31 18](https://cloud.githubusercontent.com/assets/2006548/6199485/b72111ee-b446-11e4-93a3-3ca8115c33a0.png)

I insist a little because when i look at your repository (https://github.com/vickydasta/hubpress.io) i see that : 
![capture d ecran 2015-02-14 a 12 38 14](https://cloud.githubusercontent.com/assets/2006548/6199488/efa2c652-b446-11e4-93ce-0e658da5d343.png)

The value of branch should be **gh-pages**

**Comment by vickydasta** [comment]
,i'm much sure i've changed the branch before 
i've changed the branch for the second time,into gh-pages,what then?

**Comment by anthonny** [comment]
then it should work

**Comment by vickydasta** [comment]
uh,so sorry for being so stupid,
thanks a lot !! :+1:

**Comment by anthonny** [comment]
You're welcome ! There isn't stupid question, just question.

**Comment by kmontenegro** [comment]
similar issue: either as master or gh-pages login isn't working. set it up per the instructions/readme.md.

adding you as a collaborator to help identify the issue. in advance, thanks! great work!

**Comment by anthonny** [comment]
Hi @kmontenegro !
It's work for me, which browser do you use ?
![capture d ecran 2015-02-15 a 21 21 35](https://cloud.githubusercontent.com/assets/2006548/6204833/a70833ce-b558-11e4-8aae-f29785c59906.png)

**Comment by kmontenegro** [comment]
I'm using Chrome on Mac OS X. Was able to replicate the issue in on MBPro & MBAir BUT now can get in if I use Safari. Wondering if it has something to do with cached credentials though I cleared both out in Chrome.

I should have tested in another browser! Thanks!

**Comment by anthonny** [comment]
HubPress can't work with safari because safari doesn't support IndexedDB.

It should work with chrome (not chrome beta) . Try to clear your cache

**Comment by kmontenegro** [comment]
Thanks! Had cleared my cache on both machines but once I was in on Safari, I was able to get in on Chrome. Merci, merci and have a wonderful week!

**Comment by ashgene** [comment]
I am facing the same problem and havent been able to set up hubpress even after trying all solutions.
