### ISSUE TITLE
[UX] [Settings] How to set Logo and Cover Image

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#8]
![Logo and Cover Image](https://cloud.githubusercontent.com/assets/952793/6059271/3d144686-ad7b-11e4-8db2-340dca7d1eb0.png)

What I've done is created an /Images/ directory in my repo, and put the full URL to the image. For the record, it did have a /blob/ in the URL, but I stripped that out thinking it was the issue.

The problem is the images are not loading. I'm not sure whether it is just an issue with the URL or not.

Any ideas @anthonny?

**Comment by anthonny** [comment]
You can use the raw url : 
https://raw.githubusercontent.com/jaredmorgs/blog/gh-pages/Images/logo.jpg
https://raw.githubusercontent.com/jaredmorgs/blog/gh-pages/Images/blog_cover.jpg

Or : 
http://jaredmorgs.github.io/blog/Images/logo.jpg
http://jaredmorgs.github.io/blog/Images/blog_covert.jpg

You should rename **Images** to **images**, i defined **images** as default value of the **imagesdir** attributes.

**Comment by jaredmorgs** [comment]
Great info for the README about the images directory. Perhaps you should
put the directory in the master repo so folks don't have to create it? I'll
write something up.

**Comment by anthonny** [comment]
:+1:  Just added :) (43053e4)
I added the theme Roon too

**Comment by anthonny** [comment]
I think we can close the issue ?

**Comment by jaredmorgs** [comment]
Sure can.
