### ISSUE TITLE
Duplicate posts and can't unpublish.

### ISSUE THREAD

**Issue by ryanmavilia** [HubPress/hubpress.io#82]
I have two of the same Hello World posts. One duplicated itself when I was trying to update it. The post that is showing up can't be clicked because it is an invalid link.

Since there is no delete function this is very problematic for me and a clear bug.

My blog: http://unoriginality.me

**Comment by anthonny** [comment]
Hi @ryanmavilia ,
If you can describe the steps you have done to get this bug, i'm interested.

To solve this problem, we will clear your local data.

1. Make remote save of your draft,
2. Log out from HubPress,
3. Open developer tools (cmd + option + i / ctrl + shift + i)
4. Go in the Resources tab
5. In IndexedDB, you'll see **hubpress-xxxxx** with a element named **posts**, click on **posts**
![capture d ecran 2015-02-15 a 09 16 21](https://cloud.githubusercontent.com/assets/2006548/6202579/aa4dd47c-b4f3-11e4-8731-d16eb65c3b08.png)
6. Click on the "erase" button : 
![capture d ecran 2015-02-15 a 09 20 28](https://cloud.githubusercontent.com/assets/2006548/6202581/eac2b6da-b4f3-11e4-83dd-cdcb716a598a.png)
)

Now login in HubPress, you should see only one post now

**Comment by ryanmavilia** [comment]
Well I fixed the bug and I can't remember how I got it. I know that I had a post that had no published_at so I decided to try to add it to see if it would update. I added it and then tried to save and publish and it wasn't working when I would look at my blog so I began trying to move around the published_at thinking that its placement was incorrect. Eventually it updated and then I had a second post of the same name. Just tried to recreate it to no avail.

**Comment by ryanmavilia** [comment]
And.. now I have a infinite loading page on my posts after I re-deleted the indexdb (silly me)
![test](https://cloud.githubusercontent.com/assets/1221512/6202638/c337681a-b4c4-11e4-93ce-52a611263519.PNG)

**Comment by anthonny** [comment]
Same if close your browser and clear cache ?

**Comment by ryanmavilia** [comment]
Ok that worked however now I made a new post and published it but it is creating this link http://unoriginality.me20150209-obligatory-hello-world.adoc/ which is obviously invalid.

**Comment by anthonny** [comment]
It's because : 
```
:published_at: 2015/02/09
```
must be : 
```
:published_at: 2015-02-09
```
https://github.com/HubPress/hubpress.io#publication-date

**Comment by ryanmavilia** [comment]
Ok well good news and bad news. Changing the date format and then publishing works and it fixed the problem. However my post was still red (as if I didn't publish it) so I relogged and then boom! I once again had duplicate posts, hoping that will help you track down the bug. (One post is published, the other is not and the one that is not published is the one with :published_at: 2015/02/09)

**Comment by anthonny** [comment]
Ok, delete manually from github the bad post.
Logout from HubPress, clean your IndexedDB and Login

**Comment by ryanmavilia** [comment]
Everything seems to be in order now :smile: thanks!

**Comment by anthonny** [comment]
Thank you for reporting :+1:
