### ISSUE TITLE
Add Disqus functionality

### ISSUE THREAD

**Issue by ziyaddin** [HubPress/hubpress.io#84]
It will be great if you add Disqus comment functionality for blog posts.

**Comment by anthonny** [comment]
Hi,

You can already add Disqus, you just have to set your Disqus shortname in the settings screen

**Comment by ziyaddin** [comment]
That's great! Thank you! :+1:

**Comment by ziyaddin** [comment]
I have this message:
![unable](https://cloud.githubusercontent.com/assets/1016523/6203273/487a3224-b532-11e4-80e0-7d19a3a8ef5f.PNG)

Am I doing something wrong?

**Comment by ziyaddin** [comment]
Okay, I solved it. The issue is that it works in newly posted blog posts, the old ones have the same problem. After setting Disqus shortname, we post a new blog post and it works in new ones.
