### ISSUE TITLE
[Bug] Deleting Posts in GitHub UI Does Not Replicate In HubPress

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#86]
I have noticed that if I change the name of the blog post, HubPress creates a new copy of it. As a result, I've been going through the process of deleting the duplicate posts through the GitHub UI, but the changed repo state is not reflected in HubPress. I can't easily clear the HubPress database because I'm on Chrome for Android.

Is there a way to make HubPress trigger a local Database refresh when it detects changes made outside of the confines of the authoring environment?

Could I delete all the HTML folders (the 2012, 2013, 2014, sorted by year).

**Comment by anthonny** [comment]
Relog should resync your localdb

**Comment by jaredmorgs** [comment]
I tried that, but it doesn't work. 😞

**Comment by anthonny** [comment]
I made a test with my phone, i renamed a published post, the post is not duplicate but rename.

**Comment by jaredmorgs** [comment]
Hmm, that is peculiar indeed. I wonder whether the issue was how I created the posts. I started from scratch when I deleted my old HubPress repo, but kept a remote with the blog posts present so I could copy and past the text over. I did each one individually through the HubPress UI, so I'm not sure how I got duplicates.

**Comment by jaredmorgs** [comment]
I'm going to close this for now Anthonny. I think it might have been a one-off edge case.
