### ISSUE TITLE
[Bug] Synchronizing Database State Across Devices

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#87]
I think I've discovered a limitation of HubPress if you use it on multiple devices. If you make changes on one device, and have a token on another device, the second device does not get a refreshed state of the updates.

I'm going to check now whether clearing Chrome Cache and Data will reset the database. I would think this rather drastic step would do this. 

**Update** 

This workaround does work for blogs that have become out of sync with reality.

**Comment by anthonny** [comment]
@jaredmorgs it should be fixed with the last version, can you give it a try?

**Comment by jaredmorgs** [comment]
I'll rebase and give it a go tomorrow.

**Comment by anthonny** [comment]
@jaredmorgs is it ok for you?

**Comment by jaredmorgs** [comment]
Way overdue for testing this issue out @anthonny 

Sorry for the delay: I have verified that database sync works flawlessly between devices now.
