### ISSUE TITLE
Ichi About Page

### ISSUE THREAD

**Issue by ryanmavilia** [HubPress/hubpress.io#89]
Is there a way to simply create the ichi "about" and contact page for users? I know I could easily make the pages myself through the repo but for others this may not be such a simple task.

**Comment by anthonny** [comment]
Hi @ryanmavilia !

HubPress doesn't support page yet, i'll remove link from the theme in the next version.
I think i must check every themes and remove 404 link (rss, author page...)

**Comment by jaredmorgs** [comment]
I'm closing off this issue as it would be implemented on #438
