### ISSUE TITLE
[Bug][UX] Switching Between Chrome Android Tabs Deletes Cached Setting Data

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#9]
I've been switching between Chrome tabs copying links to populate the Social Media links.

When I returned to the HubPress Settings page, which was open between tab switching, the page refreshed, and the already entered info was all erased.

Using some lateral thinking, I tapped the Chrome back button and then reloaded the Settings page. The cached data returned and I was able to continue.

Is this a caching issue (like a timeout issue) on the settings config page?

Is there a way to pause the timer if the tab loses focus?

As a new user (who kind of knows that this type of stuff happens) it took me by surprise. I can guarantee that non-geek bloggers will freak out if they see this. 

Could you put some sort of toast message that displays the editing time remaining?

**Comment by anthonny** [comment]
I think it's the default behaviour of chrome on android.
There isn't caching or timer on the settings screen, i don't know how to deal with that problem yet

**Comment by jaredmorgs** [comment]
I wonder if we should have a Known Issues link in the app, or in the docs somewhere. Maybe we can pull them all from GitHub using the flags. Might save some duplicates?

**Comment by jaredmorgs** [comment]
I"m calling this an edge case. I doubt it would happen that often for the average HubPress user, so I'm closing it out.
