### ISSUE TITLE
writing code

### ISSUE THREAD

**Issue by Bloggerschmidt** [HubPress/hubpress.io#92]
When I write something like 

[ source , html ]
_  _  _  _
< div id="superid" >sometext</ div >
_  _  _  _ 

it renders something like

< pre >< code >
< div id="superid" >sometext</ div >
</ code ></ pre >

But it should render like this

< pre >
< div id="superid" >sometext</ div >
</ pre >

without < code >. Is this a theme thing?

**Comment by anthonny** [comment]
Hi @Bloggerschmidt ,

It's not a theme thing, this code is generated by asciidoctor.js
Feel free to open an issue on this project https://github.com/asciidoctor/asciidoctor.js

**Comment by Bloggerschmidt** [comment]
Okay. done. https://github.com/asciidoctor/asciidoctor.js/issues/103
Thx for reply.

**Comment by anthonny** [comment]
You're welcome
