### ISSUE TITLE
how to delete an item?

### ISSUE THREAD

**Issue by Bloggerschmidt** [HubPress/hubpress.io#93]
What's the workarround to delete an item cleanly?

**Comment by anthonny** [comment]
Is it local draft ? or remote draft (the .adoc file is on github) ?

**Comment by Bloggerschmidt** [comment]
It's a remote draft on github. Unfotunatly after pointing my main domain via cname a post only published with success at the first time. After editing the post there is always an error. Is it right to login the master branch and publish on gh-pages?

Am 16. Februar 2015 16:31:09 MEZ, schrieb "Anthonny Quérouil" <notifications@github.com>:

**Comment by anthonny** [comment]
Bloggerschmidt.github.io point on your master, you should rename your repository to : 
**bloggerschmidt.de**

Then it should work (maybe after a delay)

**Comment by Bloggerschmidt** [comment]
Awesome! You made my day. How can I give you something back? Maybe a donation via PayPal. What's your paypal-email-address?

**Comment by ryanmavilia** [comment]
Haha @anthonny already making :moneybag: :moneybag: :moneybag: from this project!

**Comment by Bloggerschmidt** [comment]
well deserved :-)

**Comment by anthonny** [comment]
@Bloggerschmidt I do not know what to say in front of so much generosity :blush: 
I hesitated to put a button as Paypal or Gratipay, I did not know how that would be interpreted.

I do not know which is the best way of communicating on this matter, nor which is the best tools (paypal, gratipay)

My paypal account is anthonny.querouil@gmail.com

**Comment by Bloggerschmidt** [comment]
I know exactly what you mean. I have a similar project called "Blank" http://blank.vc/, a template for the cms Joomla, and it works to sell an ebook with a complete documetation. Maybe this is something you can consider.

**Comment by anthonny** [comment]
@Bloggerschmidt thank you for yours advices, i must think about this.

This week, i was thinking about crowdfunding like kickstarter but i don't know if it's good.
A survey should be interesting to have the opinion of the users.
