### ISSUE TITLE
Have you considered using Branches or Tags for "Released Versions"?

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#95]
Hi @anthonny 

I was wondering whether you might consider creating branches for releases considered "Stable". 

I like to rebase from upstream regularly, but I'm sometimes not sure at what stage of development some commits are at?

Does this make sense to do for this project? I could document it in the Readme, and you could announce using social media that a new stable version is released and users should update. 

Just a thought, mate. Keep up the awesome work. I'm really enjoying using HubPress. It makes me want to blog more and more.

**Comment by anthonny** [comment]
Hi @jaredmorgs !

I think i'll create a branch **development** with the sources soon, then i think i'll make a version every 3 weeks with a tag. The process will be : 

1. Tag development when it's ready for release,
2. Build a **dist** version from development and push the dist in **master** and **gh-pages**.
3. Tag master **master** and **gh-pages** something like **dist-master-<release version>**
4. Create a tool to update a user repository, the tool takes the master and gh-pages tags and updates user branchs

wdyt?

**Comment by ryanmavilia** [comment]
👍👍👍

**Comment by jaredmorgs** [comment]
I think we have this covered from a process perspective on https://hubpress.gitbooks.io/hubpress-knowledgebase/content/develop/contribute_pr.html

The update button is now also covered in https://hubpress.gitbooks.io/hubpress-knowledgebase/content/admin/update_hubpress.html

I'm going to close off this issue.
