### ISSUE TITLE
support emoji ?

### ISSUE THREAD

**Issue by syswow** [HubPress/hubpress.io#96]
Hello, 
Emoji is funny, can we add emoji to our post ? :smile:

**Comment by ryanmavilia** [comment]
@syswow just have a look at my last blog post. My site: unoriginality.me :smile:

**Comment by ryanmavilia** [comment]
If you are on a computer just use http://getemoji.com/ to find the emoji you want. It may not look like an emjoi but when you are on your phone the standard look will be there :+1:

**Comment by syswow** [comment]
@ryanmavilia  I cannot see the emoji. 
I using ubuntu 14.04, chromium, default font. should I change the font?

![screenshot from 2015-02-18 01 29 47](https://cloud.githubusercontent.com/assets/10815286/6233437/cfe96388-b70d-11e4-93ce-0c12d0344079.png)

**Comment by ryanmavilia** [comment]
Booting up my laptop that has crunchbang and chromium to test!

**Comment by ryanmavilia** [comment]
So I can't view them either which led me to some Googling which led me to http://www.omgubuntu.co.uk/2014/11/see-install-use-emoji-symbols-ubuntu-linux so simply follow the instructions on that page. I have a different distro (#!) but I found the package and installed it. I can proudly say that the emoji's are showing up now. However they are very ugly if not viewed from an iOS device so as a blogger I would recommend you not use them :stuck_out_tongue:

**Comment by jaredmorgs** [comment]
Close this as wontfix @HubPress/contributors  , @syswow ?

Seems like it is an OS-specific rendering issue?

**Comment by syswow** [comment]
Yes
